### ISSUE TITLE
Icon request: ESET

### ISSUE THREAD

**Issue by ghost** [krisu5/aegis-icons#355]
- URL of the site or app **(required):** https://eset.com
- Logo resources for the icon **(optional, but recommended):** https://upload.wikimedia.org/wikipedia/commons/f/f0/ESET_logo.svg

ESET MSP Administrator Site

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/ESET.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
