### ISSUE TITLE
Icon request: Notejoy

### ISSUE THREAD

**Issue by drinkcoffee247** [krisu5/aegis-icons#356]
Notejoy

- URL of the site or app **(required):** https://notejoy.com/
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Notejoy.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
