### ISSUE TITLE
Icon request: SoFi

### ISSUE THREAD

**Issue by fabulousartery** [krisu5/aegis-icons#358]
- URL of the site or app **(required):** https://www.sofi.com/
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/SoFi.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
