### ISSUE TITLE
Icon request: Blockchain.com

### ISSUE THREAD

**Issue by ghost** [krisu5/aegis-icons#360]
- URL of the site or app **(required):** www.blockchain.com
- Logo resources for the icon **(optional, but recommended):** www.blockchain.com/press
Blockchain.com Brand Assets

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Blockchain.com.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
