### ISSUE TITLE
Icon request: FACEIT

### ISSUE THREAD

**Issue by ghost** [krisu5/aegis-icons#361]
- URL of the site or app **(required):** https://faceit.com/
- Logo resources for the icon **(optional, but recommended):** https://corporate.faceit.com/branding/

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/FACEIT .svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
