### ISSUE TITLE
Icon request: ESEA

### ISSUE THREAD

**Issue by ghost** [krisu5/aegis-icons#362]
- URL of the site or app **(required):** https://play.esea.net/
- Logo resources for the icon **(optional, but recommended):** https://worldvectorlogo.com/de/logo/esea-2

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/ESEA.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
