### ISSUE TITLE
Icon request: Server-Eye

### ISSUE THREAD

**Issue by ghost** [krisu5/aegis-icons#363]
- URL of the site or app **(required):** https://server-eye.de/
- Logo resources for the icon **(optional, but recommended):** https://www.server-eye.de/presse/
- https://server-eye.de/wp-content/uploads/server-eye_logo2019-RGB.pdf

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Server-Eye.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
