### ISSUE TITLE
Icon request: FAX.PLUS

### ISSUE THREAD

**Issue by drinkcoffee247** [krisu5/aegis-icons#365]
FAX.PLUS

- URL of the site or app **(required):** https://www.fax.plus/
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/FAX.PLUS.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
