### ISSUE TITLE
Icon request: Files.com

### ISSUE THREAD

**Issue by drinkcoffee247** [krisu5/aegis-icons#366]
Files.com

- URL of the site or app **(required):** https://www.files.com/
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Files.com.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
