### ISSUE TITLE
Icon request: Greenhost

### ISSUE THREAD

**Issue by drinkcoffee247** [krisu5/aegis-icons#367]
Greenhost

- URL of the site or app **(required):** https://greenhost.net/
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Greenhost.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

**Comment by krisu5** [comment]
Because if you already haven't noticed, **all** the logos in the icon here are one-colored from the day one and we are not changing that guideline **ever**.

**Comment by krisu5** [comment]
Some logos have one-colored versions and some don't. We try to make logos with no official one-colored version to one-colored as fatefully as we can.

If you don't like, well I'm sorry but breaking our design guidelines would make our icons not visually consistent anymore and it would look like a mess.

Note also that some logos are really hard convert to one-colored.
