### ISSUE TITLE
Icon request: KeepSolid (Passwarden)

### ISSUE THREAD

**Issue by drinkcoffee247** [krisu5/aegis-icons#368]
Passwarden

- URL of the site or app **(required):** https://www.keepsolid.com/passwarden/
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Passwarden is part of KeepSolid products that uses "KeepSolid ID" account system, so I made icon for KeepSolid brand instead.

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/KeepSolid.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
