### ISSUE TITLE
Icon request: Republic Wireless

### ISSUE THREAD

**Issue by drinkcoffee247** [krisu5/aegis-icons#369]
Republic Wireless

- URL of the site or app **(required):** https://republicwireless.com/
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Republic%20Wireless.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
