### ISSUE TITLE
Icon request: Kite by Zerodha

### ISSUE THREAD

**Issue by mubaid** [krisu5/aegis-icons#370]
- URL of the site or app : kite.zerodha.com
- Logo resources for the icon : svg on the website

**Comment by krisu5** [comment]
Use Zerodha icon.

**Comment by mubaid** [comment]
Hello, Kite is a completely different product, but from Zerodha. Its like MS Office and Word/Excel?

**Comment by krisu5** [comment]
It uses Zerodha account to sign in, so it's still no. I'm not making icons for products that are linked to master brand.
