### ISSUE TITLE
Icon request: 2Checkout

### ISSUE THREAD

**Issue by mubaid** [krisu5/aegis-icons#371]
- URL of the site or app **(required):** https://www.2checkout.com/
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/2Checkout.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
