### ISSUE TITLE
Icon request: Sendy

### ISSUE THREAD

**Issue by mubaid** [krisu5/aegis-icons#372]
- URL of the site or app **(required):** https://sendy.co/
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Sendy.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
