### ISSUE TITLE
Icon request: Maxon

### ISSUE THREAD

**Issue by drinkcoffee247** [krisu5/aegis-icons#373]
Maxon

- URL of the site or app **(required):** https://www.maxon.net/en/
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Maxon.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
