### ISSUE TITLE
Icon request: Terraform Cloud

### ISSUE THREAD

**Issue by jahed** [krisu5/aegis-icons#374]
- URL of the site or app **(required):** https://app.terraform.io/
- Logo resources for the icon **(optional, but recommended):**
  - https://www.terraform.io/logos.html
  - https://simpleicons.org/?q=terraform

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Terraform.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
