### ISSUE TITLE
Icon request: Okta

### ISSUE THREAD

**Issue by jahed** [krisu5/aegis-icons#376]
- URL of the site or app **(required):** https://www.okta.com/
- Logo resources for the icon **(optional, but recommended):**
  - https://www.okta.com/press-room/media-assets/logos/
  - https://simpleicons.org/?q=okta

The colours in the main site and logo seem to be different than their login portal, for typical colours see the Simple Icons link or: https://play.google.com/store/apps/details?id=com.okta.android.mobile.oktamobile

They also don't seem to have an icon logo, it's just the word "okta". I've seen just the "o" used as an icon unofficially (see Simple Icons link). There's also the [Okta Verify](https://play.google.com/store/apps/details?id=com.okta.android.auth) icon but it's app-specific.

**Comment by krisu5** [comment]
I rather use color from the main site / branding page, most likely login portal's logo color is not updated.

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Okta.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

**Comment by krisu5** [comment]
@jahed Hey, sorry bothering you, but there's [Aegis issue](https://github.com/beemdevelopment/Aegis/issues/887) telling that they can't get Okta 2FA work on Aegis. [Alexbakker also tried this method](https://yingtongli.me/blog/2018/07/19/okta.html), but it doesn't work.

Is there other method to get Okta work on Aegis?

**Comment by jahed** [comment]
@krisu5 The method you linked does work but it might depend on your company's Okta policy. It's also possible Okta has removed that option to get more people to use their app.

Here's what I did a few months ago to get it to work: First use Okta Verify to create the initial account, then you can go to your account settings and register a normal 2FA app and remove Okta Verify.
