### ISSUE TITLE
Icon request: Oracle

### ISSUE THREAD

**Issue by amypot** [krisu5/aegis-icons#377]
- URL of the site or app **(required):** https://www.oracle.com/
- Logo resources for the icon **(optional, but recommended):** 
  - `<svg xmlns='http://www.w3.org/2000/svg' width='32' height='25' viewBox='0 0 32 25'><g fill='#C74634'><path d='M9.9,20.1c-5.5,0-9.9-4.4-9.9-9.9c0-5.5,4.4-9.9,9.9-9.9h11.6c5.5,0,9.9,4.4,9.9,9.9c0,5.5-4.4,9.9-9.9,9.9H9.9 M21.2,16.6c3.6,0,6.4-2.9,6.4-6.4c0-3.6-2.9-6.4-6.4-6.4h-11c-3.6,0-6.4,2.9-6.4,6.4s2.9,6.4,6.4,6.4H21.2'/></g></svg>`
   - https://simpleicons.org/?q=oracle

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Oracle.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
