### ISSUE TITLE
Update icon: Avast

### ISSUE THREAD

**Issue by amypot** [krisu5/aegis-icons#378]
- URL of the site or app **(required):** https://www.avast.com/
- Reason for update **(required):** Official website icon change
- Logo resources for the icon **(optional, but recommended):** 
  - https://static3.avast.com/10001938/web/i/favicon.svg
  - https://static3.avast.com/10001938/web/i/logo/avast-logo-default.svg

**Comment by amypot** [comment]
I recommend updating to v2 version

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Avast%20v2.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
