### ISSUE TITLE
New icon: ecobee

### ISSUE THREAD

**Issue by anginear** [krisu5/aegis-icons#379]
- URL of the site or app (required): https://www.ecobee.com

- Logo resources for the icon (optional, but recommended): [https://play.google.com/store/apps/details?id=com.ecobee.athenamobile&hl=en_US&gl=US](url)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/ecobee.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
