### ISSUE TITLE
Icon request: Nimbus Note

### ISSUE THREAD

**Issue by drinkcoffee247** [krisu5/aegis-icons#381]
Nimbus Note

- URL of the site or app **(required):** https://nimbusweb.me/index.php
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Nimbus%20Note.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
