### ISSUE TITLE
Icon request: Remote Utilities 

### ISSUE THREAD

**Issue by TKruzze** [krisu5/aegis-icons#385]
SIte URL: [Remote Utilities](https://www.remoteutilities.com/)

**Comment by EinfachRuwen** [comment]
**Logo Resources:** https://www.remoteutilities.com/favicon.ico

**Comment by krisu5** [comment]
> **Logo Resources:** https://www.remoteutilities.com/favicon.ico

Thanks, but ICO files usually are too small and such is this one. There's SVG in the homepage.

**Comment by EinfachRuwen** [comment]
Okay, sorry 😂

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Remote%20Utilities.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Remote%20Utilities%20bg.var.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
