### ISSUE TITLE
Icon request: Hauk

### ISSUE THREAD

**Issue by evany8** [krisu5/aegis-icons#387]
- URL of the site or app **(required):** https://github.com/bilde2910/Hauk
- Logo resources for the icon **(optional, but recommended):** https://raw.githubusercontent.com/bilde2910/Hauk/master/frontend/assets/favicon.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Hauk.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
