### ISSUE TITLE
Icon request: Spry Servers

### ISSUE THREAD

**Issue by paulusversluis** [krisu5/aegis-icons#392]
- URL of the site or app **(required):** https://www.spryservers.net/sprycloud
- Logo resources for the icon **(optional, but recommended):** No vector or high-res image found.

Sprycloud is my Nextcloud provider of choice, I would love to see the logo in Aegis.

**Comment by krisu5** [comment]
I rather make icon for "Spry Servers" then for just the "spryCloud".

There already is NextCloud icon for aegis-icons, if you want that specifically.

**Comment by paulusversluis** [comment]
An icon for Spry Servers would be great.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Spry%20Servers.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
