### ISSUE TITLE
Icon request: Railway

### ISSUE THREAD

**Issue by ghost** [krisu5/aegis-icons#393]
- URL of the site or app **(required):** https://railway.app/
- Logo resources for the icon **(optional, but recommended):** https://github.com/railwayapp/docs/blob/main/public/railway.svg, https://github.com/railwayapp/docs/blob/main/public/android-chrome-512x512.png

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Railway.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Railway%20bg.var.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
