### ISSUE TITLE
Icon request: Hostinger

### ISSUE THREAD

**Issue by marcusbillman** [krisu5/aegis-icons#394]
- URL of the site or app **(required):** https://www.hostinger.com/
- Logo resources for the icon **(optional, but recommended):** https://assets.hostinger.com/images/logo-homepage2020-f9c79137d7.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Hostinger.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
