### ISSUE TITLE
Icon request: GoodSync

### ISSUE THREAD

**Issue by marcusbillman** [krisu5/aegis-icons#395]
- URL of the site or app **(required):** https://www.goodsync.com/
- Logo resources for the icon **(optional, but recommended):** https://www.goodsync.com/gsp/img/gs_logo_black.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/GoodSync.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
