### ISSUE TITLE
Icon request: Bookstack

### ISSUE THREAD

**Issue by ghost** [krisu5/aegis-icons#402]
- URL of the site or app **(required):** https://www.bookstackapp.com/
- Logo resources for the icon **(optional, but recommended):** https://avatars.githubusercontent.com/u/20912696?s=200&v=4

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Bookstack.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
