### ISSUE TITLE
Icon request: Focusrite

### ISSUE THREAD

**Issue by drinkcoffee247** [krisu5/aegis-icons#408]
Focusrite

- URL of the site or app **(required):** https://focusrite.com/en
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Focusrite.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Focusrite%20bg.var.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
