### ISSUE TITLE
Icon request: OMG.LOL

### ISSUE THREAD

**Issue by drinkcoffee247** [krisu5/aegis-icons#414]
OMG.LOL

- URL of the site or app **(required):** https://omg.lol/
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/OMG.LOL.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
