### ISSUE TITLE
Icon request: Gate.io

### ISSUE THREAD

**Issue by ghost** [krisu5/aegis-icons#420]
- URL of the site or app **(required):** https://gate.io
- Logo resources for the icon **(optional, but recommended):** https://www.gate.io/en/page/active/mediakit (Bottom)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Gate.io.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
