### ISSUE TITLE
Icon request: Tixte

### ISSUE THREAD

**Issue by jakiisheep** [krisu5/aegis-icons#421]
- URL of the site or app **(required):** https://tixte.com
- Logo resources for the icon **(optional, but recommended):** https://tixte.com/static/media/logo_mark.d3b45ae2.png https://tixte.com/static/media/logo_text.b35b078c.png https://cdn.discordapp.com/icons/818940877262553141/a_95dd063d9f15494c4a4690e58fdd10da.png?size=4096 https://cdn.discordapp.com/icons/818940877262553141/a_95dd063d9f15494c4a4690e58fdd10da.gif?size=4096

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Tixte.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

**Comment by jakiisheep** [comment]
Thank you!
