### ISSUE TITLE
Icon request: Blur

### ISSUE THREAD

**Issue by drinkcoffee247** [krisu5/aegis-icons#422]
- URL of the site or app **(required):** https://dnt.abine.com/#register
- Logo resources for the icon **(optional, but recommended):** https://abine.com/press/

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Blur.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
