### ISSUE TITLE
Icon request: Hexonet

### ISSUE THREAD

**Issue by moist-lump-of-carbon** [krisu5/aegis-icons#423]
- URL of the site or app **(required):** https://www.hexonet.net/
- Logo resources for the icon **(optional, but recommended):** https://www.hexonet.net/assets/pdf/HEXONET_brand_guidelines.pdf

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/HEXONET.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
