### ISSUE TITLE
Icon request: Playasia

### ISSUE THREAD

**Issue by Tofuraven** [krisu5/aegis-icons#424]
- URL of the site or app **(required):** https://www.play-asia.com/
- Logo resources for the icon **(optional, but recommended):** https://s.pacn.ws/shop/l4.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Playasia.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
