### ISSUE TITLE
Icon submission: Samtrade FX (updated logo)

### ISSUE THREAD

**Issue by gnulab-id** [krisu5/aegis-icons#425]
- [ X ] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required, unless it's generic icon):** 
- https://www.samtradefx.com/
- Where did you took the BG color(s) **(required, unless it's generic icon):** 
- https://www.samtradefx.com/

the website recently change their logo

Uploaded files:
[SAM Trade.zip](https://github.com/aegis-icons/aegis-icons/files/7501857/SAM.Trade.zip)

**Comment by krisu5** [comment]
Updated.
