### ISSUE TITLE
Icon request: Arch Linux

### ISSUE THREAD

**Issue by tiziodcaio** [krisu5/aegis-icons#426]
- URL of the site or app https://archlinux.org
- Logo resources for the icon https://archlinux.org/art/

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Arch%20Linux.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
