### ISSUE TITLE
Icon request: registro.br

### ISSUE THREAD

**Issue by lbschenkel** [krisu5/aegis-icons#427]
- URL of the site or app **(required):** https://registro.br/
- Logo resources for the icon **(optional, but recommended):** https://commons.wikimedia.org/wiki/File:DotBr_logo.svg

This is the `.br` registry, it supports 2FA for authentication.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Registro.br.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
