### ISSUE TITLE
Icon request: Exrates

### ISSUE THREAD

**Issue by XoloitzcuintiI** [krisu5/aegis-icons#428]
- URL of the site or app : https://exrates.me/
- Logo resources for the icon: https://exrates.me/media/logo.png

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Exrates.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
