### ISSUE TITLE
Icon request: Sentry

### ISSUE THREAD

**Issue by mishnea** [krisu5/aegis-icons#429]
- URL of the site: https://sentry.io/
- Logo resources for the icon: https://sentry.io/branding/

Would be nice to have both light and dark versions

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Sentry.svg

> Would be nice to have both light and dark versions

Sorry, [we don't do variations by request](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#can-you-make-variation-for-x-icon).

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
