### ISSUE TITLE
Icon submission: Deutsche Bahn

### ISSUE THREAD

**Issue by devmrcl** [krisu5/aegis-icons#430]
- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required, unless it's generic icon):** https://www.bahn.de/
- Where did you took the BG color(s) **(required, unless it's generic icon):** 
https://marketingportal.extranet.deutschebahn.com/en/colours#:~:text=Colour%20specifications
https://marketingportal.extranet.deutschebahn.com/themes/custom/ebm-db/public/images/logo.svg

Uploaded files:
[Deutsche Bahn.zip](https://github.com/aegis-icons/aegis-icons/files/7537205/Deutsche.Bahn.zip)

**Comment by krisu5** [comment]
Added to repo with slightly smaller logo 👍
