### ISSUE TITLE
Icon request: Hosting.de

### ISSUE THREAD

**Issue by barbiehunter** [krisu5/aegis-icons#431]
- 

- I have read the document

- URL of the site or app **(required):** 
https://www.hosting.de/

- Website Logo/ICON: https://pbs.twimg.com/profile_images/996377584731607040/XnYKvV7X_400x400.jpg

- Pictures as file (Second picture too):
[Hosting.de.zip](https://github.com/aegis-icons/aegis-icons/files/7547710/Hosting.de.zip)

Its a Nextcloud Hosting Partner, so would be nice to have it as icon.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/hosting.de.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
