### ISSUE TITLE
Icon request: PebbleHost

### ISSUE THREAD

**Issue by Trip7274** [krisu5/aegis-icons#432]
- URL of the site or app **(required):** PebbleHost
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Name of site is not enough, URL is **required** (this is enforced even if it's easily searchable, because otherwise future requesters possibly break this rule too).

Otherwise I will close this in about a week.

**Comment by Trip7274** [comment]
oh sorry im blind, heres the URL:
https://pebblehost.com/

**Comment by krisu5** [comment]
> oh sorry im blind, heres the URL: https://pebblehost.com/

Thank you, here's your icon:

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/PebbleHost.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
