### ISSUE TITLE
Icon request: PeeringDB

### ISSUE THREAD

**Issue by Emma0Z** [krisu5/aegis-icons#433]
Hello team!
I'm already using it into Aegis app ;)

- URL of the site or app **(required):** https://peeringdb.com/
- Logo resources for the icon **(optional, but recommended):**  https://github.com/peeringdb/peeringdb/blob/master/peeringdb_server/static/pdb-logo-square-coloured.png
or more : https://github.com/peeringdb/peeringdb/tree/master/peeringdb_server/static

Thank you very much :D

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/PeeringDB.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
