### ISSUE TITLE
Icon request: HMBradley

### ISSUE THREAD

**Issue by drinkcoffee247** [krisu5/aegis-icons#434]
- URL of the site or app **(required):** https://www.hmbradley.com
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/HMBradley.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/HMBradley%20bg.var.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
