### ISSUE TITLE
Icon request: Formspree

### ISSUE THREAD

**Issue by amypot** [krisu5/aegis-icons#435]
- URL of the site or app **(required):** https://formspree.io
- Logo resources for the icon **(optional, but recommended):** 
  - https://formspree.io/static/img/logo-mark.svg
  - https://formspree.io/static/img/formspree-new.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Formspree.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
