### ISSUE TITLE
Icon request: Digitec Galaxus

### ISSUE THREAD

**Issue by Schwitzd** [krisu5/aegis-icons#436]
The company name is Digitec Galaxus, they own both websites.
login to access both is the same.

- URL of the site or app **(required):** https://www.digitec.ch/ , https://www.galaxus.ch/
- Logo resources for the icon **(optional, but recommended):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Digitec%20Galaxus.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
