### ISSUE TITLE
Icon request: NAVER

### ISSUE THREAD

**Issue by BraINstinct0** [krisu5/aegis-icons#439]
- URL of the site or app **(required):** https://www.naver.com/
- Logo resources for the icon **(optional, but recommended):** main icon: [PNG logo](https://m-logoproject.naver.com/img/logo_symbol.png)
- Additional resources to see for logo: https://m-logoproject.naver.com/logonaver

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/NAVER.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

*P.S. Next time, please do not copypaste issue template to "blank issue". Use the issue template as is, copypasting removes automatic labels.*
