### ISSUE TITLE
Icon request: OpenVK

### ISSUE THREAD

**Issue by maksalees** [krisu5/aegis-icons#440]
- URL of the site or app **(required):**  https://openvk.su
- Logo resources for the icon **(optional):** https://github.com/openvk/openvk/blob/master/Web/static/img/logo.svg (background color: #13599f)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/OpenVK.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
