### ISSUE TITLE
Icon request: Dynadot

### ISSUE THREAD

**Issue by 74k1n984ckmyp21v4cy** [krisu5/aegis-icons#441]
- URL of the site or app **(required):** https://www.dynadot.com/
- Logo resources for the icon **(optional):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Dynadot.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
