### ISSUE TITLE
Icon request: KDE

### ISSUE THREAD

**Issue by maksalees** [krisu5/aegis-icons#442]
- URL of the site or app **(required):** https://kde.org
- Logo resources for the icon **(optional):** https://kde.org/stuff/clipart/logo/kde-logo-white-blue-source.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/KDE.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
