### ISSUE TITLE
Icon request: OPNsense

### ISSUE THREAD

**Issue by 74k1n984ckmyp21v4cy** [krisu5/aegis-icons#444]
- URL of the site or app **(required):** https://opnsense.org/
- Logo resources for the icon **(optional):**

**Comment by krisu5** [comment]
Logo SVG: https://commons.wikimedia.org/wiki/File:Opnsense-logo.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/OPNsense.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
