### ISSUE TITLE
Icon request: MathWorks/MATLAB

### ISSUE THREAD

**Issue by ricted98** [krisu5/aegis-icons#445]
- URL of the site or app (required): https://mathworks.com

- Logo resources for the icon (optional): https://icons.iconarchive.com/icons/blackvariant/button-ui-requests-6/512/MATLAB-icon.png (can't find a good SVG, sorry!

**Comment by krisu5** [comment]
SVGs: 
- https://www.mathworks.com/etc.clientlibs/mathworks/clientlibs/customer-ui/templates/common/resources/images/pic-header-mathworks-logo.20211109001259418.svg
- [MathWorks monochrome logomark](https://github.com/aegis-icons/aegis-icons/files/7663943/MathWorks.zip)

---

Please use **Icon request (app / site)** issue template next time, it's not necessary to copypaste from another issue.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/MathWorks.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
