### ISSUE TITLE
Icon request: E*TRADE (E-Trade)

### ISSUE THREAD

**Issue by mmlb** [krisu5/aegis-icons#446]
- URL of the site or app **(required):** [ETrade](https://us.etrade.com/home)
- Logo resources for the icon **(optional):** I'd go with the intersecting arrows of https://commons.wikimedia.org/wiki/File:ETrade.svg

Happy to do the work of cutting the arrows from the link I posted and submitting it if deemed acceptable.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/E-Trade.svg

> Happy to do the work of cutting the arrows from the link I posted and submitting it if deemed acceptable.

Thanks for offer, but it wasn't necessary. The cut job was pretty easy.

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

**Comment by mmlb** [comment]
Thanks!
