### ISSUE TITLE
Icon request: united-domains

### ISSUE THREAD

**Issue by Phiwatec** [krisu5/aegis-icons#447]
- URL of the site or app **(required):**  www.united-domains.de
- Logo resources for the icon **(optional):** de.wikipedia.org/wiki/Datei:United-Domains-Logo-Vector.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/united-domains.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
