### ISSUE TITLE
Icon request: Kryll.io

### ISSUE THREAD

**Issue by Jrmewam** [krisu5/aegis-icons#450]
- URL of the site or app **(required):** 
https://kryll.io/

Thanks!

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Kryll.io.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
