### ISSUE TITLE
Icon request: Coda

### ISSUE THREAD

**Issue by drinkcoffee247** [krisu5/aegis-icons#451]
- URL of the site or app **(required):** https://coda.io
- Logo resources for the icon **(optional):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Coda.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
