### ISSUE TITLE
Icon request: Control D

### ISSUE THREAD

**Issue by gravitychickenwings** [krisu5/aegis-icons#452]
- URL of the site or app **(required):** https://controld.com

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/ControlD.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/ControlD%20fg.var.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
