### ISSUE TITLE
Icon request: QNAP

### ISSUE THREAD

**Issue by 74k1n984ckmyp21v4cy** [krisu5/aegis-icons#453]
- URL of the site or app **(required):** https://www.qnap.com/
- Logo resources for the icon **(optional):** https://marketing.qnap.com/resource-category/logo/ (whatever suits Aegis best)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/QNAP.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
