### ISSUE TITLE
Icon request: Hive OS

### ISSUE THREAD

**Issue by Na0mir** [krisu5/aegis-icons#454]
Hello guys,

I that possible to work a new icon request for Hive OS (crypto mining plateform)? Thanks! ~

- URL of the site or app **(required):** https://hiveos.farm
- Logo resources for the icon **(optional):** Looks like there is a good quality PNG here : https://user-images.githubusercontent.com/71948970/121897564-6a3a9500-cd1a-11eb-9bd0-bd217eb8b88d.png I let you judge

N0amir

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Hive%20OS.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

**Comment by Na0mir** [comment]
Thanks! 
Was not possible to use the official icon with grey back and red/orange/yellow colors?

**Comment by krisu5** [comment]
> Thanks! Was not possible to use the official icon with grey back and red/orange/yellow colors?

Logo is from the website you provided as URL and the logo there was SVG vector. BG color is also from the said logo.

It is as official as it gets.

I always rather use SVGs then JPG/PNG images that I have convert to vector (specially when it's small image like this one...)
