### ISSUE TITLE
Icon Request: Runescape

### ISSUE THREAD

**Issue by Observing9616** [krisu5/aegis-icons#455]
I'd like to request an icon for the RPG game called Runescape.

URL for website: https://play.runescape.com/

URL for logo design: https://duckduckgo.com/?q=runescape+logo&t=fpas&iax=images&ia=images&iai=https%3A%2F%2Flogos-world.net%2Fwp-content%2Fuploads%2F2021%2F02%2FRuneScape-Symbol.png

**Comment by krisu5** [comment]
Duplicate, see #359 (use issue templates, not blank issue)
