### ISSUE TITLE
Icon request: Indodax

### ISSUE THREAD

**Issue by eyurando** [krisu5/aegis-icons#456]
- URL of the site or app **(required):** https://indodax.com/
- Logo resources for the icon **(optional):** https://id.wikipedia.org/wiki/Berkas:Indodax_Logo-Blue.png

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Indodax.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
