### ISSUE TITLE
Icon request: dmarcian

### ISSUE THREAD

**Issue by nichu42** [krisu5/aegis-icons#457]
- URL of the site or app **(required):** https://dmarcian.com/
- Logo resources for the icon **(optional):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/dmarcian.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
