### ISSUE TITLE
Icon request: TETR.IO

### ISSUE THREAD

**Issue by puerkito66** [krisu5/aegis-icons#458]
- URL of the site or app **(required):** https://tetr.io 
- Logo resources for the icon **(optional):** https://branding.osk.sh/

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/TETR.IO.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/TETR.IO%20bg.var.svg

❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*
