### ISSUE TITLE
Icon request: Homey

### ISSUE THREAD

**Issue by Alex25820** [krisu5/aegis-icons#459]
- URL of the site or app **(required):** https://homey.app
- Logo resources for the icon **(optional):** https://drive.google.com/drive/folders/1XyF1reFM18SCsZpls3cOjnhCH7sK97Iz _(official press kit)_

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Homey.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

🙏 *Support this project by giving a star! Just adding like to this comment is also appreciated.*
