### ISSUE TITLE
Icon request: Acorns

### ISSUE THREAD

**Issue by drinkcoffee247** [krisu5/aegis-icons#460]
- URL of the site or app **(required):** https://www.acorns.com/
- Logo resources for the icon **(optional):** https://www.acorns.com/press/

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Acorns.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
