### ISSUE TITLE
Icon request: postale.io

### ISSUE THREAD

**Issue by eyurando** [krisu5/aegis-icons#462]
- URL of the site or app **(required):** https://postale.io/
- Logo resources for the icon **(optional):** https://postale.io/build/images/logo.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/postale.io.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

🙏 *Support this project by giving a star! Just adding like to this comment is also appreciated.*
