### ISSUE TITLE
Icon request: Saweria

### ISSUE THREAD

**Issue by eyurando** [krisu5/aegis-icons#463]
- URL of the site or app **(required):** https://saweria.co/
- Logo resources for the icon **(optional):**
https://saweria.co/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fcapy_happy.603c7293.svg&w=384&q=75 (minus the speech bubble with heart)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Saweria.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

🙏 *Support this project by giving a star! Just adding like to this comment is also appreciated.*
