### ISSUE TITLE
Icon request: TorrentBD

### ISSUE THREAD

**Issue by Vucko130** [krisu5/aegis-icons#464]
- URL of the site or app **(required):** https://www.torrentbd.net
- Logo resources for the icon **(optional):** https://www.torrentbd.net/themes/material/static/favicon/apple-touch-icon.png

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/TorrentBD.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
