### ISSUE TITLE
Icon request: Shakepay

### ISSUE THREAD

**Issue by iwismer** [krisu5/aegis-icons#465]
- URL of the site or app **(required):** https://shakepay.com/
- Logo resources for the icon **(optional):** https://blog.shakepay.com/content/images/size/w2000/2020/10/Group-12--1-.jpg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Shakepay.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
