### ISSUE TITLE
Icon request: LunaNode

### ISSUE THREAD

**Issue by iwismer** [krisu5/aegis-icons#466]
- URL of the site or app **(required):** https://www.lunanode.com/
- Logo resources for the icon **(optional):** https://www.lunanode.com/images/logo-big.png

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/LunaNode.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
