### ISSUE TITLE
Icon request: Kerberos.io

### ISSUE THREAD

**Issue by Robby9705** [krisu5/aegis-icons#467]
- URL of the site or app **(required):** https://kerberos.io/
- Logo resources for the icon **(optional):** https://doc.kerberos.io/images/kerberos-logo.svg

**Comment by krisu5** [comment]
This one was tricky, took under 2 hours to figure out and make.

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Kerberos.io.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
