### ISSUE TITLE
Icon request: Lnk.Bio

### ISSUE THREAD

**Issue by Leilukin** [krisu5/aegis-icons#468]
- URL of the site or app **(required):** https://lnk.bio/
- Logo resources for the icon **(optional):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Lnk.Bio.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
