### ISSUE TITLE
Icon request: Zipmex

### ISSUE THREAD

**Issue by Hope-UwU** [krisu5/aegis-icons#469]
- URL of the site or app **(required):** https://zipmex.com/
- Logo resources for the icon **(optional):**

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Zipmex.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Zipmex%20bg.var.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
