### ISSUE TITLE
Icon request: OKEx

### ISSUE THREAD

**Issue by Hope-UwU** [krisu5/aegis-icons#470]
- URL of the site or app **(required):** https://www.okex.com/
- Logo resources for the icon **(optional):**  https://seeklogo.com/vector-logo/373746/okex / https://worldvectorlogo.com/logo/okex-2

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/OKEx.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
