### ISSUE TITLE
Icon request: Bitkub

### ISSUE THREAD

**Issue by Hope-UwU** [krisu5/aegis-icons#471]
- URL of the site or app **(required):** https://www.bitkub.com/
- Logo resources for the icon **(optional):**  https://worldvectorlogo.com/logo/bitkub

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Bitkub.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
