### ISSUE TITLE
Icon request: Coins.co.th

### ISSUE THREAD

**Issue by Hope-UwU** [krisu5/aegis-icons#472]
- URL of the site or app **(required):** https://coins.co.th/
- Logo resources for the icon **(optional):**  -

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Coins.co.th.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
