### ISSUE TITLE
Icon request: AdvCash

### ISSUE THREAD

**Issue by Hope-UwU** [krisu5/aegis-icons#473]
- URL of the site or app **(required):** https://advcash.com/
- Logo resources for the icon **(optional):**  https://seeklogo.com/vector-logo/404183/advcash / https://worldvectorlogo.com/logo/advcash

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Advcash.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
