### ISSUE TITLE
Icon request: Bitcoin.com

### ISSUE THREAD

**Issue by Hope-UwU** [krisu5/aegis-icons#474]
- URL of the site or app **(required):** https://www.bitcoin.com/
- Logo resources for the icon **(optional):**  https://brandfetch.com/bitcoin.com, https://www.bitcoin.com/icons/icon-512x512.png

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Bitcoin.com.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
