### ISSUE TITLE
Icon request: Upbit

### ISSUE THREAD

**Issue by Hope-UwU** [krisu5/aegis-icons#475]
- URL of the site or app **(required):** https://sg.upbit.com/home
- Logo resources for the icon **(optional):** https://cdn.upbit.com/images/logo_upbit.19e2e01.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Upbit.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
