### ISSUE TITLE
Icon request: BitMart

### ISSUE THREAD

**Issue by Hope-UwU** [krisu5/aegis-icons#476]
- URL of the site or app **(required):** https://www.bitmart.com/
- Logo resources for the icon **(optional):** https://www.bitmart.com/_nuxt/img/logo4.fcb2042.svg, https://www.bitmart.com/about/en

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/BitMart.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
