### ISSUE TITLE
Icon request: Caixa

### ISSUE THREAD

**Issue by Johnascimento-zz** [krisu5/aegis-icons#478]
URL of the site or app (required): https://www.caixa.gov.br
Logo resources for the icon (optional): https://seeklogo.com/vector-logo/24768/caixa-economica-federal (double-check logo color)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Caixa.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
