### ISSUE TITLE
Icon request: Hodlnaut

### ISSUE THREAD

**Issue by ciotorcristian** [krisu5/aegis-icons#479]
- URL of the site or app **(required):** https://www.hodlnaut.com/
- Logo resources for the icon **(optional):** https://res.cloudinary.com/crunchbase-production/image/upload/c_lpad,f_auto,q_auto:eco,dpr_1/eoirswwxluaw1fk8fx6u

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Hodlnaut.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
