### ISSUE TITLE
Icon request: Kiva

### ISSUE THREAD

**Issue by nichu42** [krisu5/aegis-icons#480]
- URL of the site or app **(required):** https://www.kiva.org/
- Logo resources for the icon **(optional):** https://www.kiva.org/about/press-center

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Kiva.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
