### ISSUE TITLE
Icon request: Cake DeFi

### ISSUE THREAD

**Issue by ciotorcristian** [krisu5/aegis-icons#481]
- URL of the site or app **(required):** https://cakedefi.com/
- Logo resources for the icon **(optional):** https://cakedefi.com/media-downloads/

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Cake%20DeFi.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
