### ISSUE TITLE
Icon submission: Toontown Rewritten (logo fix)

### ISSUE THREAD

**Issue by jessiehildebrandt** [krisu5/aegis-icons#482]
The existing icon for Toontown Rewritten can be difficult to read on smaller screens due to the fine linework in the logomark.
This version of the icon uses a solid version of the logomark that is easier to read at small sizes.

- [x] I have read and followed CONTRIBUTING document.
- URL of the site or app **(required, unless it's generic icon):** https://www.toontownrewritten.com/
- Where did you took the BG color(s) **(required, unless it's generic icon):** https://www.toontownrewritten.com/

Uploaded files:
[Toontown Rewritten alt.zip](https://github.com/aegis-icons/aegis-icons/files/7857564/Toontown.Rewritten.alt.zip)

**Comment by krisu5** [comment]
That does looks nicer and more like how it should look IMO.

Not adding this as `alt`, instead I will replace previous one with this icon.

Thanks for contributing. 👍
