### ISSUE TITLE
Icon request: Shopee

### ISSUE THREAD

**Issue by 3xploiton3** [krisu5/aegis-icons#484]
- URL of the site or app **(required):** https://shopee.co.id/
- Logo resources for the icon **(optional):** https://upload.wikimedia.org/wikipedia/commons/f/fe/Shopee.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Shopee.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
