### ISSUE TITLE
Icon request: Sony

### ISSUE THREAD

**Issue by rkhmlvch** [krisu5/aegis-icons#485]
- URL of the site or app **(required):** https://www.sony.com/
- Logo resources for the icon **(optional):** https://upload.wikimedia.org/wikipedia/commons/c/ca/Sony_logo.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Sony.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Sony%20bg.var.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
