### ISSUE TITLE
Icon request: Russian Post

### ISSUE THREAD

**Issue by rkhmlvch** [krisu5/aegis-icons#486]
- URL of the site or app **(required):** https://www.pochta.ru/en/
- Logo resources for the icon **(optional):** https://upload.wikimedia.org/wikipedia/commons/9/99/Russian_Post.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Russian%20Post.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
