### ISSUE TITLE
Icon request: TP-Link

### ISSUE THREAD

**Issue by 74k1n984ckmyp21v4cy** [krisu5/aegis-icons#488]
### URL of the site or app

https://www.tp-link.com

### Logo resources for the icon

_Removed by maintainer_

**Comment by krisu5** [comment]
Changed from Omada to TP-Link, because product use TP-Link ID to login.

Few other things:
- Please remember to add name to the title
- We don't accept JPG / PNG / GIF files anymore as logo resource.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/TP-Link.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
