### ISSUE TITLE
Icon request: Kaspersky

### ISSUE THREAD

**Issue by XoloitzcuintiI** [krisu5/aegis-icons#489]
### URL of the site or app

https://www.kaspersky.com

### Logo resources for the icon

https://upload.wikimedia.org/wikipedia/de/5/56/Kaspersky_anti_virus_logo.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Kaspersky.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
