### ISSUE TITLE
Icon request: Eneba

### ISSUE THREAD

**Issue by XoloitzcuintiI** [krisu5/aegis-icons#490]
### URL of the site or app

https://www.eneba.com/

### Logo resources for the icon

https://cdn.eneba.com/branding/v2/logoFull.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Eneba.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
