### ISSUE TITLE
Icon request: ecloud (/e/ cloud)

### ISSUE THREAD

**Issue by ghost** [krisu5/aegis-icons#491]
### URL of the site or app

https://e.foundation/ecloud/ & https://ecloud.global/

### Logo resources for the icon

https://doc.e.foundation/images/e_logo.svg

### Anything else?

Links which may help:
https://e.foundation/
https://simpleicons.org/icons/e.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/ecloud.svg


❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
