### ISSUE TITLE
Icon request: XSplit

### ISSUE THREAD

**Issue by mdvhimself** [krisu5/aegis-icons#493]
### URL of the site or app

https://www.xsplit.com/

### Logo resources for the icon

https://www.xsplit.com/presskit

### Anything else?

XSplit has its new design with an actual "splitted X" logo. Their main software is the broadcaster, which is pretty much is a payed version of obs. Site and the program uses 2fa. Thanks in advance!

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/XSplit.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
