### ISSUE TITLE
Icon request: Yandex

### ISSUE THREAD

**Issue by kri164** [krisu5/aegis-icons#494]
### URL for the brand / site / app

https://yandex.com/

### Logo resources for the icon

https://yandex.com/company/general_info/logotype_rules

### Proof of the Aegis-compatible 2FA

Support added with this PR: https://github.com/beemdevelopment/Aegis/pull/869
Released app version with Yandex.Key OTP support: https://github.com/beemdevelopment/Aegis/releases/tag/v2.1-beta1

### Anything else?

- Latin logo (with `Yandex` text) as primary icon
- Russian Cyrillic logo (with `Яндекс` text) as alternative icon.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Aegis doesn't support Yandex's 2fa system *yet*.

Until https://github.com/beemdevelopment/Aegis/pull/869 is merged with Aegis and app version released with the feature, we will not make icon for it **yet** for sake of avoiding to confuse users.

It's on [our todo list](https://github.com/aegis-icons/aegis-icons/projects/1#card-76021224) though. We keep eye on it and notify via this issue if icon is done.

**Comment by krisu5** [comment]
[Latest beta versions of Aegis](https://github.com/beemdevelopment/Aegis/releases) support Yandex.Key 2FA, so finally we can make icons for it.

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Yandex.svg
https://github.com/aegis-icons/aegis-icons/blob/master/icons/2_Variations/Yandex%20alt.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
