### ISSUE TITLE
Icon request: ID.me

### ISSUE THREAD

**Issue by Syzygos** [krisu5/aegis-icons#495]
### URL of the site or app

https://www.id.me/

### Logo resources for the icon

https://developers.id.me/brand-assets

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/ID.me.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
