### ISSUE TITLE
Icon request: Cheaper Domains

### ISSUE THREAD

**Issue by Cautious-Software701** [krisu5/aegis-icons#496]
### URL of the site or app

https://www.cheaperdomains.com.au/

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Cheaper%20Domains.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
