### ISSUE TITLE
Icon submission: simple-shortener

### ISSUE THREAD

**Issue by jessiehildebrandt** [krisu5/aegis-icons#498]
### Icon type

New icon

### URL of the site or app

https://gitlab.com/jessieh/simple-shortener/

### Logo / icon info

Created SVG version of logo from https://gitlab.com/jessieh/simple-shortener/-/raw/assets/icon.png by matching the font and dimensions used

### Background color info

Background color is from the dark color of the logo (#363636), alternative background color is from the project's primary UI accent color (#485fc7).

Screenshot of UI w/ accent color:
![image](https://user-images.githubusercontent.com/40772633/151732958-aa631e8c-64eb-4219-9351-7c7fba178b34.png)

### Upload icon(s)

[simple-shortener.zip](https://github.com/aegis-icons/aegis-icons/files/7967703/simple-shortener.zip)

### Anything else?

This icon is not for a centralized site or service, but a self-host-able link shortening service that authenticates user sessions with TOTPs by default. I've not seen anything in the contribution guide about this sort of thing, so I'm only assuming that this might be appropriate.

Disclaimer: The service in question is a personal project. ;)

### Confirmation

- [X] I have read and followed [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md)

**Comment by krisu5** [comment]
I don't know about this one.

Icons are mostly okay (except for wrong order of `viewBox="0 0 1024 1024"` and `xmlns="http://www.w3.org/2000/svg"`, [see the example](https://github.com/aegis-icons/misc/commit/c0128f61f0d2b88d5953881699955a4a17477e47?diff=split)), but this software feels too unpopular (based of not having any non-maintainer activity on the repo) and – *even if it wasn't on purpose* – self-advertisement.

Selfhosted services are okay (see: Wordpress, Bookstack, Wallabag etc.), but IMO these should be at least somewhat popular.

And while aegis-icons has some *really* niche icons (eg. university related icons), these were requested by users. Unless they own the service they're requesting the icon for, there's not much of bias there and are okay to aegis-icons.

We also had one person who made icon for service that was also their creation, but that service had almost close to half a million users and Wikipedia article. So even if that's *technically* self-advertisement too, at least that service is popular enough to have some users for the icon.

I'm most likely adding some kind of "popularity guideline" for creating icons for selfhosted services, something like Simple Icons has: https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#requesting-an-icon

Of course, this would be case to case thing at the future still.

**Comment by jessiehildebrandt** [comment]
All totally fair considerations!

I made the icon for use on my phone and wasn't sure if it'd be an appropriate addition to this project; my only real contribution here may be prompting an update to the contributing guidelines (sorry!).

**Comment by krisu5** [comment]
Thank you for understanding. 😄

Related to this, I made ["icon acceptability criteria"](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#icon-acceptability-criteria) list. This was necessary sooner then later anyways.
