### ISSUE TITLE
Icon request: CoinStats

### ISSUE THREAD

**Issue by CodeShakingSheep** [krisu5/aegis-icons#500]
### URL of the site or app

https://coinstats.app/

### Logo resources for the icon

*Removed by maintainer (data URI)*

### Anything else?

Here is the press-kit page: https://coinstats.app/de/press-kit/

**Comment by krisu5** [comment]
Please just add link to press kit or direct link to vector if it has one on "Logo resources for the icon", not data uri URL (those are annoyingly long)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/CoinStats.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
