### ISSUE TITLE
Icon request: lexoffice

### ISSUE THREAD

**Issue by CodeShakingSheep** [krisu5/aegis-icons#501]
### URL of the site or app

https://www.lexoffice.de/

### Logo resources for the icon

https://www.lexoffice.de/presse/

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/lexoffice.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
