### ISSUE TITLE
Icon request: Render

### ISSUE THREAD

**Issue by mishnea** [krisu5/aegis-icons#503]
### URL of the site or app

https://render.com

### Logo resources for the icon

https://render.com/favicon.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Render.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
