### ISSUE TITLE
Icon request: RAIDBOXES

### ISSUE THREAD

**Issue by CodeShakingSheep** [krisu5/aegis-icons#504]
### URL of the site or app

https://raidboxes.io/

### Logo resources for the icon

https://b2r14pkp-69c6.kxcdn.com/wp-content/uploads/2021/10/raidboxes_landscape_logo_main.svg

### Anything else?

Thanks for adding my last 2 icon requests. Just found another one.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/RAIDBOXES.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
