### ISSUE TITLE
Icon request: Paddle

### ISSUE THREAD

**Issue by CodeShakingSheep** [krisu5/aegis-icons#505]
### URL of the site or app

https://paddle.com/

### Logo resources for the icon

https://drive.google.com/drive/u/0/folders/1piriZwb9uRDrVI4_8tEBCS_7NcW49n4u

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Paddle.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
