### ISSUE TITLE
Icon request: WPMU DEV

### ISSUE THREAD

**Issue by CodeShakingSheep** [krisu5/aegis-icons#506]
### URL of the site or app

https://wpmudev.com/

### Anything else?

SVG logo can be found on the main page.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/WPMU%20DEV.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
