### ISSUE TITLE
Icon request: Asana

### ISSUE THREAD

**Issue by CodeShakingSheep** [krisu5/aegis-icons#508]
### URL of the site or app

https://asana.com/

### Logo resources for the icon

https://www.dropbox.com/sh/66ux39jwxb1eztn/AABYvDZbRuiSJMnh59YUFQkva/Logos/RGB%20-%20Screen

**Comment by justsomemate** [comment]
I actually made one for this a while back, if it helps.
Their [brand guidelines](https://asana.com/brand) specify that the dots and name shouldn't be used independently, but they do allow for the name to go below the dots.

![Asana](https://user-images.githubusercontent.com/80608392/153691584-ba709086-377d-46e3-ac0b-8497967123db.svg)

**Comment by krisu5** [comment]
Yeah, I accept @justsomemate's icon.

Adding to the pack and credits.
