### ISSUE TITLE
Icon submission: Rocket.Chat

### ISSUE THREAD

**Issue by ghost** [krisu5/aegis-icons#509]
### Icon type

Generic icon

### URL of the site or app

https://rocket.chat/

### Logo / icon info

Image traced of https://play-lh.googleusercontent.com/wGn6UxVJUVWBOEAR_864Y_TG42iCsr8Ls3xmLoT4oOimSo6lk2_2gfBATqNDNmArKzQ=s360-rw

### Upload icon(s)

[rocket.chat.zip](https://github.com/aegis-icons/aegis-icons/files/8059530/rocket.chat.zip)

### Confirmation

- [X] I have read and followed [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md)

**Comment by krisu5** [comment]
Rejected.

1. We want SVG based icons. Icon on the ZIP is WebP raster image.
2. You shouldn't image trace the logo, when there's available SVG logo (on the website, top navigation). Image tracing can make imperfections to logo, specially for image that low resolution.
   - Also, even if image tracing was acceptable for this case, you should write what tool you used or did you do it manually by hand.
3. There's no background color info, for brand based icons it's required to fill that section.
4. Minor mistake but still, icon type is not "generic icon" in this case. It's "new icon" (but I will soon update it to more understandable "brand based icon").

**Comment by ghost** [comment]
Hi. Is there any problem with it? It’s perfectly fine on my device. It'll save us searching for it elsewhere if it's in your package. Thanks.

**Comment by krisu5** [comment]
> Hi. Is there any problem with it? It’s perfectly fine on my device. It'll save us searching for it elsewhere if it's in your package. Thanks.

[Read my comment](https://github.com/aegis-icons/aegis-icons/issues/509#issuecomment-1039011964). I'm not gonna repeat myself. And read [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) (again).
