### ISSUE TITLE
Icon request: Manjaro

### ISSUE THREAD

**Issue by Robby9705** [krisu5/aegis-icons#510]
### URL of the site or app

https://manjaro.org/

### Logo resources for the icon

https://gitlab.manjaro.org/artwork/icon-themes/manjaro-icons/-/blob/master/green/green.svg

### Anything else?

[Simple-icons](https://simpleicons.org/) also has one, if you want to use it as a [reference](https://github.com/simple-icons/simple-icons/blob/521c96fd04b0ea93034db8715eda5a4de27a58bb/icons/manjaro.svg) :D

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Manjaro.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
