### ISSUE TITLE
Update icon: raidboxes

### ISSUE THREAD

**Issue by CodeShakingSheep** [krisu5/aegis-icons#511]
### URL of the site or app

https://raidboxes.io/

### Reason for update

New logo

### Logo resources for the icon

https://images.raidboxes.io/raidboxes.io/uploads/2021/10/raidboxes-wordmark.svg

### Anything else?

Raidboxes created a new branding including a new logo. Bad timing as the issue for the previous raidboxes icon was just closed 4 days ago. Grateful for your work.

**Comment by krisu5** [comment]
Here you go! Thanks for the kind words.

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/raidboxes.svg


❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
