### ISSUE TITLE
Icon request: ONLYOFFICE

### ISSUE THREAD

**Issue by drinkcoffee247** [krisu5/aegis-icons#512]
### URL of the site or app

https://www.onlyoffice.com/

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/ONLYOFFICE.svg



❓ *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

⭐ *Support this project by giving a star! Just adding like to this comment is also appreciated.*
