### ISSUE TITLE
Icon submission: Hyper Expert

### ISSUE THREAD

**Issue by cfanoulis** [krisu5/aegis-icons#514]
### Icon type

Logo based

### URL of the site or app

https://hyperexpert.com

### Logo / icon info

Extracted SVG from the administration UI

### Background color info

Background color is taken from the branding accent color, shown when hovering the logo at https://hyperexpert.com
![Image showng the logo color](https://user-images.githubusercontent.com/38255093/154838242-afc933e7-014d-47a0-afd0-968a7694983f.png)

### Upload icon(s)

[Logo (.zip)](https://github.com/aegis-icons/aegis-icons/files/8140721/Hyper.Expert.zip)

### Confirmation

- [X] I have read and followed [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md)

**Comment by cfanoulis** [comment]
OK nope, the SVG submitted seems broken. Please hold as I make a new one

**Comment by cfanoulis** [comment]
I've submitted the correct version now, awaiting your responses

**Comment by krisu5** [comment]
1. Logo is way too big, stick to the inside of the (at least top / bottom) guides. I recommend `560 px` width (with constrained width and height, Illustrator gave it height as `464,867 px`)
2. [SVG's compression / cleanup is not good enough](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#svg-compression--cleanup), specially check the correct SVG format.

_Sidenote:_ even though Github now supports uploading SVGs to comments / markdown, its currently little bit buggy. 

Please ZIP the SVGs still instead. [I have reported this issue](https://github.com/github/feedback/discussions/11053).

**Comment by cfanoulis** [comment]
Hi, I've fixed the issues mentioned. I've attached the new svg zipfile to this comment & the original issue
[Hyper Expert.zip](https://github.com/aegis-icons/aegis-icons/files/8140721/Hyper.Expert.zip)

**Comment by krisu5** [comment]
Added to the repo.
