### ISSUE TITLE
Icon request: The Good Cloud

### ISSUE THREAD

**Issue by CodeShakingSheep** [krisu5/aegis-icons#515]
### URL of the site or app

https://thegood.cloud/

### Logo resources for the icon

https://thegood.cloud/assets/images/tgc-logo.svg

### Anything else?

I know that the good cloud uses nextcloud under the hood for which an icon already exists. Still, the good cloud is a single entity including its own company and branding. So, I think it would be consistent to maintain their logo.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/The%20Good%20Cloud.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/The%20Good%20Cloud%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
