### ISSUE TITLE
Icon request: Mollie

### ISSUE THREAD

**Issue by ph00lt0** [krisu5/aegis-icons#516]
### URL of the site or app

https://mollie.com

### Logo resources for the icon

https://www.mollie.com/en/resources

### Anything else?

Link to press kit with logos: https://assets.ctfassets.net/k4kk06v59kf0/5NIVCmD6wwpbD7yvhZPYNX/d22c1ec5997f242f3344ca316ffcac62/Mollie_Logos.zip

Link may change hence I listed https://www.mollie.com/en/resources

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Mollie.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Mollie%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
