### ISSUE TITLE
Icon request: Tecnoblog (forum)

### ISSUE THREAD

**Issue by Johnascimento-zz** [krisu5/aegis-icons#517]
### URL of the site or app

https://tecnoblog.net/

**Comment by krisu5** [comment]
Only place that use accounts was comment section and forum: https://comunidade.tecnoblog.net/

[Not popular enough for getting own icon](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#case-by-case-basis).

Both of those use **Discourse** forum software, search those icon(s).
