### ISSUE TITLE
Icon request: Ubuntu

### ISSUE THREAD

**Issue by ghost** [krisu5/aegis-icons#519]
### URL of the site or app

https://ubuntu.com/

### Logo resources for the icon

*Deleted by maintainer (raster image)*

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Ubuntu.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
