### ISSUE TITLE
Icon request: Tiny Tiny RSS

### ISSUE THREAD

**Issue by ghost** [krisu5/aegis-icons#520]
### URL of the site or app

https://tt-rss.org/

### Logo resources for the icon

*Deleted by maintainer (raster image)*

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Tiny%20Tiny%20RSS.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
