### ISSUE TITLE
Icon request: HP

### ISSUE THREAD

**Issue by theLittlePrinceAD** [krisu5/aegis-icons#522]
### URL of the site or app

https://www.hp.com

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/HP.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*

**Comment by theLittlePrinceAD** [comment]
Thank you very much for the fast response!I couldn’t open the SVG in Aegis, but never mind – I’ll wait for the official icon pack update release 😊BR and Good luck! Sent from Mail for Windows From: Kristian SalonenSent: 28 февруари 2022 г. 1:36To: aegis-icons/aegis-iconsCc: DIMOV, A.B.; AuthorSubject: Re: [aegis-icons/aegis-icons] Icon request: HP (Issue #522) Here you go!https://github.com/aegis-icons/aegis-icons/blob/master/SVG/HP.svg❓ How to add icon(s) to Aegis?⭐ Support this project by giving a star! Just adding like to this comment is also appreciated.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>
