### ISSUE TITLE
Icon submission: BitSight

### ISSUE THREAD

**Issue by Ailothaen** [krisu5/aegis-icons#524]
### Icon type

Logo based

### URL of the site or app

https://www.bitsight.com/

### Logo / icon info

Letter "B" taken from the embedded SVG logotype in the header

### Background color info

Background color is from the logo.

### Upload icon(s)

[Bitsight](https://user-images.githubusercontent.com/11133116/155898589-237b9386-6805-4246-aa1f-fa9d5f0099a6.svg)

### Confirmation

- [X] I have read and **carefully** followed [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md)

**Comment by krisu5** [comment]
Use full logo (minus the trademark and tagline under the logo), not one letter.

Also, I don't recommend uploading SVGs without zipping currently, [because it's currently buggy](https://github.com/github/feedback/discussions/11053).

**Comment by Ailothaen** [comment]
Here is the updated file: [BitSight.zip](https://github.com/aegis-icons/aegis-icons/files/8155284/BitSight.zip)

**Comment by krisu5** [comment]
Added to repo (with smaller sized logo).
