### ISSUE TITLE
Icon submission: CrowdStrike

### ISSUE THREAD

**Issue by Ailothaen** [krisu5/aegis-icons#525]
### Icon type

Logo based

### URL of the site or app

https://www.crowdstrike.com/

### Logo / icon info

Full logo, showed in the favicon for example

### Background color info

Background color is from the logo.

### Upload icon(s)

![Crowdstrike](https://user-images.githubusercontent.com/11133116/155898941-2622c269-2e0f-44b9-91fd-4a0a04ab09f0.svg)

### Anything else?

ATTENTION: I was not able to unify logo as a single path as explained in https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#vectors
Feel free to refuse submission if this is not acceptable as per criteria and this cannot be done after submission.

### Confirmation

- [X] I have read and **carefully** followed [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md)

**Comment by krisu5** [comment]
I try to make logo into compound path.

**Comment by krisu5** [comment]
Added to the repo.
