### ISSUE TITLE
Icon request: Red Hat

### ISSUE THREAD

**Issue by IzumiSenaSora** [krisu5/aegis-icons#526]
### URL of the site or app

https://www.redhat.com

### Logo resources for the icon

https://www.redhat.com/profiles/rh/themes/redhatdotcom/img/logo.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Red%20Hat.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
