### ISSUE TITLE
Icon request: Internxt

### ISSUE THREAD

**Issue by CodeShakingSheep** [krisu5/aegis-icons#527]
### URL of the site or app

https://internxt.com/

### Logo resources for the icon

https://internxt.com/logos/internxt/cool-gray-90.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Internxt.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Internxt%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
