### ISSUE TITLE
Icon request: GNOME (forum)

### ISSUE THREAD

**Issue by Robby9705** [krisu5/aegis-icons#529]
### URL of the site or app

https://www.gnome.org/

### Logo resources for the icon

https://foundation.gnome.org/logo-and-trademarks/

### Anything else?

There Forum Has An Authenticator based Two-Step Verification https://discourse.gnome.org/

PS. Simple Icons Also Has One, If You Wanna Use That As A Reference. https://github.com/simple-icons/simple-icons/blob/521c96fd04b0ea93034db8715eda5a4de27a58bb/icons/gnome.svg

**Comment by krisu5** [comment]
Rejected: [only really popular forums can get their own icon.](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#case-by-case-basis) GNOME Discourse only has [under 3000 members](https://discourse.gnome.org/u?order=likes_received).

Use one of the **Discourse** icons.
