### ISSUE TITLE
Icon request: fileee

### ISSUE THREAD

**Issue by nichu42** [krisu5/aegis-icons#530]
### URL of the site or app

https://www.fileee.com/

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/fileee.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
