### ISSUE TITLE
Icon request: CoinFLEX

### ISSUE THREAD

**Issue by authorturker** [krisu5/aegis-icons#531]
### URL of the site or app

https://coinflex.com/

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/CoinFLEX.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
