### ISSUE TITLE
Icon request: WAX (Worldwide Asset eXchange)

### ISSUE THREAD

**Issue by authorturker** [krisu5/aegis-icons#533]
### URL of the site or app

https://wax.io/

### Logo resources for the icon

https://legacy.wax.io/press

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/WAX.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
