### ISSUE TITLE
What happened Adobe icon?

### ISSUE THREAD

**Issue by authorturker** [krisu5/aegis-icons#534]
### Issue

Hi! I was using older version of aegis icons for couple months. In latest version, I couldn't see Adobe option anymore. I searched all git repo but couldn't find the answer. What happened to that?

**Comment by krisu5** [comment]
Removed from the pack, because it doesn't have [3rd party 2FA option](https://helpx.adobe.com/manage-account/using/secure-your-adobe-account.html)

Current available here: https://github.com/aegis-icons/misc/blob/main/removed_icons/Adobe.svg

**Comment by authorturker** [comment]
Interesting. I'm still using aegis as a 2FA service for Adobe. I should add it manually to the pack than. Thanks for reply.
