### ISSUE TITLE
Icon request: VFUN

### ISSUE THREAD

**Issue by eyurando** [krisu5/aegis-icons#535]
### URL of the site or app

https://vfun.valofe.com/

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/VFUN.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
