### ISSUE TITLE
Icon submission: International Information System Security Certification Consortium, or (ISC)²

### ISSUE THREAD

**Issue by CampinCarl** [krisu5/aegis-icons#537]
### Icon type

Logo based

### URL of the site or app

https://www.isc2.org/

### Logo / icon info

https://www.isc2.org/images/logos/logo-isc2-green.svg

### Background color info

[Official Chapter Branding Guidelines.pdf](https://www.isc2.org/-/media/7319E93A76D643C2BAEDAA204F08C0F3.ashx), page 5, primary color is `#006852`.

![Primary Color](https://user-images.githubusercontent.com/11837803/158616893-19686687-cda6-4083-93dc-7cdbafc3ffc9.png)

### Zipped Vector File
[(ISC)².zip](https://github.com/aegis-icons/aegis-icons/files/8263298/ISC.zip)

### PNG Sample
![Example](https://user-images.githubusercontent.com/11837803/158617405-c9b228e4-0dca-432c-a549-25b35e2cd00f.png)

### Confirmation

- [X] I have read and **carefully** followed [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md)

**Comment by krisu5** [comment]
Added to the repo.
