### ISSUE TITLE
Icon submission: Cloudinary

### ISSUE THREAD

**Issue by CampinCarl** [krisu5/aegis-icons#538]
### Icon type

Logo based

### URL of the site or app

https://cloudinary.com/

### Logo / icon info

https://cloudinary.com/assets

### Background color info

[Brand Assets | Cloudinary](https://cloudinary.com/assets) &mdash; "Cloudinary blue" is `#3448c5`

![CloudinaryColorPalette](https://user-images.githubusercontent.com/11837803/158723416-08ebd056-af33-4236-9c4b-36f13dbd16db.png)

### Upload icon(s)

![Cloudinary](https://user-images.githubusercontent.com/11837803/158723600-25c1f551-26d0-4190-8e20-0c598809cab8.png)
[Cloudinary.svg.zip](https://github.com/aegis-icons/aegis-icons/files/8280890/Cloudinary.svg.zip)

### Confirmation

- [X] I have read and **carefully** followed [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md)

**Comment by krisu5** [comment]
You need to be more careful when formatting the SVG, we want SVG markup formatting exactly like [in the example](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#svg-compression--cleanup). The `style="fill:` part in the logo was on the wrong position and there was also pointless `class` property (I made also updates to CONTRIBUTING doc again regarding these).

The logo also was visually off center, had to move it up by 24px.

I made the changes and added the icon to repo.

**Comment by CampinCarl** [comment]
Hi @krisu5, understood, thanks for the feedback.
