### ISSUE TITLE
Icon request: Pterodactyl

### ISSUE THREAD

**Issue by jensz12** [krisu5/aegis-icons#540]
### URL of the site or app

https://pterodactyl.io

### Logo resources for the icon

https://pterodactyl.io/logos/pterry.svg

### Anything else?

Would love a propper icon for the Pterodactyl Panel.
Its a gameserver panel, that anyone can host

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Pterodactyl.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
