### ISSUE TITLE
Icon request: cPanel

### ISSUE THREAD

**Issue by jensz12** [krisu5/aegis-icons#541]
### URL of the site or app

https://cpanel.net

### Logo resources for the icon

https://cpanel.net/company/cpanel-brand-guide/

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/cPanel.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
