### ISSUE TITLE
Icon request: Capital.com

### ISSUE THREAD

**Issue by just-dev-creator** [krisu5/aegis-icons#542]
### URL of the site or app

https://capital.com/

### Logo resources for the icon

https://svgshare.com/i/fQd.svg

### Anything else?

I think that the app logo should be used. It is available at brandfetch.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Capital.com.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
