### ISSUE TITLE
Icon request: Invoice Ninja

### ISSUE THREAD

**Issue by just-dev-creator** [krisu5/aegis-icons#548]
### URL of the site or app

https://www.invoiceninja.org/

### Logo resources for the icon

https://www.svgrepo.com/download/306245/invoiceninja.svg

**Comment by krisu5** [comment]
Alt. svg: https://github.com/simple-icons/simple-icons/blob/master/icons/invoiceninja.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Invoice%20Ninja.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Invoice%20Ninja%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
