### ISSUE TITLE
Icon request: SPID (Sistema Pubblico di Identità Digitale)

### ISSUE THREAD

**Issue by fiorins** [krisu5/aegis-icons#549]
### URL of the site or app

https://www.spid.gov.it/en/

### Anything else?

Hi, could you add the Spid icon to the package, please? It would be awesome

SVG: https://github.com/italia/spid-graphics/blob/master/spid-logos/spid-logo-c-lb.svg
EPS: https://github.com/italia/spid-graphics/blob/master/spid-logos/spid-logo-c-lb.eps

I send you an icon I use for now as reference with blue color background:
![Spid Italia](https://user-images.githubusercontent.com/32281481/159369185-2ce5e888-44d8-4f4f-835b-136b372621c9.png)

As color background you can use the blue #0066CC since it's the official color, cheers.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/SPID.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
