### ISSUE TITLE
Icon submission: Qualys

### ISSUE THREAD

**Issue by CampinCarl** [krisu5/aegis-icons#552]
### Icon type

Logo based

### URL of the site or app

https://www.qualys.com/

### Logo / icon info

https://www.qualys.com/mask-icon.svg

### Background color info

[Qualys-Logo-Guidelines.pdf](https://www.qualys.com/docs/qualys-logo-guidelines.pdf) (Page 7) — Primary color is `#ed2e26`

![QualysColors](https://user-images.githubusercontent.com/11837803/159612676-bde7078d-ef9c-42bc-8ef8-e17769fbb3bc.png)

### Upload icon(s)

Icon
:---:
![Qualys](https://user-images.githubusercontent.com/11837803/159613209-0e227c4a-8e6f-408c-b9eb-82e482425d2d.png)
[Qualys.zip](https://github.com/aegis-icons/aegis-icons/files/8329254/Qualys.zip)

### Anything else?

The path is aligned but the logo is a bit top-heavy. I'm happy to lower it a bit if the reviewer thinks it would be better that way.

Thanks for the useful repo!

### Confirmation

- [X] I have read and **carefully** followed [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md)

**Comment by krisu5** [comment]
Added to the repo 👍
