### ISSUE TITLE
Icon request: ZEBEDEE

### ISSUE THREAD

**Issue by authorturker** [krisu5/aegis-icons#554]
### URL of the site or app

https://zebedee.io/

### Logo resources for the icon

https://zebedee.io/press

**Comment by CampinCarl** [comment]
The press kit page has multiple versions of the logo, i.e., a "ZBD" and "ZEBEDEE" version. I figure the ZBD version is probably better for this application but I created icons for both just in case.

Hope this helps.

### Icons
ZEBEDEE Version|ZBD Version (Alternate)
:---:|:---:
![ZEBEDEE](https://user-images.githubusercontent.com/11837803/159721609-44b237e4-a3c1-4bbb-9716-9e920d900025.png)|![ZBD](https://user-images.githubusercontent.com/11837803/159721856-83c3ac1f-bdbb-4fd1-b48f-3013a9afeab9.png)
[ZEBEDEE.zip](https://github.com/aegis-icons/aegis-icons/files/8333805/ZEBEDEE.zip)|[ZBD.zip](https://github.com/aegis-icons/aegis-icons/files/8333809/ZBD.zip)

### Background Color
I used the purple color taken from the ZBD media kit, as purple seems to be the dominant color on the https://zebedee.io/ site. Specifically, `#916FF7`.

![ZBD Brand Colors Excerpt](https://user-images.githubusercontent.com/11837803/159722891-fb2e6d3e-c622-40c1-8b18-db192eccfc2b.png)

[ZBD-Media-Kit.zip](https://cdn.zebedee.io/media-kit/ZBD-Media-Kit.zip)

**Comment by authorturker** [comment]
Thanks! I'll use ZBD one. If somebody will add this to the repo, their common logo is ZBD

**Comment by krisu5** [comment]
Added ZBD logo icon to the repo, with smaller logo

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/ZEBEDEE.svg
