### ISSUE TITLE
Icon request: PipeFlare

### ISSUE THREAD

**Issue by authorturker** [krisu5/aegis-icons#555]
### URL of the site or app

https://pipeflare.io/

**Comment by CampinCarl** [comment]
I couldn't find a press kit, but I found an SVG logo with tagline here: [PF-logo-with-tagline-white.svg](https://statics.pipeflare.io/assets/logo/PF-logo-with-tagline-white.svg).

Hope this helps.

Icon
:---:
![PipeFlare](https://user-images.githubusercontent.com/11837803/159715040-e157e21e-4a83-4a6d-b3f6-82a27ffb69a7.png)
[PipeFlare.zip](https://github.com/aegis-icons/aegis-icons/files/8333530/PipeFlare.zip)

### Background Color
Background color is from the logo. Specifically, I used the darker end of the logo's gradient—Inkscape called it `stop6`—taken from the source SVG file, i.e., `#52009b`.

**Comment by authorturker** [comment]
Thank you so much!

**Comment by krisu5** [comment]
Added to the repo.
