### ISSUE TITLE
Icon submission: TheHive

### ISSUE THREAD

**Issue by Ailothaen** [krisu5/aegis-icons#556]
### Icon type

Logo based

### URL of the site or app

https://thehive-project.org/

### Logo / icon info

Grabbed logo and colors from the front page

### Background color info

Background color is from the logo.

I also provide a `fg.var` version because the color is yellow and the white icon could be hard to see

### Upload icon(s)

[TheHive.zip](https://github.com/aegis-icons/aegis-icons/files/8344975/TheHive.zip)

### Anything else?

I could not union the paths of the logo, because the color of some parts relies on the fill and others on the border, so union was making weird results.

### Confirmation

- [X] I have read and **carefully** followed [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md)

**Comment by krisu5** [comment]
> I could not union the paths of the logo, because the color of some parts relies on the fill and others on the border, so union was making weird results.

It's because the bee's antennas and line above it are **strokes**. You need to change those parts to **path** (path -> stroke to path).

Every object has to be path for successful compund path unioning.

TBH, fg.var version isn't necessary, I can see the logo fine on my monitor.

**Comment by Ailothaen** [comment]
Thank you for the tip, I was able to convert everything to path and union them correctly afterwards.

Here is the edited version (with only the standard version as fg.var was not necessary) :
[TheHive.zip](https://github.com/aegis-icons/aegis-icons/files/8353672/TheHive.zip)

**Comment by krisu5** [comment]
Added to the repo, with fg.var after all. I was wrong, it needed that after all.
