### ISSUE TITLE
Icon submission: ThreatQuotient

### ISSUE THREAD

**Issue by Ailothaen** [krisu5/aegis-icons#557]
### Icon type

Logo based

### URL of the site or app

https://www.threatq.com/

### Logo / icon info

Taken from: https://www.threatq.com/branding/ I used Vectorizer.io since only PNGs were provided.

### Background color info

Background color is from the logo.

### Upload icon(s)

[ThreatQuotient.zip](https://github.com/aegis-icons/aegis-icons/files/8345006/ThreatQuotient.zip)

### Confirmation

- [X] I have read and **carefully** followed [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md)

**Comment by krisu5** [comment]
Added to repo.
