### ISSUE TITLE
Icon request: Finary

### ISSUE THREAD

**Issue by ChxGuillaume** [krisu5/aegis-icons#559]
### URL of the site or app

https://finary.com/

### Anything else?

I tried finding a branding page or svg from them but none seems to be available :/

**Comment by ChxGuillaume** [comment]
Found some SVG logo online (see: [d23da9f9f97f1b84eb28da202d281a8fa26ebb84-120x120.svg](https://cdn.sanity.io/images/it6yt7cb/production/d23da9f9f97f1b84eb28da202d281a8fa26ebb84-120x120.svg?q=75&fit=max&auto=format))

So I made versions on Illustrator.

| White Version  | Black Version | White on Black | Black on White | W on Primary |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| ![finary-logo-white](https://user-images.githubusercontent.com/43764147/160089976-664e0902-01a4-4401-a4e4-3b0ae03082c7.svg) | ![finary-logo-black](https://user-images.githubusercontent.com/43764147/160089980-0b4bbfd4-5b6d-4101-9404-c3fa387cf006.svg) | ![finary-logo-black-white](https://user-images.githubusercontent.com/43764147/160090252-21a4bc77-898a-4797-96dd-ee33b9d88b5a.svg) | ![finary-logo-white-black](https://user-images.githubusercontent.com/43764147/160090254-56dceb50-987e-4ca1-8cea-c0d862c2bad6.svg) | ![finary-logo-primary](https://user-images.githubusercontent.com/43764147/160090257-c2496c6b-7ab0-4dda-918f-0e5365b0af29.svg) |

Here is a zip with everything [finary-logos.zip](https://github.com/aegis-icons/aegis-icons/files/8349026/finary-logo.zip)

## Background Color

Primary color `#F1C084` from the source svg.

# _THOSE ARE SUGGESTIONS_

**Comment by krisu5** [comment]
Based of submissions, I can assume you didn't read the CONTRIBUTING document, which is requirement for submission.

Submissions should be made with seperate issue using the correct form.

**Comment by ChxGuillaume** [comment]
I don't see what i did wrong but ok ^^

**Comment by krisu5** [comment]
Reopened since you mentioned that these are suggestions on the comment edit.

It wasn't clear before and I assumed that this was request turn into submission, sorry.

**Comment by ChxGuillaume** [comment]
Yea I'm sorry 😅 I'm not a designer myself, just wanted to give examples as I saw on other issues ><

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Finary.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
