### ISSUE TITLE
Icon request: Betfair

### ISSUE THREAD

**Issue by AKDub** [krisu5/aegis-icons#561]
### URL of the site or app

https://www.betfair.com

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Betfair.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Betfair%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
