### ISSUE TITLE
Icon submission: Let'sBit

### ISSUE THREAD

**Issue by sebastianserrani** [krisu5/aegis-icons#562]
### Icon type

Logo based

### URL of the site or app

https://letsbit.io

### Logo / icon info

Extracted from https://letsbit.io/static/media/letsbit_purple.7560b7a1.svg

### Background color info

Background color is from the logo. Altenate version uses the web site primary color.

### Upload icon(s)

[LetsBit.zip](https://github.com/aegis-icons/aegis-icons/files/8373728/LetsBit.zip)

### Anything else?

Thanks :)

### Confirmation

- [X] I have read and **carefully** followed [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md)

**Comment by krisu5** [comment]
Added to the repo (https://github.com/aegis-icons/aegis-icons/commit/bc30f840a4405717af14001bbf9f8ed5e8de1c9f). Only primary icon, not the variation.
