### ISSUE TITLE
Icon submission: SatoshiTango

### ISSUE THREAD

**Issue by sebastianserrani** [krisu5/aegis-icons#566]
### Icon type

Logo based

### URL of the site or app

https://www.satoshitango.com

### Logo / icon info

Image traced of https://www.satoshitango.com/static/img/app/iconoapp.svg

### Background color info

Background color is accent color frow web page.

### Upload icon(s)

[SatoshiTango.zip](https://github.com/aegis-icons/aegis-icons/files/8400647/SatoshiTango.zip)

### Confirmation

- [X] I have read and **carefully** followed [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md)

**Comment by krisu5** [comment]
Added to repo with bigger logo and changed BG color to color from the logo.
