### ISSUE TITLE
Icon request:  MacroDroid (forum)

### ISSUE THREAD

**Issue by rajarshikhatua** [krisu5/aegis-icons#567]
### URL of the site or app

https://play.google.com/store/apps/details?id=com.arlosoft.macrodroid&hl=en_IN&gl=US&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dmacrodroid&pcampaignid=APPU_1_1W1HYu2xH4i6seMP8ImSmAo

### Logo resources for the icon

*Removed by maintainer (raster image)*

**Comment by krisu5** [comment]
Rejected: not having Aegis supported 2FA support.

**Comment by rajarshikhatua** [comment]
> Rejected: not having Aegis supported 2FA support.

but this site -https://www.macrodroidforum.com
have 2FA support

**Comment by krisu5** [comment]
Still stays rejected **(please be more clear next time)**.

[We only make icons for really popular forums](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#case-by-case-basis) (at least over 250,000 total members and high posting activity). This forum only has 8000 members. For forums under the requirements, forum software related icons are the prefer solution.

Use **XenForo** icon.
