### ISSUE TITLE
Icon request: PythonAnywhere

### ISSUE THREAD

**Issue by EncryptCrystal** [krisu5/aegis-icons#568]
### URL of the site or app

https://www.pythonanywhere.com/

### Logo resources for the icon

https://www.pythonanywhere.com/static/anywhere/images/PA-logo.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/PythonAnywhere.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
