### ISSUE TITLE
Icon request: Skiff

### ISSUE THREAD

**Issue by habitualname** [krisu5/aegis-icons#569]
### URL of the site or app

https://skiff.org

### Logo resources for the icon

https://cdn.sanity.io/images/j846cla7/production/f492d70674ec4bac97dd6560e3bc0fb7acc8e080-163x64.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Skiff.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Skiff%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
