### ISSUE TITLE
Icon request: Cash App

### ISSUE THREAD

**Issue by TotalChris** [krisu5/aegis-icons#570]
### URL of the site or app

https://cash.app

### Logo resources for the icon

https://cash.app/press

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Cash%20App.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
