### ISSUE TITLE
Icon request: Hotbit

### ISSUE THREAD

**Issue by abhishek3x** [krisu5/aegis-icons#571]
### URL of the site or app

https://www.hotbit.io/

### Logo resources for the icon

https://seeklogo.com/vector-logo/426255/hotbit

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Hotbit.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
