### ISSUE TITLE
Icon request: Bitbns

### ISSUE THREAD

**Issue by abhishek3x** [krisu5/aegis-icons#572]
### URL of the site or app

https://bitbns.com/

### Logo resources for the icon

https://bitbns.com/assets/img/logos/bitbns.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Bitbns.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
