### ISSUE TITLE
Icon request: BitForex

### ISSUE THREAD

**Issue by abhishek3x** [krisu5/aegis-icons#573]
### URL of the site or app

https://www.bitforex.com/

### Logo resources for the icon

https://event.bitforex.com/en/Media.html

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/BitForex.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
