### ISSUE TITLE
Icon request: UseMyCards

### ISSUE THREAD

**Issue by abhishek3x** [krisu5/aegis-icons#574]
### URL of the site or app

https://usemycards.com/

### Logo resources for the icon

*Removed by maintainer (SVG code)*

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/UseMyCards.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
