### ISSUE TITLE
Icon request: Wasabi 

### ISSUE THREAD

**Issue by perplexityjeff** [krisu5/aegis-icons#575]
### URL of the site or app

https://wasabi.com/

### Anything else?

Service used for backup storage based on S3.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Wasabi.svg


:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
