### ISSUE TITLE
Icon request: Ripe NCC

### ISSUE THREAD

**Issue by jensz12** [krisu5/aegis-icons#579]
### URL of the site or app

https://www.ripe.net/

### Logo resources for the icon

https://www.ripe.net/about-us/press-centre/ripe-ncc-logos

**Comment by krisu5** [comment]
Don't change title format.

**Comment by CampinCarl** [comment]
I grabbed the [ripe-ncc-logo-white-svg](https://www.ripe.net/about-us/press-centre/ripe-ncc-logos/ripe-ncc-logo-white-svg) file from the provided logos page and made icons with both primary colors from the [RIPE NCC 2015 Brand Guidelines](https://www.ripe.net/about-us/press-centre/ripe-ncc-brand-guidelines/ripe-ncc-brand-guidelines-pdf) PDF (p. 25, see below).

![Ripe NCC Primary Colors](https://user-images.githubusercontent.com/11837803/163471805-48ee4977-3910-43f7-b18c-2ec439a857fe.png)

1. Blue `#131F48`
2. Orange `#ff6a00`

Blue Icon | Orange Icon
:---:|:---:
![Ripe NCC (Blue)](https://user-images.githubusercontent.com/11837803/163472059-18dab206-12ee-4173-a133-94c3fc4175c9.png)|![Ripe NCC (Orange)](https://user-images.githubusercontent.com/11837803/163472076-cb0b6bc2-e730-44bc-92c0-4c1ae720f6c7.png)
[RipeNCC (Blue).zip](https://github.com/aegis-icons/aegis-icons/files/8492087/RipeNCC.Blue.zip)|[RipeNCC (Orange).zip](https://github.com/aegis-icons/aegis-icons/files/8492089/RipeNCC.Orange.zip)

There are also three (3) secondary colors in the brand guidelines document if the primary colors aren't suitable (p. 26).

1. `#6ebe49`
2. `#009ba6`
3. `#c4d5ec`

Hope this helps.

**Comment by krisu5** [comment]
@CampinCarl You need to create submission issue for filling the request #560

**Comment by CampinCarl** [comment]
Thanks, I'll do that.

**Comment by krisu5** [comment]
Filled by #580.

Added icon: https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Ripe%20NCC.svg
