### ISSUE TITLE
Icon submission: Ripe NCC

### ISSUE THREAD

**Issue by CampinCarl** [krisu5/aegis-icons#580]
### Icon type

Logo based

### URL of the site or app

https://www.ripe.net

### Logo / icon info

https://www.ripe.net/about-us/press-centre/ripe-ncc-logos

### Background color info

Background color taken from the [Brand Guidelines][1] PDF (p. 25).

[1]: https://www.ripe.net/about-us/press-centre/ripe-ncc-brand-guidelines/ripe-ncc-brand-guidelines-pdf

![Ripe NCC Primary Colors](https://user-images.githubusercontent.com/11837803/163471805-48ee4977-3910-43f7-b18c-2ec439a857fe.png)

1. Blue `#131F48`
2. Orange `#ff6a00`

There are also three (3) secondary colors in the brand guidelines document if the primary colors aren't suitable (p. 26).

1. `#6ebe49`
2. `#009ba6`
3. `#c4d5ec`

### Upload icon(s)

Blue Icon | Orange Icon
:---:|:---:
![Ripe NCC (Blue)](https://user-images.githubusercontent.com/11837803/163472059-18dab206-12ee-4173-a133-94c3fc4175c9.png)|![Ripe NCC (Orange)](https://user-images.githubusercontent.com/11837803/163472076-cb0b6bc2-e730-44bc-92c0-4c1ae720f6c7.png)
[RipeNCC (Blue).zip](https://github.com/aegis-icons/aegis-icons/files/8492087/RipeNCC.Blue.zip)|[RipeNCC (Orange).zip](https://github.com/aegis-icons/aegis-icons/files/8492089/RipeNCC.Orange.zip)

### Anything else?

Reference icon request #579.

Given our previous conversations, the orange icon is probably the better pick for AMOLED screens.

### Confirmation

- [X] I have read and **carefully** followed [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) during the creation of the icon.

**Comment by krisu5** [comment]
Added to the repo!
