### ISSUE TITLE
Icon submission: Square

### ISSUE THREAD

**Issue by CampinCarl** [krisu5/aegis-icons#581]
### Icon type

Logo based

### URL of the site or app

https://squareup.com/

### Logo / icon info

https://assets.ctfassets.net/2d5q1td6cyxq/5MwNG75AWAupW4stBOc09I/20ad78008e6c04996e3d27d81f8ebb88/Square_Logo_External_Package.zip

### Background color info

Background color is from the logo.

Specifically, the `Square Logo Package.zip/SVG/Square_Jewel_Black.svg` file. Background color is `#1a1a1a`.

### Upload icon(s)

Icon
:---:
![Square](https://user-images.githubusercontent.com/11837803/164264686-b1cb1110-ca1f-4c29-9099-b920eb2c09b3.png)
[Square.svg.zip](https://github.com/aegis-icons/aegis-icons/files/8522853/Square.svg.zip)

### Anything else?

I found the **Square_Logo_External_Package.zip** file linked on Square's site here, [Press & Media](https://squareup.com/us/en/press); look for "Media Resources".

### Confirmation

- [X] I have read and **carefully** followed [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) during the creation of the icon.

**Comment by krisu5** [comment]
You'll need to make `bg.var` too.

**Comment by CampinCarl** [comment]
Understood, will this work?

bg.var
:---:
![Square bg var](https://user-images.githubusercontent.com/11837803/164322099-65903fbc-cbd6-4dbf-bbb3-dcf5d5eee958.png)
[Square bg.var.svg.zip](https://github.com/aegis-icons/aegis-icons/files/8525417/Square.bg.var.svg.zip)

I couldn't find any brand guidelines for alternate colors, so I grabbed a prominent blue from their homepage (used for buttons). Specifically, `#006aff`.

![Example](https://user-images.githubusercontent.com/11837803/164322860-8fed81ac-826e-418f-a7d0-be192c755125.png)

**Comment by krisu5** [comment]
Yeah, that's okay. Added to the repo.
