### ISSUE TITLE
Icon submission: USAA

### ISSUE THREAD

**Issue by CampinCarl** [krisu5/aegis-icons#582]
### Icon type

Logo based

### URL of the site or app

https://www.usaa.com/

### Logo / icon info

Extracted logo with SVG Gobbler from https://www.usaa.com/

### Background color info

Background color is from the logo.

There are two logos at time of writing (one blue and one white). I used the blue logo, i.e., `#0b2237`.

### Upload icon(s)

Icon
:---:
![USAA](https://user-images.githubusercontent.com/11837803/164271145-1b2dac18-0398-4dc2-a3a9-af9f713f5c0b.png)
[USAA.svg.zip](https://github.com/aegis-icons/aegis-icons/files/8523073/USAA.svg.zip)

### Confirmation

- [X] I have read and **carefully** followed [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) during the creation of the icon.

**Comment by krisu5** [comment]
Added to the repo!
