### ISSUE TITLE
Icon request: MC-Market

### ISSUE THREAD

**Issue by SteffoSpieler** [krisu5/aegis-icons#583]
### URL of the site or app

https://www.mc-market.org

### Anything else?

Here are the icon svgs that are inline in the page and not resources I would've been able to link to:

![mc-market-icon](https://user-images.githubusercontent.com/41108856/164513253-15164c13-fd1d-4966-a5cf-0cc8a52e1f58.svg)
![mc-market](https://user-images.githubusercontent.com/41108856/164513262-84be615c-30a5-495e-ad93-86de4438c731.svg)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/MC-Market.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
