### ISSUE TITLE
Icon request: Nitrado

### ISSUE THREAD

**Issue by SteffoSpieler** [krisu5/aegis-icons#584]
### URL of the site or app

https://nitrado.net

### Anything else?

Inline SVG:
[svg-gobbler](https://user-images.githubusercontent.com/41108856/164734763-786b14ca-50e1-45c0-b3cb-5ccdfecf97c8.svg)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Nitrado.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Nitrado%20fg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
