### ISSUE TITLE
Icon request: Wilma

### ISSUE THREAD

**Issue by unnervingduck** [krisu5/aegis-icons#586]
### URL of the site or app

https://www.wilma.fi/

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Wilma.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
