### ISSUE TITLE
Icon request: Plutus

### ISSUE THREAD

**Issue by CodeShakingSheep** [krisu5/aegis-icons#587]
### Homepage URL for the brand / app

https://plutus.it/

### Logo resources for the icon

https://plutus.it/press-kit

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Plutus.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
