### ISSUE TITLE
Icon request: Notesnook

### ISSUE THREAD

**Issue by drinkcoffee247** [krisu5/aegis-icons#588]
### Homepage URL for the brand / app

https://notesnook.com

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Notesnook.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
