### ISSUE TITLE
Icon request: Alibaba Cloud (Aliyun)

### ISSUE THREAD

**Issue by suomedualc** [krisu5/aegis-icons#589]
### Homepage URL for the brand / app

https://www.alibabacloud.com/

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Alibaba%20Cloud.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
