### ISSUE TITLE
Icon request: Uplay

### ISSUE THREAD

**Issue by suomedualc** [krisu5/aegis-icons#590]
### Homepage URL for the brand / app

https://www.ubisoft.com/

**Comment by krisu5** [comment]
Already exists under "Ubisoft" name:
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Ubisoft.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Ubisoft%20bg.var.svg
