### ISSUE TITLE
Icon request: Postmark

### ISSUE THREAD

**Issue by k3davis** [krisu5/aegis-icons#591]
### Homepage URL for the brand / app

https://www.postmarkapp.com

### Logo resources for the icon

https://assets-useast2.postmarkapp.com/packs/images/application/logo-stamp-c9d74579.svg

### Anything else?

They were recently acquired by ActiveCampaign which also doesn't seem to have an icon, but they are supposed to remain independent, so we'll see how that goes.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Postmark.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Postmark%20fg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
