### ISSUE TITLE
Icon request: Boomi

### ISSUE THREAD

**Issue by k3davis** [krisu5/aegis-icons#592]
### Homepage URL for the brand / app

https://www.boomi.com

### Logo resources for the icon

https://user-images.githubusercontent.com/1307914/168067761-2115e46d-3a75-4acf-97b2-084cad4446ad.svg

### Anything else?

Boomi is an integration platform owned by Dell. If Boomi itself is too niche for an icon, you could consider adding one for Dell instead, which might be more broadly useful:

https://upload.wikimedia.org/wikipedia/commons/4/48/Dell_Logo.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Boomi.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
