### ISSUE TITLE
Icon request: woelkli (wölkli)

### ISSUE THREAD

**Issue by CodeShakingSheep** [krisu5/aegis-icons#593]
### Homepage URL for the brand / app

https://woelkli.com/en

### Anything else?

Logo on their homepage is in gif raster format. Couldn't find a svg file unfortunately.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/woelkli.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
