### ISSUE TITLE
Icon request: sipgate

### ISSUE THREAD

**Issue by nichu42** [krisu5/aegis-icons#594]
### Homepage URL for the brand / app

https://www.sipgate.de/

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/sipgate.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/sipgate%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
