### ISSUE TITLE
Icon request: Bitso

### ISSUE THREAD

**Issue by puerkito66** [krisu5/aegis-icons#595]
### URL for the brand / site / app

https://bitso.com

### Logo resources for the icon

https://assets.bitso.com/static/media/logo_dark.93562fe3.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Bitso.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Bitso%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
