### ISSUE TITLE
Icon submission: Elastic

### ISSUE THREAD

**Issue by jessiehildebrandt** [krisu5/aegis-icons#596]
### Icon type

Logo based

### URL of the site or app

https://www.elastic.co/

### Logo / icon info

https://images.contentstack.io/v3/assets/bltefdd0b53724fa2ce/blt280217a63b82a734/6202d3378b1f312528798412/elastic-logo.svg

### Background color info

Background color is from the logo; `#07c` was picked from the available colors because it is also used as the primary UI color on their site:
![screenshot](https://user-images.githubusercontent.com/40772633/168520097-699b6d6e-a55d-4782-bf61-882d7f2362f6.png)

### Upload icon(s)

[Elastic.zip](https://github.com/aegis-icons/aegis-icons/files/8697163/Elastic.zip)

### Anything else?

The direct link to the logo vector file was pulled from the [landing page of the company's site](https://www.elastic.co/); it is being served by a third-party CDN.

### Confirmation

- [X] I have read and **carefully** followed [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) during the creation of the icon.

**Comment by krisu5** [comment]
Added to the repo! 👍
