### ISSUE TITLE
Icon request: Handshake

### ISSUE THREAD

**Issue by jakariyaa** [krisu5/aegis-icons#597]
### URL for the brand / site / app

https://handshake.org/

### Logo resources for the icon

https://handshake.org/images/landing/logo-dark.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Handshake.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Handshake%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
