### ISSUE TITLE
Icon request: SuperHosting.BG

### ISSUE THREAD

**Issue by theLittlePrinceAD** [krisu5/aegis-icons#599]
### URL for the brand / site / app

https://en.superhosting.bg/

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/SuperHosting.BG.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
