### ISSUE TITLE
Icon request: FetLife

### ISSUE THREAD

**Issue by artemislena** [krisu5/aegis-icons#600]
### URL for the brand / site / app

https://fetlife.com (NSFW)

### Logo resources for the icon

https://fetlife.com/favicons/icon.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/FetLife.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
