### ISSUE TITLE
Icon request: LabyMod

### ISSUE THREAD

**Issue by RealMuffinTime** [krisu5/aegis-icons#601]
### URL for the brand / site / app

https://www.labymod.net/

### Logo resources for the icon

https://www.labymod.net/branding

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/LabyMod.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
