### ISSUE TITLE
Icon request: Kwansei Gakuin University

### ISSUE THREAD

**Issue by ghost** [krisu5/aegis-icons#605]
### URL for the brand / site / app

https://global.kwansei.ac.jp/

### Logo resources for the icon

https://kwansei-ksc.jp/common/img/logo_univ_blue.svg

### Anything else?

Different logo at https://www.kwansei.ac.jp (better suited for icon)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Kwansei%20Gakuin%20University.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Kwansei%20Gakuin%20University%20fg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
