### ISSUE TITLE
Icon request: Kyoto Sangyo University

### ISSUE THREAD

**Issue by ghost** [krisu5/aegis-icons#606]
### URL for the brand / site / app

https://www.kyoto-su.ac.jp/index-e.html

### Logo resources for the icon

https://www.kyoto-su.ac.jp/common-wr/img/ks2030_logo.svg

### Anything else?

Different logo at https://www.kyoto-su.ac.jp/ (better suited for logo)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Kyoto%20Sangyo%20University.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
