### ISSUE TITLE
Icon request: Kindai University

### ISSUE THREAD

**Issue by ghost** [krisu5/aegis-icons#607]
### URL for the brand / site / app

https://www.kindai.ac.jp/english/

### Logo resources for the icon

https://www.shingu.kindai.ac.jp/wp/wp-content/uploads/2019/08/emblem.svg

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Kindai%20University.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
