### ISSUE TITLE
Icon request: VicRoads

### ISSUE THREAD

**Issue by Cautious-Software701** [krisu5/aegis-icons#609]
### URL for the brand / site / app

https://vicroads.vic.gov.au/

### Logo resources for the icon

_Deleted by maintainer (raster image)_

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/VicRoads.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
