### ISSUE TITLE
Icon request: RMIT University

### ISSUE THREAD

**Issue by Cautious-Software701** [krisu5/aegis-icons#610]
### URL for the brand / site / app

https://rmit.edu.au/

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/RMIT%20University.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
