### ISSUE TITLE
🏝 Taking a break, requests / issues are closed for the time being

### ISSUE THREAD

**Issue by krisu5** [krisu5/aegis-icons#611]
I have done icons for ~3 years with just small breaks and I don't want request flood when I'm gone, so I decided to just close the issues / requests for now.

There's lot of IRL stuff I have to do, so I cannot focus on this project right now.

I can't close PR submissions, but that's OK for me. Just don't expect immediate response from me.

**EDIT 2022-06-07:** I will accept / edit / close PRs and make related commits if I have time.

**EDIT 2022-07-10:** Do not request icons in the comment section, I will remove them. Requests will probably open after the summer time if not earlier.

Thank you for your patience.

**Comment by joshsleeper** [comment]
Always worth prioritizing self-care, and thanks for all the hard work and amazing icons over the past many years!
Here's hoping you can eventually return to this project as it really is one of the best icon packs around~

**Comment by holequantum** [comment]
fedora icon
https://fr.m.wikipedia.org/wiki/Fedora_Linux#/media/Fichier:Fedora_icon_(2021).svg
kinfly add this to the repo.

**Comment by holequantum** [comment]
https://foundation.gnome.org/logo-and-trademarks/
gnome logo
bromite logo - https://github.com/bromite/bromite

**Comment by krisu5** [comment]
Do not request icons in the comment section, I will remove them. Requests will probably open after the summer time if not earlier.

Thank you for your patience.

**Comment by krisu5** [comment]
Sorry for the long break, but finally issues are reopened again!
