### ISSUE TITLE
Icon request: Revolt

### ISSUE THREAD

**Issue by qwerty287** [krisu5/aegis-icons#638]
### URL for the brand / site / app

https://revolt.chat/

### Logo resources for the icon

https://revolt.chat/_next/static/media/revolt-logo.24213514.svg or https://revolt.chat/favicon.ico (the favicon is quadratic, the other one not)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Revolt.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
