### ISSUE TITLE
Icon request: Neos

### ISSUE THREAD

**Issue by digitalcircuit** [krisu5/aegis-icons#640]
### URL for the brand / site / app

https://neos.com/

### Logo resources for the icon

https://wiki.neos.com/Branding

### Anything else?

Neos might also be referred to as Neos VR or Neos Metaverse.

The official wiki page above links to [a Google Drive folder, with the vector resources here](https://drive.google.com/drive/folders/1BD4GopdP5-aJtJob_V_4CcV-VF-2Vtc3 ).

Neos provides standardized 2FA inside the game with the `Setup 2FA` button.  You cannot do this via the website (almost all Neos functionality happens inside the game).

Setup was originally tested with andOTP, then migrated into Aegis (TOTP, SHA1, 6 digits).

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Neos.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
