### ISSUE TITLE
Icon request: Ghost

### ISSUE THREAD

**Issue by drinkcoffee247** [krisu5/aegis-icons#646]
### URL for the brand / site / app

https://ghost.org

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
There's no 2FA for Ghost: https://forum.ghost.org/t/multi-factor-authentication/548
