### ISSUE TITLE
Icon request: TruckersMP

### ISSUE THREAD

**Issue by Marty42780** [krisu5/aegis-icons#649]
### URL for the brand / site / app

https://truckersmp.com/

### Anything else?

Proof: Here are the instructions to activate the A2F: https://truckersmp.com/knowledge-base/article/16

Note: TruckersMP is a Mod or Euro Truck Simulator 2 and isn't affiliate with the game.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/TruckersMP.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*

**Comment by Marty42780** [comment]
Thanks for your quick response. 
Best wishes. 
Marty42
