### ISSUE TITLE
Icon request: F-Secure

### ISSUE THREAD

**Issue by ghost** [krisu5/aegis-icons#652]
### URL for the brand / site / app

https://www.f-secure.com/

### Logo resources for the icon

https://my.f-secure.com/img/icon_safe.fd5ebf54.svg

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/F-Secure.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
