### ISSUE TITLE
Icon request: ImprovMX

### ISSUE THREAD

**Issue by rbardini** [krisu5/aegis-icons#655]
### URL for the brand / site / app

https://improvmx.com/

### Logo resources for the icon

https://improvmx.com/wp-content/themes/improvmx/img/safari-pinned-tab.svg

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/ImprovMX.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
