### ISSUE TITLE
Icon request: Loket.nl

### ISSUE THREAD

**Issue by rbardini** [krisu5/aegis-icons#656]
### URL for the brand / site / app

https://www.loket.nl/

### Logo resources for the icon

https://www.loket.nl/wp-content/uploads/2020/02/loket_logo_new.svg

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Loket.nl.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
