### ISSUE TITLE
Icon request: PlanetScale

### ISSUE THREAD

**Issue by zigou23** [krisu5/aegis-icons#657]
### URL for the brand / site / app

https://planetscale.com/

### Logo resources for the icon

*Removed by maintainer (duplicate of "URL for the brand / site / app")*

### Anything else?
*Removed by maintainer (SVG code)*

### Confirmation

- [x] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/PlanetScale.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/PlanetScale%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
