### ISSUE TITLE
Icon request: one.com

### ISSUE THREAD

**Issue by jensz12** [krisu5/aegis-icons#658]
### URL for the brand / site / app

https://one.com

### Logo resources for the icon

Have added as files, as i cant link from interneal one.com site

### Anything else?

[one.com logo guidelines.pdf](https://github.com/aegis-icons/aegis-icons/files/9447401/one.com.logo.guidelines.pdf)
![one com inner dot](https://user-images.githubusercontent.com/1682377/187281021-4db3cf4d-f491-4ff4-8e27-9deb08e3d4be.svg)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/one.com.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
