### ISSUE TITLE
Icon request: Farmad

### ISSUE THREAD

**Issue by jdeluyck** [krisu5/aegis-icons#659]
### URL for the brand / site / app

https://farmad.be

### Logo resources for the icon

https://www.farmad.be/wp-content/themes/typografics/dist/assets/images/logo_farmad.svg

### Anything else?

![image](https://user-images.githubusercontent.com/5451787/187658627-c4b85014-216f-45be-a730-35b17928916f.png)

It's in dutch, but basically it is asking for the 2FA TOTP code.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Farmad.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
