### ISSUE TITLE
Icon request: Norton

### ISSUE THREAD

**Issue by jdeluyck** [krisu5/aegis-icons#660]
### URL for the brand / site / app

https://norton.com

### Logo resources for the icon

https://upload.wikimedia.org/wikipedia/commons/8/83/Norton-logo-2021.svg

### Anything else?

![image](https://user-images.githubusercontent.com/5451787/187659643-ff2f39d1-d02e-427c-bba0-578ee71d1b0b.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Norton.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Norton%20fg.var.svg

:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
