### ISSUE TITLE
Icon request: Outlook

### ISSUE THREAD

**Issue by alphanerdgen** [krisu5/aegis-icons#661]
### URL for the brand / site / app

https://outlook.live.com/owa/

### Logo resources for the icon

https://commons.m.wikimedia.org/wiki/File:Microsoft_Office_Outlook_(2018%E2%80%93present).svg

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Outlook is sub-brand of Microsoft and uses Microsoft account system.

Use **Microsoft** icon.
