### ISSUE TITLE
Update icon: Microsoft

### ISSUE THREAD

**Issue by alphanerdgen** [krisu5/aegis-icons#663]
### URL for the brand / site / app

https://microsoft.com

### Reason for update

Updated brand color

### Logo resources for the icon

https://uxwing.com/microsoft-icon/

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
See https://github.com/aegis-icons/aegis-icons/issues/140#issuecomment-735439804
