### ISSUE TITLE
Icon request: Mail.ru

### ISSUE THREAD

**Issue by Sergo1217** [krisu5/aegis-icons#666]
### URL for the brand / site / app

https://mail.ru/

### Logo resources for the icon

https://simpleicons.org/icons/maildotru.svg

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
[2FA Directory](https://2fa.directory/int/) says that app-based 2FA is only available from their proprietary app, cannot 100% confirm from [docs](https://help.mail.ru/mail-help/2auth).

Rejected for now, unless you give evidence via comment that it does has 3rd party supported 2FA (take a screenshot of the 2FA settings, censor sensitive information if needed).
