### ISSUE TITLE
Icon request: YooMoney

### ISSUE THREAD

**Issue by Sergo1217** [krisu5/aegis-icons#667]
### URL for the brand / site / app

https://yoomoney.ru/

### Logo resources for the icon

https://yoomoney.ru/page?id=522991

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Rejected: 3rd party app 2FA is [discontinued](https://yoomoney.ru/page?id=536116) (part of ["icon acceptability criteria"](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#not-approved))
