### ISSUE TITLE
Icon request: Gaijin

### ISSUE THREAD

**Issue by Sergo1217** [krisu5/aegis-icons#668]
### URL for the brand / site / app

https://gaijin.net/

### Logo resources for the icon

https://www.svgrepo.com/svg/331402/gaijin-entertainment

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Already exists:
- https://aegis-icons.github.io/icons/primary/Gaijin%20Entertainment.svg
- https://aegis-icons.github.io/icons/variations/Gaijin%20Entertainment%20bg.var.svg

Please search from the aegis-icons website too next time.

P.S. Your logo resource link's SVG is actually from aegis-icons, kinda funny.
