### ISSUE TITLE
Icon request: Misskey

### ISSUE THREAD

**Issue by Sergo1217** [krisu5/aegis-icons#670]
### URL for the brand / site / app

https://misskey-hub.net/

### Logo resources for the icon

https://github.com/misskey-dev/assets

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Misskey.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
