### ISSUE TITLE
Icon request: Torum

### ISSUE THREAD

**Issue by authorturker** [krisu5/aegis-icons#672]
### URL for the brand / site / app

https://www.torum.com/

### Anything else?

2FA Proof:
![image](https://user-images.githubusercontent.com/96711166/188307163-c69d78f8-d5f5-4f80-8bd0-d1051928fb64.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Torum.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
