### ISSUE TITLE
Icon request: XGo

### ISSUE THREAD

**Issue by authorturker** [krisu5/aegis-icons#673]
### URL for the brand / site / app

https://xgo.com/

### Anything else?

2FA Proof:
![Ekran görüntüsü 2022-09-04 123958](https://user-images.githubusercontent.com/96711166/188307320-054f2dec-9371-4d4d-80f3-368b107d4767.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Rejected: site being too vague (part of [icon acceptability criteria](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#case-by-case-basis)).

**Comment by authorturker** [comment]
The website is in Beta. For the being vague part, I can provide some evidence from website. (To clarify this part: we need at least some evidence from the web. Otherwise it counts as "suspiciously shady".)
To access exchange interface, you can use this link: https://xgo.com/btc-to-usdt
BTC-USDT trading page:
![image](https://user-images.githubusercontent.com/96711166/188623961-82e61880-31d0-487f-ba62-373b79c1fb22.png)

Market overview: 
![image](https://user-images.githubusercontent.com/96711166/188624097-29a57723-8294-462b-a876-f44a08cb1ab6.png)

Superfluid Rewards:
![image](https://user-images.githubusercontent.com/96711166/188624205-2ced0c79-c066-4f92-a349-ca6f3e075cf5.png)

**Comment by authorturker** [comment]
While waiting for an icon, I made one myself. I used original logo, it was data url. I used button colors as bg.
![XGO](https://user-images.githubusercontent.com/96711166/189413845-5e46e1fa-7075-4ba4-9f81-986f1e15a3d0.svg)
