### ISSUE TITLE
Icon request: LinkAce

### ISSUE THREAD

**Issue by lenicyl** [krisu5/aegis-icons#676]
### URL for the brand / site / app

https://linkace.org

### Logo resources for the icon

SVG : https://github.com/Kovah/LinkAce/blob/main/public/favicon.svg , Reference : https://github.com/Kovah/LinkAce/blob/main/public/android-chrome-384x384.png

### Anything else?

This app does support two factor authentication, [_proof_](https://www.linkace.org/docs/v1/configuration/user-settings/#two-factor-authentication)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/LinkAce.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
