### ISSUE TITLE
Icon request: Chaturbate

### ISSUE THREAD

**Issue by EncryptCrystal** [krisu5/aegis-icons#677]
### URL for the brand / site / app

https://chaturbate.com/ (NSFW)

### Logo resources for the icon

https://commons.wikimedia.org/wiki/File:Chaturbate_logo.svg#/media/File:Chaturbate_logo.svg

### Anything else?

I confirm that the TOTP is available at this address: https://chaturbate.com/security/tfa/devices/

![image](https://user-images.githubusercontent.com/52292872/192058638-1597b423-dd86-4b47-b419-07ac2c6a0204.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Chaturbate.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
