### ISSUE TITLE
Icon request: Coursera

### ISSUE THREAD

**Issue by EncryptCrystal** [krisu5/aegis-icons#678]
### URL for the brand / site / app

https://www.coursera.org/

### Logo resources for the icon

https://commons.wikimedia.org/wiki/File:Coursera-Logo_600x600.svg

### Anything else?

The activation of TOTP is done here: https://www.coursera.org/account-settings

Warning, this 2FA is presented as being in beta. Nevertheless, it works (I use it since several months with Aegis).

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Coursera.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
