### ISSUE TITLE
Icon request: Vimeo

### ISSUE THREAD

**Issue by EncryptCrystal** [krisu5/aegis-icons#679]
### URL for the brand / site / app

https://vimeo.com

### Logo resources for the icon

https://www.svgrepo.com/show/299483/vimeo.svg

### Anything else?

The activation of TOTP is done here: https://vimeo.com/settings/account/security

The link of the given icon is not official, but in free license.
Another possible logo here : https://fr.m.wikipedia.org/wiki/Fichier:Vimeo_Logo.svg

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
I made the icon few hours ago: https://aegis-icons.github.io/icons/primary/Vimeo.svg
