### ISSUE TITLE
Icon request: Fansly

### ISSUE THREAD

**Issue by EncryptCrystal** [krisu5/aegis-icons#680]
### URL for the brand / site / app

https://fansly.com (NSFW)

### Logo resources for the icon

https://commons.wikimedia.org/wiki/File:Fansly_logo.svg

### Anything else?

Activate TOTP here: https://fansly.com/settings/account

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Fansly.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
