### ISSUE TITLE
Icon request: ManyVids

### ISSUE THREAD

**Issue by EncryptCrystal** [krisu5/aegis-icons#681]
### URL for the brand / site / app

https://www.manyvids.com (NSFW)

### Logo resources for the icon

https://d3e1078hs60k37.cloudfront.net/site_files/images/icons/mv-straight-icon.svg

### Anything else?

TOTP can be activated here: https://www.manyvids.com/Security-center/

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/ManyVids.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/ManyVids%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
