### ISSUE TITLE
Icon submission: XGo

### ISSUE THREAD

**Issue by authorturker** [krisu5/aegis-icons#682]
### URL of the site or app

https://xgo.com/

### Logo / icon info

Extracted original logo with dev tools of the website and edited using official colors

### Background color info

I took the yellow tone from official buttons with dev tools. I dig the CSS and found the HEX code. 
![image](https://user-images.githubusercontent.com/96711166/192139981-d600a8b4-07d1-4377-8fb8-f38c21955f7c.png)

### Upload icon(s)

![XGO](https://user-images.githubusercontent.com/96711166/192139999-9200fd9a-ab8c-4354-ae45-260fa84acbd0.svg)

### Anything else?

You can reach exchange interface with this link: https://xgo.com/algo-to-usdt

### Confirmation

- [X] I have **read and carefully followed** [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) during the creation of the icon.

**Comment by krisu5** [comment]
Logo needs to be white

**Comment by krisu5** [comment]
1. Logo needs to be white
2. Logo is too big, keep it inside of the guides (in the most inner sider ones).
3. Logo needs to be in one path.

Please read the docs for more info.

**Comment by authorturker** [comment]
1. Done but changed bg with black because with that yellow tone, logo becomes invisible
2. Done
3. I'm using affinity photo (not designer) so I have no idea how to do it.
![XGO](https://user-images.githubusercontent.com/96711166/192145760-50330a5b-44dc-4df8-9a44-3c8f97321639.svg)

**Comment by krisu5** [comment]
> 1. Done but changed bg with black because with that yellow tone, logo becomes invisible

Well, then you need `bg.var` version too: https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#bgvar-fgvar--fgbgvar-icons

Make the one with yellow bg too (and have it with white logo).

---

We don't recommend Affinity **Photo**, it's not proper vector graphics software even if it has some vector functions.

We will not accept icons made with **Affinity Photo** after these and MEXC ones.

I'm updating CONTRIBUTING document related to this.

**Comment by authorturker** [comment]
bg.var version:
![XGO bg var](https://user-images.githubusercontent.com/96711166/192150315-08c4850b-3ba5-496b-8b60-81b01cc69cde.svg)

Yellow bg + white logo

Sorry for using wrong editing tool 🥲

**Comment by authorturker** [comment]
And I guess this one fits for fg.bg.var alternative:
![XGO fg bg var](https://user-images.githubusercontent.com/96711166/192150471-aabc7110-8340-4dd8-8640-7a3fb741d233.svg)

**Comment by krisu5** [comment]
Added to the repo!
