### ISSUE TITLE
Icon submission: MEXC

### ISSUE THREAD

**Issue by authorturker** [krisu5/aegis-icons#683]
### URL of the site or app

https://www.mexc.com/

### Logo / icon info

https://www.mexc.com/images/full-logo-dark.svg

### Background color info

I used the logo color at bg and bg color at logo. Didin't change the color palette. Used same ones. 
https://www.mexc.com/images/full-logo-dark.svg

### Upload icon(s)

![MEXC](https://user-images.githubusercontent.com/96711166/192140094-889379b3-f265-49fe-9761-339aec6e83cc.svg)

### Anything else?

I'm GitHub noob. Opening PR is a really complicated thing for me. Sorry for opening as issue.

### Confirmation

- [X] I have **read and carefully followed** [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) during the creation of the icon.

**Comment by krisu5** [comment]
1. Logo needs to be in one path
   - Divine the line part with rest of the logo
2. I would make the logo slightly smaller, `600 px` width is good number.

**Comment by authorturker** [comment]
For 1st one, I'm using affinity photo (not designer) so I have no idea how to do it.
For 2nd one, I made it little bit smaller:
![MEXC](https://user-images.githubusercontent.com/96711166/192145656-21cc0441-c8b4-4f22-a676-8d69b60ead9b.svg)

**Comment by krisu5** [comment]
Fine, but we will not accept icons made with **Affinity Photo** after these and XGo ones.

Affinity Photo isn't proper vector graphics program, even if it has _some_ vector features.

I'm updating CONTRIBUTING document related to this and editing / adding icons to pack later.

**Comment by authorturker** [comment]
Sorry, I just wanted to help project but I didn't use vector editing programs before. 🥲

**Comment by krisu5** [comment]
Added to the repo!
