### ISSUE TITLE
Icon request: Zenegy

### ISSUE THREAD

**Issue by jensz12** [krisu5/aegis-icons#684]
### URL for the brand / site / app

https://zenegy.com/en-gb

### Logo resources for the icon

https://zenegy.com/media/2979/zenegy-logopakke.zip

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Zenegy.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
