### ISSUE TITLE
Icon request: Smarkets

### ISSUE THREAD

**Issue by ghost** [krisu5/aegis-icons#686]
### URL for the brand / site / app

https://smarkets.com/

### Logo resources for the icon

https://drive.google.com/drive/folders/1SUXkilDncw3Zn4ricA70d71zzYwk6oDC

### Anything else?

Hello, 

Smarkets is a betting exchange company similar to Betfair (Betfair logo already exists on the Aegis icon pack).
https://en.wikipedia.org/wiki/Smarkets

**Proof of 2FA:** https://help.smarkets.com/hc/en-gb/articles/115000822171-Using-two-factor-authentication

I contacted staff via email and they have uploaded their logo in SVG form on their press kit. The link to the press kit is a Google Drive link found on https://smarkets.com/about/

Thank you for your consideration.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Smarkets.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*

**Comment by ghost** [comment]
Thank you very much Mr Salonen, your work is very much appreciated. Have a great week!
