### ISSUE TITLE
Icon request: Fly.io (Fly)

### ISSUE THREAD

**Issue by salim-b** [krisu5/aegis-icons#687]
### URL for the brand / site / app

https://fly.io/

### Logo resources for the icon

https://fly.io/docs/about/brand/

### Anything else?

2FA TOTP Proof (redacted QR code):

![Screenshot 2022-09-28 at 23-31-30 Two Factor Authentication · Fly](https://user-images.githubusercontent.com/20040931/192906451-a6b35550-4b8e-4cff-bd5d-7ba2a6a18eb0.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Filled by #689:

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Fly.io.svg
