### ISSUE TITLE
Icon request: EXMO

### ISSUE THREAD

**Issue by salim-b** [krisu5/aegis-icons#688]
### URL for the brand / site / app

https://exmo.com/

### Logo resources for the icon

https://info.exmo.com/en/about-us/

### Anything else?

2FA TOTP Proof (at login):

![Screenshot 2022-09-28 at 23-41-44 Login](https://user-images.githubusercontent.com/20040931/192907400-c0491130-995c-4a04-a0f7-b9b5349df239.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/EXMO.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
