### ISSUE TITLE
Icon request: Salesforce

### ISSUE THREAD

**Issue by edent** [krisu5/aegis-icons#692]
### URL for the brand / site / app

https://www.salesforce.com/uk/

### Logo resources for the icon

https://c1.sfdcstatic.com/content/dam/sfdc-docs/www/logos/logo-salesforce.svg

### Anything else?

https://help.salesforce.com/s/articleView?id=sf.security_overview_2fa.htm&language=en_US&type=5

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Filled by #702:

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Salesforce.svg
