### ISSUE TITLE
Icon request: Bitcoin.de

### ISSUE THREAD

**Issue by mdPlusPlus** [krisu5/aegis-icons#693]
### URL for the brand / site / app

https://www.bitcoin.de/

### Logo resources for the icon

https://www.bitcoin.de/build/images/svg/bc_logo.svg

### Anything else?

I can only find a .svg with the logo **and** the text "bitcoin.de", so it would need to be modified.  
There's a press kit, but it seems unavailable at the moment: https://www.bitcoin.de/en/presse

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Bitcoin.de.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
