### ISSUE TITLE
Icon request: SideShift.ai

### ISSUE THREAD

**Issue by mdPlusPlus** [krisu5/aegis-icons#694]
### URL for the brand / site / app

https://sideshift.ai/

### Logo resources for the icon

https://uploads-ssl.webflow.com/5cb4563abba38c3bf60f33d7/60a36b5145577d75ad82d618_sideshift-logo-light.svg

### Anything else?

I can only find a .svg with the logo and the text "sideshift.ai", so it would need to be modified.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/SideShift.ai.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
