### ISSUE TITLE
Icon submission: KnowBe4

### ISSUE THREAD

**Issue by justsomemate** [krisu5/aegis-icons#695]
### URL of the site or app

https://www.knowbe4.com/

### Logo / icon info

https://www.knowbe4.com/hubfs/KB4-logo_BW.svg

### Background color info

Background color (#f16823) is from the regular full-color logo (https://www.knowbe4.com/hubfs/KB4-logo.svg?noresize)

### Upload icon(s)

[KnowBe4.zip](https://github.com/aegis-icons/aegis-icons/files/9691329/KnowBe4.zip)

### Confirmation

- [X] I have **read and carefully followed** [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) during the creation of the icon.

**Comment by krisu5** [comment]
Added to the repo!
