### ISSUE TITLE
Icon submission: LibreNMS

### ISSUE THREAD

**Issue by justsomemate** [krisu5/aegis-icons#696]
### URL of the site or app

https://www.librenms.org/

### Logo / icon info

https://www.librenms.org/images/LibreNMS-Logo.svg

### Background color info

Background color (#db202e) is from the logo

### Upload icon(s)

[LibreNMS.zip](https://github.com/aegis-icons/aegis-icons/files/9691335/LibreNMS.zip)

### Anything else?

This is self-hosted software.
[GitHub repository](https://github.com/librenms/librenms) has 2900+ stars

### Confirmation

- [X] I have **read and carefully followed** [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) during the creation of the icon.

**Comment by krisu5** [comment]
Added to the repo!
