### ISSUE TITLE
Icon request: Questrade

### ISSUE THREAD

**Issue by Hangten10** [krisu5/aegis-icons#697]
### URL for the brand / site / app

https://www.questrade.com/

### Logo resources for the icon

https://cdn.questrade.com/images/Questrade-Logo-Primary-Black-Medium.svg

### Anything else?

![image](https://user-images.githubusercontent.com/3211799/193435830-506e44ff-d1d0-4bf6-abdf-aa4f85f02316.png)

https://www.questrade.com/learning/questrade-basics/lesson/account-profile-and-security

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Questrade.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
