### ISSUE TITLE
Icon request: Qt

### ISSUE THREAD

**Issue by Sergo1217** [krisu5/aegis-icons#698]
### URL for the brand / site / app

https://qt.io/

### Logo resources for the icon

https://brand.qt.io/design

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Couldn't find anything related to 2FA function inside this service / site.

Add comment with screenshot proof if you want this open again (hide sensitive info if needed) or link to QT's documentation page related to 2FA.

**Comment by Sergo1217** [comment]
https://login.qt.io/status-otp
![2022-10-12_14-35-42](https://user-images.githubusercontent.com/16447886/195372217-cad6192d-6f76-4bb1-a593-198c47200ce7.png)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Qt.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
