### ISSUE TITLE
Icon submission: Mint Mobile

### ISSUE THREAD

**Issue by justsomemate** [krisu5/aegis-icons#701]
### URL of the site or app

https://www.mintmobile.com

### Logo / icon info

https://cdn.mintmobile.com/wp-content/themes/mintmobile/v3/assets/images/MM_Logo_Horizontal.svg

### Background color info

Background color is from the logo (`#68af85`).

### Upload icon(s)

[Mint Mobile.zip](https://github.com/aegis-icons/aegis-icons/files/9702653/Mint.Mobile.zip)

### Anything else?

I tried to get the size/alignment of "mobile" as close to how it appears in their [Twitter profile](https://twitter.com/Mintmobile/photo) as I could.

Fills https://github.com/aegis-icons/aegis-icons/issues/691

### Confirmation

- [X] I have **read and carefully followed** [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) during the creation of the icon.

**Comment by krisu5** [comment]
Added to the repo and closed the request.
