### ISSUE TITLE
Icon submission: Onshape

### ISSUE THREAD

**Issue by cammarin** [krisu5/aegis-icons#703]
### URL of the site or app

https://www.onshape.com

### Logo / icon info

Copied SVG logo from the website header using browser dev tools.

### Background color info

Background color is from the logo (`#64bc4f`).

### Upload icon(s)

[Onshape.zip](https://github.com/aegis-icons/aegis-icons/files/9737385/Onshape.zip)

### Anything else?

I tried to follow their social media avatar but the proportions clashed with the rest.

You can check 2FA support at [2FA Directory](https://2fa.directory/int/).

### Confirmation

- [X] I have **read and carefully followed** [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) during the creation of the icon.

**Comment by cammarin** [comment]
Using Twitter profile picture as reference:

![Onshape-original](https://user-images.githubusercontent.com/936220/194650178-1e85fb95-3d83-4789-8f29-bfa986a9ce30.png)

After adjusting size:

![Onshape-fixed](https://user-images.githubusercontent.com/936220/194650314-39f4f89b-9bd0-4483-9e28-56bd5931d11a.png)

**Comment by krisu5** [comment]
> I tried to follow their social media avatar but the proportions clashed with the rest.

I assume you read #701 and misunderstood: you **shouldn't** follow how social media avatar presents their logo, that was just one time thing related to this: https://github.com/aegis-icons/aegis-icons/issues/691#issuecomment-1264604713

Everything you need is in the CONTRIBUTING doc, don't copy what other submissions / PRs does because it leads to misunderstandings like this one.

**Comment by cammarin** [comment]
I thought of using official material as references, such as app icons and avatars, but in the end, I didn‘t like how it was displayed alongside the others.

**Comment by krisu5** [comment]
> I thought of using official material as references, such as app icons and avatars, but in the end, I didn‘t like how it was displayed alongside the others.

Sorry, my mistake.

But anyway, logo is too big, aim more like this size: https://aegis-icons.github.io/icons/primary/LibreNMS.svg

**Comment by cammarin** [comment]
Updated: [Onshape.zip](https://github.com/aegis-icons/aegis-icons/files/9737898/Onshape.zip)

![Onshape](https://user-images.githubusercontent.com/936220/194676117-79026259-c9d3-47d9-afa0-d4f545c9e4f7.png)

**Comment by krisu5** [comment]
Added to the repo.
