### ISSUE TITLE
Icon submission: Nintendo

### ISSUE THREAD

**Issue by cammarin** [krisu5/aegis-icons#704]
### URL of the site or app

https://www.nintendo.com

### Logo / icon info

Copied SVG wordmark from the website header using browser dev tools.

### Background color info

Background color is from the logo (`#e60012`).

### Upload icon(s)

[Nintendo alt.zip](https://github.com/aegis-icons/aegis-icons/files/9737684/Nintendo.alt.zip)

### Anything else?

Alternative logo using the common wordmark.

### Confirmation

- [X] I have **read and carefully followed** [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) during the creation of the icon.

**Comment by cammarin** [comment]
![Nintendo](https://user-images.githubusercontent.com/936220/194669659-3fc4dda8-bf58-40d5-b6ba-b40d5fe50592.png)

**Comment by krisu5** [comment]
Thanks for submission, but we have to reject this one. 

It doesn't count as alternative logo and original logo is too wide for icon.
