### ISSUE TITLE
Icon request: My Digital Life Forums

### ISSUE THREAD

**Issue by McRoyce** [krisu5/aegis-icons#706]
### URL for the brand / site / app

https://forums.mydigitallife.net/

### Logo resources for the icon

https://forums.mydigitallife.net/img/logo.svg

### Anything else?

My Digital Life has 2FA and support Aegis
![Screenshot 2022-10-15 at 19-28-23 Two-Step Verification My Digital Life Forums](https://user-images.githubusercontent.com/94728369/195986371-a83f0f13-7129-482f-9f88-43e57298a85e.png)

Here is the link: https://forums.mydigitallife.net/account/two-step

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/My%20Digital%20Life%20Forums.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
