### ISSUE TITLE
Icon request: BreachForums

### ISSUE THREAD

**Issue by McRoyce** [krisu5/aegis-icons#707]
### URL for the brand / site / app

*Removed by maintainer (highly illegal activity)*

### Logo resources for the icon

*Removed by maintainer (raster image)*

### Anything else?

BreachForums has 2FA and support Aegis too

![Screenshot 2022-10-15 at 19-35-09 BreachForums - Two-factor authentication](https://user-images.githubusercontent.com/94728369/195986763-d459775c-ef14-4792-9f46-bddd674f1ee6.png)

Here is the link: *Removed by maintainer (highly illegal activity)*

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Rejected.

Breaks two icon acceptability criterias:

1. [Apps / sites focusing on highly immoral and illegal activity / material.](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#not-approved)
   - In this case: black hat hacking, malware, sharing hacked / leaked accounts etc.
2. [Not enough forum members for dedicated icon](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#case-by-case-basis).
