### ISSUE TITLE
Icon request: GameBanana

### ISSUE THREAD

**Issue by Shoptalky** [krisu5/aegis-icons#708]
### URL for the brand / site / app

https://gamebanana.com

### Anything else?

![image](https://user-images.githubusercontent.com/112514395/195990146-4fd644d6-26a8-4dd4-9054-c6fc781e0d53.png)

I found a raster image of the banana logo here: https://images.gamebanana.com/static/img/banana.png and their full logo here: https://images.gamebanana.com/static/img/logo.png as well as on their Twitter/Discord pages but I was unable to find a SVG file.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/GameBanana.svg

*(sorry if it looks bad, this is the best I could do with these logos)*



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
