### ISSUE TITLE
Icon request: Privacy Guides (forum)

### ISSUE THREAD

**Issue by McRoyce** [krisu5/aegis-icons#711]
### URL for the brand / site / app

https://discuss.privacyguides.org/

### Anything else?

This site support Aegis 2FA

![Screenshot 2022-10-16 at 17-19-52 Profile - McRoyce - Privacy Guides](https://user-images.githubusercontent.com/94728369/196030047-9162de59-5e73-4688-a2a6-41d0cf0f7fdf.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
[We only make icons for really popular forums](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#case-by-case-basis) (at least over 250,000 total members and high posting activity). This forum only has [185](https://discuss.privacyguides.org/about) members. For forums under the requirements, forum software related icons are the prefer solution.

Use one of the **Discourse** icons.
