### ISSUE TITLE
Icon request: IDCloudHost

### ISSUE THREAD

**Issue by eyurando** [krisu5/aegis-icons#712]
### URL for the brand / site / app

https://idcloudhost.com

### Logo resources for the icon

https://idcloudhost.com/en/en-about-press-release/

### Anything else?

For reference, they have tutorial to enable 2FA  [here](https://idcloudhost.com/panduan/verifikasi-2-langkah-pada-akun-idcloudhost/) (in Indonesian language)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/IDCloudHost.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
