### ISSUE TITLE
Icon request: Tom's Hardware (forum)

### ISSUE THREAD

**Issue by eyurando** [krisu5/aegis-icons#713]
### URL for the brand / site / app

https://forums.tomshardware.com/

### Logo resources for the icon

https://findvectorlogo.com/toms-hardware-vector-logo-svg/

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Tom's%20Hardware.svg


:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
