### ISSUE TITLE
Icon request: Back4App

### ISSUE THREAD

**Issue by eyurando** [krisu5/aegis-icons#714]
### URL for the brand / site / app

https://www.back4app.com/

### Logo resources for the icon

*Removed by maintainer (raster image, outdated logo)*

### Anything else?

2FA/MFA Reference : https://www.back4app.com/docs/security/multi-factor-authentication

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Back4App.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Back4App%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
