### ISSUE TITLE
Icon request: Travala.com

### ISSUE THREAD

**Issue by gilcn** [krisu5/aegis-icons#715]
### URL for the brand / site / app

https://www.travala.com/

### Logo resources for the icon

https://drive.google.com/drive/folders/1OtKia23_1_QOwFfckJbjer5nBxx08ypc

### Anything else?

Proof of 2FA: https://blog.travala.com/explaining-how-the-travala-wallet-functions/
See _"2. Set up Google 2 Factor Authentication (2FA)"_

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Travala.com.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
