### ISSUE TITLE
Icon request: Nash

### ISSUE THREAD

**Issue by gilcn** [krisu5/aegis-icons#716]
### URL for the brand / site / app

https://nash.io/

### Logo resources for the icon

https://nash.io/assets/svg/nash-logo.svg

### Anything else?

Proof of 2FA: https://support.nash.io/hc/en-us/sections/360005285194-Two-factor-authentication-2FA-

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Nash.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
