### ISSUE TITLE
Icon request: CrowdSec

### ISSUE THREAD

**Issue by markus-gitdev** [krisu5/aegis-icons#717]
### URL for the brand / site / app

https://www.crowdsec.net/

### Logo resources for the icon

https://github.com/crowdsecurity/crowdsec-docs/blob/main/crowdsec-docs/static/img/crowdsec_custom.svg

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Couldn't find anything related to 2FA inside of this service / site.

If you want this open again, either comment with:
- Link to documentation page related to 2FA
- Screenshot proof of the TOTP / Google Authenticator 2FA settings page (censor sensitive info if needed).

**Comment by markus-gitdev** [comment]
> Couldn't find anything related to 2FA inside of this service / site.
> 
> If you want this open again, either comment with:
> 
>     * Link to documentation page related to 2FA
> 
>     * Screenshot proof of the TOTP / Google Authenticator 2FA settings page (censor sensitive info if needed).

The [CrowdSec Console](https://app.crowdsec.net/) offers MFA:
![grafik](https://user-images.githubusercontent.com/82206269/196514665-6e9208f2-797d-49d2-965a-0e9de3bee911.png)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/CrowdSec.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
