### ISSUE TITLE
Icon request: Stripchat

### ISSUE THREAD

**Issue by EncryptCrystal** [krisu5/aegis-icons#718]
### URL for the brand / site / app

https://stripchat.com/ (NSFW)

### Logo resources for the icon

https://upload.wikimedia.org/wikipedia/commons/f/f9/Stripchat-logo.svg

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Stripchat.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
