### ISSUE TITLE
Icon request: AVG

### ISSUE THREAD

**Issue by McRoyce** [krisu5/aegis-icons#719]
### URL for the brand / site / app

https://www.avg.com/

### Logo resources for the icon

https://upload.wikimedia.org/wikipedia/commons/4/44/AVG_Similar_Icon.svg

### Anything else?

AVG has 2fa and support Aegis
![Screenshot 2022-10-21 at 06-55-27 Account settings](https://user-images.githubusercontent.com/94728369/197080902-65c31f7e-15cf-435f-abc0-ec3382298946.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/AVG.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
