### ISSUE TITLE
Icon request: 2Captcha

### ISSUE THREAD

**Issue by eyurando** [krisu5/aegis-icons#720]
### URL for the brand / site / app

https://2captcha.com/

### Logo resources for the icon

https://2captcha.com/dist/web/db378cecbb0bcf2ac47f4c67b84c01d9.svg

### Anything else?

![2captcha](https://user-images.githubusercontent.com/16876803/197115453-08ff45d0-e55a-41da-bdfb-233d8dbf0840.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/2Captcha.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
