### ISSUE TITLE
Icon request: SpigotMC (forum)

### ISSUE THREAD

**Issue by Vollorak** [krisu5/aegis-icons#724]
### URL for the brand / site / app

https://www.spigotmc.org/

### Logo resources for the icon

*Removed by maintainer (raster image)*

### Anything else?

Proof of 2FA:
<img width="596" alt="image" src="https://user-images.githubusercontent.com/76022196/197415537-a70313ce-700e-42dc-b8f3-fca792de9221.png">

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Rejected: no vectors or high quality raster images for logo available.

Use **XenForo** icon (forum software this forum uses) or generic **gaming** or **talk** icon.
