### ISSUE TITLE
Icon request: Neopets

### ISSUE THREAD

**Issue by Vollorak** [krisu5/aegis-icons#725]
### URL for the brand / site / app

https://www.neopets.com/

### Anything else?

Proof of 2FA:
<img width="410" alt="image" src="https://user-images.githubusercontent.com/76022196/197416481-7fb85570-8751-4b95-8caf-65e78cdca30a.png">

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/SVG/Neopets.svg
https://github.com/aegis-icons/aegis-icons/blob/master/SVG/.Variations/Neopets%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
