### ISSUE TITLE
Icon request: DedicatedMC

### ISSUE THREAD

**Issue by Vollorak** [krisu5/aegis-icons#726]
### URL for the brand / site / app

https://dedicatedmc.io/

### Logo resources for the icon

https://panel.dedicatedmc.io/assets/svgs/logo.svg

### Anything else?

Proof of 2FA:
<img width="263" alt="image" src="https://user-images.githubusercontent.com/76022196/197418854-71c4578b-3443-4b45-bd64-2d6af8811d3d.png">

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/DedicatedMC.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
