### ISSUE TITLE
Icon request: BuiltByBit (f.k.a. MC-Market)

### ISSUE THREAD

**Issue by Vollorak** [krisu5/aegis-icons#727]
### URL for the brand / site / app

https://builtbybit.com

### Logo resources for the icon

https://builtbybit.com/wiki/branding/

### Anything else?

Proof of 2FA:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/76022196/197421249-88478b5b-c3d0-4d28-8f76-20f465d19120.png">

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
We have the icon, but it was with the old name "MC-Market".

Renamed: https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/BuiltByBit.svg
