### ISSUE TITLE
Icon request: CyberPanel

### ISSUE THREAD

**Issue by eyurando** [krisu5/aegis-icons#728]
### URL for the brand / site / app

https://cyberpanel.net/

### Logo resources for the icon

https://cyberpanel.net/wp-content/uploads/2021/10/cyberpanel-temp-logo.svg (logo symbol is embedded raster graphic)

### Anything else?

2FA Reference: https://community.cyberpanel.net/docs?search=2fa&topic=130

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/CyberPanel.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
