### ISSUE TITLE
Icon request: HelpSpot

### ISSUE THREAD

**Issue by eyurando** [krisu5/aegis-icons#729]
### URL for the brand / site / app

https://www.helpspot.com/

### Logo resources for the icon

https://www.helpspot.com/img/helpspot-logo-color.svg

### Anything else?

2FA Reference: https://support.helpspot.com/index.php?pg=kb.page&id=649

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/HelpSpot.svg
https://github.com/aegis-icons/aegis-icons/blob/master/icons/2_Variations/HelpSpot%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
