### ISSUE TITLE
Icon request: NETdepot

### ISSUE THREAD

**Issue by eyurando** [krisu5/aegis-icons#730]
### URL for the brand / site / app

https://www.netdepot.com/

### Logo resources for the icon

https://octanecdn.com/netdepotcom/netdepotcom_427247565.svg

### Anything else?

Proof of 2FA:

![NETdepot](https://user-images.githubusercontent.com/16876803/197436321-3ace940f-156a-4bfa-8cda-399f27ec01e1.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/NETdepot.svg
https://github.com/aegis-icons/aegis-icons/blob/master/icons/2_Variations/NETdepot%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
