### ISSUE TITLE
Icon request: Gaia Online

### ISSUE THREAD

**Issue by Lonestarkiller6** [krisu5/aegis-icons#731]
### URL for the brand / site / app

https://www.gaiaonline.com

### Logo resources for the icon

https://upload.wikimedia.org/wikipedia/commons/8/84/Gaia_Online_logo.svg

### Anything else?

Proof of 2FA:

![2022-10-24 15_14_22-Settings](https://user-images.githubusercontent.com/76207732/197468667-d8f54163-4fce-49b0-9d0c-861e0c6cfc8f.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Gaia%20Online.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
