### ISSUE TITLE
Icon request: Grist

### ISSUE THREAD

**Issue by paulusversluis** [krisu5/aegis-icons#733]
### URL for the brand / site / app

https://www.getgrist.com/

### Logo resources for the icon

https://www.getgrist.com/wp-content/uploads/2021/07/logo-white.svg

### Anything else?

![image](https://user-images.githubusercontent.com/43139717/197799539-5fc72049-3cb8-4402-b1e2-53562b2e2fa9.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Grist.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
