### ISSUE TITLE
Icon request: Primobox

### ISSUE THREAD

**Issue by EncryptCrystal** [krisu5/aegis-icons#735]
### URL for the brand / site / app

https://www.primobox.com/en

### Logo resources for the icon

https://www.primobox.com/wp-content/uploads/2022/05/logo-bleu-primobox.svg

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Couldn't find anything related to 2FA inside of this service / site.

If you want this open again, either comment with:
- Link to documentation page related to 2FA **(prefered option)**
- Screenshot proof of the TOTP / Google Authenticator 2FA settings page (censor sensitive info if needed).

**Comment by EncryptCrystal** [comment]
![image](https://user-images.githubusercontent.com/52292872/198124544-ca5e239f-6b70-44f5-be19-f6a46c41d5b8.png)

The company's website is https://www.primobox.com/, but the site where to activate 2FA is : https://www.myprimobox.net/Coffre?request_locale=en#

If it is the second logo you want (MyPrimobox, the product, not Primobox, the company name): https://www.myprimobox.net/images/header/logo.svg

In addition, here is a screenshot of 2FA: 
![image](https://user-images.githubusercontent.com/52292872/198125265-69ec90df-75b2-4949-9f0a-7ae97e7580c9.png)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Primobox.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
