### ISSUE TITLE
Icon request: TotalEnergies

### ISSUE THREAD

**Issue by EncryptCrystal** [krisu5/aegis-icons#736]
### URL for the brand / site / app

https://www.totalenergies.fr/

### Logo resources for the icon

https://upload.wikimedia.org/wikipedia/fr/thumb/f/f7/Logo_TotalEnergies.svg/1139px-Logo_TotalEnergies.svg.png?20210529181740

### Anything else?

Dual authentication is offered for jobseeker accounts.  : https://careers.totalenergies.com/fr

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
Couldn't find anything related to 2FA inside of this service / site.

If you want this open again, either comment with:
- Link to documentation page related to 2FA
- Screenshot proof of the TOTP / Google Authenticator 2FA settings page (censor sensitive info if needed).

**Comment by EncryptCrystal** [comment]
I confirm that the recruitment site has a 2FA TOTP : 
![image](https://user-images.githubusercontent.com/52292872/199241052-06ecd359-0b23-44e7-8bab-95011b187d5b.png)

To access this page :  https://careers.totalenergies.com/en (It is the TotalEnergies recruitment site)
Then, "See our offer" leads to this page (with a strange URL) : 

![image](https://user-images.githubusercontent.com/52292872/199241743-50cec609-5d59-4cce-a627-de6ae58f15e1.png)

**Comment by krisu5** [comment]
Here you go!
https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/TotalEnergies.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
