### ISSUE TITLE
Icon request: Meister (MindMeister, MeisterTask, MeisterNote)

### ISSUE THREAD

**Issue by EncryptCrystal** [krisu5/aegis-icons#737]
### URL for the brand / site / app

~~https://www.mindmeister.com~~ https://www.meisterlabs.com/

### Logo resources for the icon

https://www.meisterlabs.com/press

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines).

**Comment by krisu5** [comment]
MindMeister is part of **Meister** master brand and account system, so I made icon for that instead

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Meister.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
