### ISSUE TITLE
Icon request: Todoist

### ISSUE THREAD

**Issue by richlawson** [krisu5/aegis-icons#739]
### URL for the brand / site / app

https://todoist.com/

### Logo resources for the icon

https://doist.com/press

### Proof of the Aegis-compatible 2FA

https://todoist.com/help/articles/how-to-enable-multi-factor-authentication

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Todoist.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
