### ISSUE TITLE
Icon request: The University of Chicago (UChicago)

### ISSUE THREAD

**Issue by Oaklight** [krisu5/aegis-icons#740]
### URL for the brand / site / app

https://www.uchicago.edu

### Logo resources for the icon

https://uchicago.app.box.com/s/9w9vxlocyv9msmz3vi867ma4cednz22k/file/793419057974

### Proof of the Aegis-compatible 2FA

University site for 2FA: https://cnet.uchicago.edu/2FA/index.htm

### Anything else?

use `duo-bypass` to enable other TOTP/HOTP authenticators: https://github.com/revalo/duo-bypass
I tried and it worked.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!
https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/The%20University%20of%20Chicago.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
