### ISSUE TITLE
Icon request: Huawei

### ISSUE THREAD

**Issue by Oaklight** [krisu5/aegis-icons#741]
### URL for the brand / site / app

https://www.huawei.com/

### Logo resources for the icon

https://upload.wikimedia.org/wikipedia/en/0/04/Huawei_Standard_logo.svg *(outdated)*

### Proof of the Aegis-compatible 2FA

- Huawei account is universal across its products, including mobile devices and cloud computing.
- Soft token is used by Huawei Cloud: https://support.huaweicloud.com/intl/en-us/usermanual-iam/iam_10_0002.html
- https://2fa.directory/int/

### Anything else?

Link above is the main brand svg logo. Here is the svg for Huawei Cloud: https://res-static.hc-cdn.cn/cloudbu-site/china/zh-cn/wangxue/header/logo.svg

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!
https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Huawei.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
