### ISSUE TITLE
Icon request: Mattermost

### ISSUE THREAD

**Issue by lauhayden** [krisu5/aegis-icons#742]
### URL for the brand / site / app

https://mattermost.com/

### Logo resources for the icon

https://mattermost.com/newsroom/#press-kit-section

### Proof of the Aegis-compatible 2FA

[Here is their documentation page on their "Multi-factor authentication" functionality.](https://docs.mattermost.com/onboard/multi-factor-authentication.html) It states that their MFA is implementation relies on TOTP.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!
https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Mattermost.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
