### ISSUE TITLE
Icon request: NamePros (forum)

### ISSUE THREAD

**Issue by eyurando** [krisu5/aegis-icons#743]
### URL for the brand / site / app

https://www.namepros.com/

### Logo resources for the icon

https://nameproscdn.com/styles/namepros/core/logo.svg

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Couldn't find anything related to 2FA inside of this service / site.

If you want this open again, either comment with:
- Link to documentation page related to 2FA **(prefered option)**
- Screenshot proof of the TOTP / Google Authenticator 2FA settings page (censor sensitive info if needed).

**Comment by eyurando** [comment]
Proof of TOTP 2FA:

![666b2130-ff3c-4526-9389-92620681c4fd](https://user-images.githubusercontent.com/16876803/198989597-0d2a5510-66af-4d23-8896-d87ee354657c.png)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/NamePros.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
