### ISSUE TITLE
Icon request: DomaiNesia

### ISSUE THREAD

**Issue by eyurando** [krisu5/aegis-icons#744]
### URL for the brand / site / app

https://www.domainesia.com/

### Logo resources for the icon

https://www.domainesia.com/media-kit/

### Proof of the Aegis-compatible 2FA

https://www.domainesia.com/panduan/cara-mengaktifkan-two-factor-authentication/

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/DomaiNesia.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
