### ISSUE TITLE
Icon request: WHMCS

### ISSUE THREAD

**Issue by eyurando** [krisu5/aegis-icons#745]
### URL for the brand / site / app

https://www.whmcs.com/

### Logo resources for the icon

https://seeklogo.com/vector-logo/424722/whmcs

### Proof of the Aegis-compatible 2FA

https://docs.whmcs.com/Two-Factor_Authentication

### Anything else?

Official [media resources](https://www.whmcs.com/media/) seems doesn't have vector image, so I use another resource.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/WHMCS.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
