### ISSUE TITLE
Icon request: Better Uptime

### ISSUE THREAD

**Issue by Otiel** [krisu5/aegis-icons#749]
### URL for the brand / site / app

https://betteruptime.com

### Logo resources for the icon

https://betterstack.com/packs/static/logo-b9bb2de68dce64823424.svg

### Proof of the Aegis-compatible 2FA

https://docs.betteruptime.com/team/account-settings/two-factor-authentication

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Better%20Uptime.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*

**Comment by Otiel** [comment]
Thank you! ❤️
