### ISSUE TITLE
Icon request: Moodle

### ISSUE THREAD

**Issue by slim8shady9** [krisu5/aegis-icons#750]
### URL for the brand / site / app

https://moodle.org/

### Proof of the Aegis-compatible 2FA

[https://moodle.org/plugins/tool_mfa](https://moodle.org/plugins/tool_mfa)
[https://github.com/catalyst/moodle-tool_mfa](https://github.com/catalyst/moodle-tool_mfa)

### Confirmation

- [x] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Moodle.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
