### ISSUE TITLE
Icon request: ComputerBase

### ISSUE THREAD

**Issue by steffenweber** [krisu5/aegis-icons#751]
### URL for the brand / site / app

https://www.computerbase.de/

### Logo resources for the icon

https://www.computerbase.de/img/icon-maskable.svg

### Proof of the Aegis-compatible 2FA

![Screenshot from 2022-11-07 22-27-32](https://user-images.githubusercontent.com/1138129/200419224-a11b08b9-71dc-4a57-beed-f7bcf89d7717.png)

### Anything else?

I'm the administrator of ComputerBase (german tech magazine with a big community, 27 million posts). Our login system is provided by XenForo which has a TOTP implementation that I've been using for several years with andOTP. It would be great to have our logo available in Aegis out of the box, too! :slightly_smiling_face: 

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/ComputerBase.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
