### ISSUE TITLE
Icon request: Postman

### ISSUE THREAD

**Issue by nikhilbadyal** [krisu5/aegis-icons#752]
### URL for the brand / site / app

https://www.postman.com/

### Logo resources for the icon

https://www.postman.com/company/press-media/

### Proof of the Aegis-compatible 2FA

<img width="491" alt="image" src="https://user-images.githubusercontent.com/59223300/201160254-3fc37228-efcc-4347-91d7-18b031b6a9cf.png">

MFA support is still in beta and they will be releasing it to the public soon as mentioned [here](https://github.com/postmanlabs/postman-app-support/issues/6452#issuecomment-1303828909). It'll be nice to have it as early addition. 

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Postman.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
