### ISSUE TITLE
Icon request: BookWyrm

### ISSUE THREAD

**Issue by drinkcoffee247** [krisu5/aegis-icons#753]
### URL for the brand / site / app

https://joinbookwyrm.com

### Proof of the Aegis-compatible 2FA

https://github.com/bookwyrm-social/bookwyrm/pull/2294

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Dropped.

1. No vectors and only low resolution raster images
2. Logo is too complex for monochrome treatment

After / during the [generic icons redesign](https://github.com/aegis-icons/aegis-icons/issues/722), I will make "books" icon as supplement.
