### ISSUE TITLE
Icon request: Bohemia Interactive

### ISSUE THREAD

**Issue by Dalgam** [krisu5/aegis-icons#754]
### URL for the brand / site / app

https://www.bohemia.net/

### Logo resources for the icon

https://data.bistudio.com/images/logos/Bohemia_Interactive_Logos.zip

### Proof of the Aegis-compatible 2FA

[Screenshot_2022-11-17-20-00-35-19_cbf47468f7ecfbd8ebcc46bf9cc626da](https://user-images.githubusercontent.com/7426323/202537069-961feac0-4a7e-4c5f-bd20-1506743d416d.jpg)
[Screenshot_2022-11-17-20-13-56-89_cbf47468f7ecfbd8ebcc46bf9cc626da](https://user-images.githubusercontent.com/7426323/202537775-afb2910c-5756-4cff-b292-4c7b51d317d5.jpg)

accounts.bistudio.com is their login and account portal.
The service can be found at 2FA Directory when searching for Bohemia 

### Anything else?

This pack with the Aegis app is a godsent to keep 2FA great and functional whilst still looking good. Great job!

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Bohemia%20Interactive.svg


:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*

**Comment by Dalgam** [comment]
Great stuff, thanks!
