### ISSUE TITLE
Icon request: Ko-fi

### ISSUE THREAD

**Issue by nichu42** [krisu5/aegis-icons#755]
### URL for the brand / site / app

https://ko-fi.com/

### Logo resources for the icon

https://more.ko-fi.com/brand-assets

### Proof of the Aegis-compatible 2FA

https://help.ko-fi.com/hc/en-us/articles/6355489342737-How-to-Set-Up-Two-Factor-Authentication-2FA-

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Ko-fi.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
