### ISSUE TITLE
Icon request: Warner Bros. Games

### ISSUE THREAD

**Issue by lunboks** [krisu5/aegis-icons#756]
### URL for the brand / site / app

https://warnerbrosgames.com/

### Logo resources for the icon

https://cdn.wbgames.com/static/wb-shield.svg

The color version of the logo in the top-left corner is also an (embedded) SVG file.

### Proof of the Aegis-compatible 2FA

![WB Games 2FA settings screenshot](https://user-images.githubusercontent.com/6715670/203340826-b0fdb5e7-3714-4f7d-964d-7d464020b169.png)

It's also listed on [2FA Directory](https://2fa.directory/int/).

### Anything else?

Thanks in advance on behalf of paranoid MultiVersus players :)

### Confirmation

- [x] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
> Thanks in advance on behalf of paranoid MultiVersus players :)

No problem :)

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Warner%20Bros.%20Games.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
