### ISSUE TITLE
Icon request: Teleport

### ISSUE THREAD

**Issue by TheBinaryLoop** [krisu5/aegis-icons#757]
### URL for the brand / site / app

https://goteleport.com/

### Proof of the Aegis-compatible 2FA

![image](https://user-images.githubusercontent.com/13447164/203540380-383e585a-6565-4905-9e3f-a00e9a2b88ad.png)

https://goteleport.com/blog/teleport-2.0-released/

### Anything else?

I can provide an SVG base64 string if that is wanted.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Teleport.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
