### ISSUE TITLE
Icon request: Wuxiaworld

### ISSUE THREAD

**Issue by RuthlessRuler** [krisu5/aegis-icons#758]
### URL for the brand / site / app

https://www.wuxiaworld.com/

### Proof of the Aegis-compatible 2FA

[Screenshot_2022-11-23-18-50-08-479_org mozilla firefox-01](https://user-images.githubusercontent.com/20885012/203557051-0f83abb3-bf85-4e3e-acdb-abc9ea9b4f09.jpeg)
[Screenshot_2022-11-23-18-41-36-226_org mozilla firefox-02](https://user-images.githubusercontent.com/20885012/203557061-536619fb-3632-480b-bc31-b98c581ae083.jpeg)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Wuxiaworld.svg
https://github.com/aegis-icons/aegis-icons/blob/master/icons/2_Variations/Wuxiaworld%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*

**Comment by RuthlessRuler** [comment]
> Here you go!
> 
> https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Wuxiaworld.svg https://github.com/aegis-icons/aegis-icons/blob/master/icons/2_Variations/Wuxiaworld%20bg.var.svg
> 
> ❓ _[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)_
> 
> ⭐ _Support this project by giving a star! Just adding like to this comment is also appreciated._

Thanks alot.
