### ISSUE TITLE
Icon request: Sorare

### ISSUE THREAD

**Issue by fiorins** [krisu5/aegis-icons#759]
### URL for the brand / site / app

https://sorare.com

### Logo resources for the icon

_Removed by maintainer (raster image)_

### Proof of the Aegis-compatible 2FA

https://help.sorare.com/hc/en-us/articles/4415614957841-How-do-I-set-up-two-factor-authentication-2FA-

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Sorare.svg
https://github.com/aegis-icons/aegis-icons/blob/master/icons/2_Variations/Sorare%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
