### ISSUE TITLE
Icon request: Hewlett Packard Enterprise (HPE)

### ISSUE THREAD

**Issue by Schwitzd** [krisu5/aegis-icons#760]
### URL for the brand / site / app

https://www.hpe.com/

### Logo resources for the icon

https://www.hpe.com/content/dam/hpe/newsroom/Media-Assets-Page/image-norend/hpe-logos.zip

### Proof of the Aegis-compatible 2FA

![mfa](https://user-images.githubusercontent.com/15292575/204228480-d254837b-f769-4c98-b353-559153568d7b.jpg)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Hewlett%20Packard%20Enterprise.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
