### ISSUE TITLE
Icon request: CurseForge

### ISSUE THREAD

**Issue by redfire75369** [krisu5/aegis-icons#761]
### URL for the brand / site / app

https://www.curseforge.com/

### Logo resources for the icon

https://www.curseforge.com/Content/2-0-8366-33007/Skins/CurseForge/images/anvil.svg

### Proof of the Aegis-compatible 2FA

Link: <https://2fa.curseforge.com>
It requires a logged in account though, so here's a picture after you set it up.
![image](https://user-images.githubusercontent.com/52237913/204483129-8cf54901-d270-41ce-b1d5-4fabd68992b1.png)

Screenshot of enabling page:
![image](https://user-images.githubusercontent.com/52237913/204484076-d57663c8-673d-4b40-87f3-817ff843d349.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/CurseForge.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
