### ISSUE TITLE
Icon request: VIPTel

### ISSUE THREAD

**Issue by ghost** [krisu5/aegis-icons#762]
### URL for the brand / site / app

https://www.viptel.sk/en/

### Logo resources for the icon

https://www.viptel.sk/templates/viptel/images/viptel-logo.svg

### Proof of the Aegis-compatible 2FA

![totp](https://user-images.githubusercontent.com/44501389/204827669-fba1c479-83ba-47b7-bddb-91c54e03c029.png)

TOTP support can also be checked on the **customer portal login page** which has an (initially hidden) TOTP input field with a tooltip referencing Google Authenticator:
  - open https://www.viptel.sk/customer/auth/sign/in
  - switch to English (country flag dropdown)
  - view page source
  - search for `2-step verification` string

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/VIPTel.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
