### ISSUE TITLE
Icon request: Buhl 

### ISSUE THREAD

**Issue by okunze** [krisu5/aegis-icons#763]
### URL for the brand / site / app

https://www.buhl.de/

### Logo resources for the icon

https://www.buhl.de/wp-content/themes/buhl-2021/img/icons/buhl_logo_weiss.svg

### Proof of the Aegis-compatible 2FA

A FAQ about 2FA can be found here (currently only in German):
https://www.buhl.de/shop/faqs?category=325

### Anything else?

The icon https://www.buhl.de/wp-content/themes/buhl-2021/img/icons/buhl_logo_weiss.svg is used on this page (at the very bottom on the left side):
https://www.buhl.de/

Alternatively, the icon https://www.buhl.de/presse/wp-content/uploads/sites/20/2019/01/buhl-footer-logo-w.svg from this page can be used (also at the very bottom of the left side):
https://www.buhl.de/presse/

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Buhl.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
