### ISSUE TITLE
Icon request: ImmoScout24

### ISSUE THREAD

**Issue by okunze** [krisu5/aegis-icons#764]
### URL for the brand / site / app

https://www.immobilienscout24.de/

### Logo resources for the icon

https://www.immobilienscout24.de/unternehmen/typo3conf/ext/sfsitepackage/Resources/Public/Images/immoscout24-white.svg

### Proof of the Aegis-compatible 2FA

A FAQ about 2FA can be found here (currently only in German):
https://sicherheit.immobilienscout24.de/2-faktor-authentifizierung.html

And here:
https://sicherheit.immobilienscout24.de/2-faktor-authentifizierung-suchende.html

### Anything else?

The icon https://www.immobilienscout24.de/unternehmen/typo3conf/ext/sfsitepackage/Resources/Public/Images/immoscout24-white.svg is used on this page (at the very bottom on the right side):
https://www.immobilienscout24.de/unternehmen/news-medien/medienkontakt/

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/ImmoScout24.svg
https://github.com/aegis-icons/aegis-icons/blob/master/icons/2_Variations/ImmoScout24%20fg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
