### ISSUE TITLE
Icon request: GNS3

### ISSUE THREAD

**Issue by juanico10** [krisu5/aegis-icons#765]
### URL for the brand / site / app

https://www.gns3.com/

### Logo resources for the icon

*Removed by maintainer (raster image)*

### Proof of the Aegis-compatible 2FA

https://www.gns3.com/gns3-community-release-notes

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Couldn't find anything related to 2FA inside of this service / site.

If you want this open again, either comment with:
- Link to documentation page related to 2FA **(prefered option)**
- Screenshot proof of the TOTP / Google Authenticator 2FA settings page (censor sensitive info if needed).

**Comment by juanico10** [comment]
Hellos,

I found this on the web blog.
https://www.gns3.com/gns3-community-release-notes

Let me know if you need anything else.
Best regards.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/GNS3.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
