### ISSUE TITLE
Icon request: Gosuslugi (Госуслуги)

### ISSUE THREAD

**Issue by Sunsper** [krisu5/aegis-icons#767]
### URL for the brand / site / app

https://www.gosuslugi.ru/

### Logo resources for the icon

https://www.figma.com/file/lyIduPvpgl3wbzuuMFcwL8/Cardbox-UI-Design-Kit

### Proof of the Aegis-compatible 2FA

Since I completely understand this is going to be nearly impossible to proof 2FA compatibility of the website in question without having an account there (which I'm almost certain requires citizenship of Russian Federation or some sort of document that grants at least a temporary right to stay in Russia), I'm providing a screenshot I made while logged into my account:

![firefox_paT8yakq1w](https://user-images.githubusercontent.com/75447034/205426948-6abf05f4-1a8a-4c62-8c04-7a507d9527b0.png)

I highlighted the option to configure 2FA through TOTP token – this feature has been finally added recently.
I already set up 2FA here with Aegis – it works.

Also, here's an article in the Help section of the website which also highlights 2FA functionality:
https://www.gosuslugi.ru/help/faq/lk_security/102522
(The article is in Russian and **DOES NOT** have an English version, unfortunately)

### Anything else?

I provided the link to a file on Figma which contains the Gosuslugi logo. I hope it'll be of any use, since I wasn't able to find any press kit or whatever.

Also, #StandWithUkraine 🇺🇦
The war must be stopped and Ukrainian territories (including the Republic of Crimea) must be freed from Russian Military Forces.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Gosuslugi.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
