### ISSUE TITLE
Icon request: Auth0

### ISSUE THREAD

**Issue by theS1LV3R** [krisu5/aegis-icons#768]
### URL for the brand / site / app

https://auth0.com

### Logo resources for the icon

*Removed by maintainer (outdated branding)*

### Proof of the Aegis-compatible 2FA

https://auth0.com/docs/secure/multi-factor-authentication

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Auth0.svg
https://github.com/aegis-icons/aegis-icons/blob/master/icons/2_Variations/Auth0%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
