### ISSUE TITLE
Icon request: Cardmarket

### ISSUE THREAD

**Issue by citizen-17** [krisu5/aegis-icons#769]
### URL for the brand / site / app

https://www.cardmarket.com

### Proof of the Aegis-compatible 2FA

![grafik](https://user-images.githubusercontent.com/78883884/206153286-ff1b6f87-c27c-4add-a241-b4c861dde76c.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Cardmarket.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
