### ISSUE TITLE
Icon request: Topicbox

### ISSUE THREAD

**Issue by fxbrit** [krisu5/aegis-icons#770]
### URL for the brand / site / app

https://www.topicbox.com/

### Logo resources for the icon

https://www.topicbox.com/press#logo

### Proof of the Aegis-compatible 2FA

https://www.topicbox.help/hc/en-us/articles/360053598394-Two-step-verification-2FA-

### Anything else?

Most notably used by Thunderbid: https://thunderbird.topicbox.com/latest

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Topicbox.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*

**Comment by fxbrit** [comment]
amazing, many thanks for your work :-)
