### ISSUE TITLE
Icon request: Public Transport Victoria (PTV)

### ISSUE THREAD

**Issue by Cautious-Software701** [krisu5/aegis-icons#772]
### URL for the brand / site / app

https://www.ptv.vic.gov.au

### Logo resources for the icon

https://www.ptv.vic.gov.au/resources/themes/ptv-mpw/public/images/logo.svg

### Proof of the Aegis-compatible 2FA

https://www.ptv.vic.gov.au/footer/about-ptv/digital-tools/mobile-apps/mfa/

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Public%20Transport%20Victoria.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
