### ISSUE TITLE
Icon request: Barmenia

### ISSUE THREAD

**Issue by scurfin** [krisu5/aegis-icons#776]
### URL for the brand / site / app

https://barmenia.de/

### Logo resources for the icon

*Removed by maintainer (outdated branding)*

### Proof of the Aegis-compatible 2FA

[Link to FAQ for TOTP](https://suche.barmenia.de/faqs.html?prd=Nutzen%2BSie%2Bdie%2Bdas%2BOnline%2BKundencenter%2Bals%2BApp%2Boder%2Bals%2BWebversion.%2B&dom=barmenia.de&p0=334300&referrerPageUrl=https%3A%2F%2Fwww.barmenia.de%2Fdeu%2Fbde_privat%2Fbde_service%2Fbde_selfservice%2Fbde_meine_barmenia%2Fuebersicht.xhtml&query=totp&context=%7B%22adm%22%3Anull%7D&tabOrder=.%2Findex.html%2Cproducts%2Cfaqs%2Clinks%2Clocations&facetFilters=%7B%7D&filters=%7B%7D)

### Anything else?

Barmenia itself uses as icon for apps or favicon only the big B as logo (blue on white or white on blue).

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Barmenia.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
