### ISSUE TITLE
Icon request: Prusa (Printables.com)

### ISSUE THREAD

**Issue by scurfin** [krisu5/aegis-icons#777]
### URL for the brand / site / app

https://prusa3d.com/

### Logo resources for the icon

https://www.prusa3d.com/page/media-assets_987/

### Proof of the Aegis-compatible 2FA

[PrusaAccount 2-step Verification](https://help.prusa3d.com/article/prusaaccount-2-step-verification_230402)

### Anything else?

Account is also required for Printables.com

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Prusa.svg
https://github.com/aegis-icons/aegis-icons/blob/master/icons/2_Variations/Prusa%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
