### ISSUE TITLE
Icon request: Systemli

### ISSUE THREAD

**Issue by BlitDev** [krisu5/aegis-icons#779]
### URL for the brand / site / app

https://www.systemli.org/en/

### Logo resources for the icon

*Removed by maintainer (raster image)*

### Proof of the Aegis-compatible 2FA

![2022-12-15_20-09](https://user-images.githubusercontent.com/79034202/207867518-6d282660-4373-4b7e-b908-a4ed4afaadce.png)

### Anything else?

Systemli requires an invitation code to register, so I don't know if you can check that.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Please post screenshot of the "configure two-factor authentication" page **(censor sensitive information)**, current screenshot doesn't tell me that this has TOTP / app based 2FA (there can be several different options for 2FA or no TOTP at all) and I couldn't find the answer from Google.

**Comment by BlitDev** [comment]
> Please post screenshot of the "configure two-factor authentication" page **(censor sensitive information)**, current screenshot doesn't tell me that this has TOTP / app based 2FA (there can be several different options for 2FA or no TOTP at all) and I couldn't find the answer from Google.

![image](https://user-images.githubusercontent.com/79034202/208085449-f6808f72-713d-44a3-af74-9cb70c6eef24.png)
I'm already using two-factor authentication, so I can't provide much more.

**Comment by krisu5** [comment]
The information on the right side of page confirms that this has TOTP, thank you.

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Systemli.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
