### ISSUE TITLE
Icon request: IGN

### ISSUE THREAD

**Issue by sanatsathaye** [krisu5/aegis-icons#781]
### URL for the brand / site / app

https://www.ign.com/

### Logo resources for the icon

*Removed by maintainer (SVG code)*

### Proof of the Aegis-compatible 2FA

![image](https://user-images.githubusercontent.com/15162329/208303417-c5e1d846-766e-4fc8-8bda-6f8e0698d306.png)

### Anything else?

Had to get svg using inspect element, hope I did correctly... added "xmlns" in svg tag to make it viewable in browser.

▲ **Maintainer note:** don't add SVG code, it's forbidden in the issue form.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by sanatsathaye** [comment]
[IGN logo SVG](https://user-images.githubusercontent.com/15162329/208303716-26a6d971-89d2-4ed1-9b6d-a0923c4ba3d5.svg)

Attached IGN svg, doesn't look like the code has rendered correctly

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/IGN.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
