### ISSUE TITLE
Icon request: Luogu (洛谷)

### ISSUE THREAD

**Issue by dsy4567** [krisu5/aegis-icons#782]
### URL for the brand / site / app

http://luogu.com.cn/

### Proof of the Aegis-compatible 2FA

https://www.luogu.com.cn/user/setting#security

![image](https://user-images.githubusercontent.com/84607814/208725779-efa1cb96-abd3-4f27-8dc2-234e0d7dab6f.png)

![image](https://user-images.githubusercontent.com/84607814/208726380-57743488-8925-4910-93f1-5f963d826418.png)

### Confirmation

- [x] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

---

**Maintainer notes:**

Luogu is "chinese competitive programming contest website", like [Codeforces](https://en.wikipedia.org/wiki/Codeforces).

Source: https://codeforces.com/blog/entry/103454

*Double-checked having TOTP by registering dummy account*.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Luogu.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
