### ISSUE TITLE
Icon request: Linux Professional Institute (LPI) (forum)

### ISSUE THREAD

**Issue by mhalano** [krisu5/aegis-icons#784]
### URL for the brand / site / app

https://lpi.org

### Logo resources for the icon

I found this one, but it should be converted and cropped to a circle. *Removed by maintainer (raster image)*

### Proof of the Aegis-compatible 2FA

The 2FA is used here: https://discuss.lpi.org/. Here is a site that catalogs 2FA compatible websites and here is the link for the LPI entry: https://github.com/2factorauth/twofactorauth/blob/master/entries/l/lpi.org.json

### Anything else?

I'm sending an email to LPI to check if they have any kind of press media kit.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
> Here is a site that catalogs 2FA compatible websites and here is the link for the LPI entry: https://github.com/2factorauth/twofactorauth/blob/master/entries/l/lpi.org.json

This entry doesn't state that this has TOTP, [see example entry that has it](https://github.com/2factorauth/twofactorauth/blob/master/entries/f/facebook.com.json) (`tfa`).

**Comment by mhalano** [comment]
You are right. I checked and 2FA is just for the discourse forum, discuss.lpi.org. Here is the screen where I type the OTP code:
![image](https://user-images.githubusercontent.com/6025031/209332483-2053538a-2185-482c-a506-e0db8b453537.png)

**Comment by krisu5** [comment]
_Created forum account to see user amount._

[We only make icons for really popular forums](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#case-by-case-basis) (at least over 250,000 total members and high posting activity). This forum only has [188](https://discuss.lpi.org/u) members. For forums under the requirements, forum software related icons are the prefer solution.

Use one of the **Discourse** icons (the forum software) or generic **Talk** icon instead.
