### ISSUE TITLE
Icon request: DNSimple

### ISSUE THREAD

**Issue by Soitora** [krisu5/aegis-icons#785]
### URL for the brand / site / app

https://dnsimple.com/

### Logo resources for the icon

https://dnsimple.com/logos

### Proof of the Aegis-compatible 2FA

https://support.dnsimple.com/articles/multi-factor-authentication/

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/DNSimple.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
