### ISSUE TITLE
Icon request: Real-Debrid

### ISSUE THREAD

**Issue by Jonas1312** [krisu5/aegis-icons#786]
### URL for the brand / site / app

https://real-debrid.com/

### Logo resources for the icon

https://fcdn.real-debrid.com/0819/favicons/safari-pinned-tab.svg

### Proof of the Aegis-compatible 2FA

![Screenshot 2022-12-25 at 13-40-34 Real-Debrid All-in-one solution](https://user-images.githubusercontent.com/15847892/209468242-ccf92f7b-e468-4e07-acb9-10d9a6496471.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Real-Debrid.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*

**Comment by Jonas1312** [comment]
Thanks a lot!
