### ISSUE TITLE
Icon request: Uphold

### ISSUE THREAD

**Issue by lcsvcn** [krisu5/aegis-icons#789]
### URL for the brand / site / app

https://uphold.com/

### Logo resources for the icon

https://seeklogo.com/vector-logo/408763/uphold

### Proof of the Aegis-compatible 2FA

https://support.uphold.com/hc/en-us/sections/360008206291-2-factor-authentication

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Already exists in the pack: https://aegis-icons.github.io/icons/primary/Uphold.svg
