### ISSUE TITLE
Icon request: Husky

### ISSUE THREAD

**Issue by lcsvcn** [krisu5/aegis-icons#790]
### URL for the brand / site / app

https://www.husky.io/

### Logo resources for the icon

https://uploads-ssl.webflow.com/62cc74ca475d041718de7fc2/62cc74ca475d041923de7ff4_husky-horizontal-logo.svg

### Proof of the Aegis-compatible 2FA

https://help.husky.io/pt-BR/articles/5979491-o-que-e-e-como-funciona-a-autenticacao-em-dois-fatores

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Filled by #791:

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Husky.svg
