### ISSUE TITLE
Icon request: CAPCOM ID

### ISSUE THREAD

**Issue by fufuakuseru** [krisu5/aegis-icons#792]
### URL for the brand / site / app

https://cid.capcom.com/en/

### Logo resources for the icon

https://github.com/detain/svg-logos/blob/master/svg/capcom-logo-1-.svg

**Maintainer note:** SVG for CAPCOM ID https://cid.capcom.com/assets/img/top/cid_logo.svg

### Proof of the Aegis-compatible 2FA

The _Two-Factor Authentication_ section on the support page: [https://cid.capcom.com/en/support/](https://cid.capcom.com/en/support/)

### Anything else?

The logo resource provided in this issue is the general Capcom logo which would be more recognizable though there is also a specific _Capcom ID_ logo which I wasn't able to find in SVG form but is used on the website's header and throughout that branch of Capcom's services.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/CAPCOM%20ID.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
