### ISSUE TITLE
Icon request: Guru.com

### ISSUE THREAD

**Issue by alexanderadam** [krisu5/aegis-icons#793]
### URL for the brand / site / app

https://www.guru.com/

### Logo resources for the icon

https://upload.wikimedia.org/wikipedia/commons/2/23/Guru_logo.svg

### Proof of the Aegis-compatible 2FA

![screenshot of TOTP screen at guru.com](https://user-images.githubusercontent.com/372620/210059812-78fa0f81-2f6e-418c-8bba-cb4c31081798.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Guru.com.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
