### ISSUE TITLE
Icon request: paste.gg

### ISSUE THREAD

**Issue by redfire75369** [krisu5/aegis-icons#794]
### URL for the brand / site / app

https://paste.gg

### Logo resources for the icon

https://paste.gg/static/svg/icons.svg#paste

### Proof of the Aegis-compatible 2FA

Link: https://paste.gg/account/2fa
Logged in account is required so here's an image.
![image](https://user-images.githubusercontent.com/52237913/210091116-a5979cc4-30d1-436b-a15f-9d10456fffa2.png)

### Anything else?

This is an instance of the open-source [paste](https://github.com/ascclemens/paste) hosted by the author. It can also be self-hosted, so this logo can be used for other such instances. It meets the 500 star criteria that shows it is widely used.

Although the svg is available, the logo is the svg symbol with id `paste`, which is embedded within it, and would need to be extracted.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/paste.gg.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
