### ISSUE TITLE
Icon submission: Optery

### ISSUE THREAD

**Issue by pvstyps** [krisu5/aegis-icons#795]
### URL of the site or app

https://www.optery.com/

### Proof of the Aegis-compatible 2FA

https://help.optery.com/en/article/how-to-add-multi-factor-authentication-mfa-2-step-verification-2fa-to-your-account-for-additional-security-e16sz4/

![Optery2FA](https://user-images.githubusercontent.com/121651925/210122828-df763977-105a-4566-ad25-aafde11f239b.jpg)

### Logo / icon info

https://www.optery.com/wp-content/uploads/2022/09/optery-logo-3.svg (I saved this SVG directly and used the shield in my design.)

I followed all of the instructions very carefully. However, this is my first time submitting and I apologize as I had an issue at the "combine logo" stage. In Affinity Designer, when I selected "Layer > Geometry > Add" my whole logo simply turned one color and I couldn't figure out how to get it to work the right way. Everything else should be correct. I would be happy to make the proper adjustment with some guidance from you, unless this submission is still acceptable.

### Background color info

The logo is blue and white, and I simply reversed the two colors so the background would be blue.

### Upload icon(s)

[optery.zip](https://github.com/aegis-icons/aegis-icons/files/10326763/optery.zip)

### Anything else?

Thank you for maintaining Aegis Icons! I've been loving it for a long time now.

### Confirmation

- [X] I have **read and carefully followed** [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) during the creation of the icon.

**Comment by krisu5** [comment]
Weird bug, that it taken 4 days for GitHub to show this issue on the repo and no notification... That was the reason for late response. 😅

I check this on friday / this weekend.

It's ok if you couldn't do some of the parts this time, I will fix them.

> Thank you for maintaining Aegis Icons! I've been loving it for a long time now.

Thank you :)

**Comment by krisu5** [comment]
Added to the repo with necessary fixes and smaller logo size:

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Optery.svg
