### ISSUE TITLE
Icon request: Restream

### ISSUE THREAD

**Issue by Lonestarkiller6** [krisu5/aegis-icons#797]
### URL for the brand / site / app

https://restream.io/

### Logo resources for the icon

https://restre.am/media-kit

### Proof of the Aegis-compatible 2FA

https://support.restream.io/en/articles/870429-two-factor-authentication

![2023-01-03 19_33_52-Settings - Restream](https://user-images.githubusercontent.com/76207732/210349718-30e56468-a1b6-43a6-8ec4-18447cead375.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Restream.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
