### ISSUE TITLE
Icon request: JFrog

### ISSUE THREAD

**Issue by tlusk** [krisu5/aegis-icons#798]
### URL for the brand / site / app

https://www.jfrog.com/

### Logo resources for the icon

https://jfrog.com/brand-guidelines/

### Proof of the Aegis-compatible 2FA

https://www.jfrog.com/confluence/display/JFROG/Logging+in+using+Multi-factor+Authentication

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/JFrog.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
