### ISSUE TITLE
Icon request: Teamup Calendar

### ISSUE THREAD

**Issue by ethyoo** [krisu5/aegis-icons#799]
### URL for the brand / site / app

https://www.teamup.com/

### Logo resources for the icon

https://commons.wikimedia.org/wiki/File:Teamup_Logo.svg

### Proof of the Aegis-compatible 2FA

https://calendar.teamup.com/kb/two-factor-authentication/

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Teamup%20Calendar.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
