### ISSUE TITLE
Icon request: Kinguin

### ISSUE THREAD

**Issue by ThunderF0x** [krisu5/aegis-icons#801]
### URL for the brand / site / app

https://www.kinguin.net/

### Proof of the Aegis-compatible 2FA

![kinguin2fa](https://user-images.githubusercontent.com/122406330/211667766-6876c7f5-6808-4635-99cd-6fa68160b205.JPG)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Kinguin.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
