### ISSUE TITLE
Icon submission: Ubiquiti (update)

### ISSUE THREAD

**Issue by justsomemate** [krisu5/aegis-icons#802]
### URL of the site or app

https://ui.com

### Proof of the Aegis-compatible 2FA

https://help.ui.com/hc/en-us/articles/115012986607-How-to-Enable-Disable-Multi-factor-Authentication-MFA-

### Logo / icon info

https://ui.com/microsite/ui-logo.svg

### Background color info

Background color is from the logo (`#006fff`) (the logo uses a gradient; this is the first of the two colors in the gradient and is the same as the primary button color on the web page) 

### Upload icon(s)

[Ubiquiti.zip](https://github.com/aegis-icons/aegis-icons/files/10389323/Ubiquiti.zip)

### Anything else?

Ubiquiti updated their logo on January 3 with a simpler design.
The logo is shifted slightly down from "center" to hopefully be visually centered.

### Confirmation

- [X] I have **read and carefully followed** [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) during the creation of the icon.

**Comment by krisu5** [comment]
Thanks, I check this later this week.

>  The logo is shifted slightly down from "center" to hopefully be visually centered.

I change it if needed.

**Comment by krisu5** [comment]
Added to the repo.

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Ubiquiti.svg
