### ISSUE TITLE
Icon request: YouHodler

### ISSUE THREAD

**Issue by CodeShakingSheep** [krisu5/aegis-icons#803]
### URL for the brand / site / app

https://www.youhodler.com/

### Logo resources for the icon

https://www.youhodler.com/company (scroll down to "Media Kit" section)

### Proof of the Aegis-compatible 2FA

https://help.youhodler.com/en/articles/3760592-how-to-enable-google-two-factor-authentication

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/YouHodler.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
