### ISSUE TITLE
Icon request: hi

### ISSUE THREAD

**Issue by CodeShakingSheep** [krisu5/aegis-icons#804]
### URL for the brand / site / app

https://hi.com/

### Proof of the Aegis-compatible 2FA

https://resources.hi.com/better-security-with-2fa/

### Anything else?

SVG logo is embedded as inline on the homepage.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/hi.svg
https://github.com/aegis-icons/aegis-icons/blob/master/icons/2_Variations/hi%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
