### ISSUE TITLE
Icon request: Storj

### ISSUE THREAD

**Issue by Ali-Khani-789** [krisu5/aegis-icons#807]
### URL for the brand / site / app

https://www.storj.io/

### Logo resources for the icon

https://www.storj.io/media-kit

### Proof of the Aegis-compatible 2FA

https://docs.storj.io/dcs/getting-started/satellite-developer-account/my-account#RaBCe

### Anything else?

The link for logo resources is a page from the official website of this service, which has information such as the types of icons and color codes used.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Storj.svg


:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
