### ISSUE TITLE
Icon request: Tolgee

### ISSUE THREAD

**Issue by SteffoSpieler** [krisu5/aegis-icons#808]
### URL for the brand / site / app

https://tolgee.io/

### Logo resources for the icon

https://tolgee.io/img/tolgeeLogo.svg

### Proof of the Aegis-compatible 2FA

![grafik](https://user-images.githubusercontent.com/41108856/212854330-db2bebb4-1ce7-4d38-b4e9-b89e751759b8.png)

(Sadly I can't find any documentation online about that, but if you want, here's the directory with the user settings. There are Multi-Factor-Auth (Mfa) files)
https://github.com/tolgee/tolgee-platform/tree/main/webapp/src/views/userSettings/accountSecurity

### Anything else?

I really hope this is enough as I can't find any mention of tolgee and 2fa on the internet...

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Tolgee.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
