### ISSUE TITLE
Icon request: ClearScore

### ISSUE THREAD

**Issue by simonhollingshead** [krisu5/aegis-icons#810]
### URL for the brand / site / app

https://www.clearscore.com/

### Proof of the Aegis-compatible 2FA

https://help.clearscore.com/hc/en-us/articles/360011249579-How-do-I-enable-disable-Two-Factor-Authentication-2FA-

### Anything else?

Inside their webpack (webpack://global-website/node_modules/@clearscore/) are directories for rainbow.icons.clearscore, rainbow.icons.clearscore-logo-symbol and rainbow.icons.clearscore-logo-wordmark, each exporting SVGs.  These generate the parts of the icon in the top left of the screen.  The logomark alone is probably good.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/ClearScore.svg
https://github.com/aegis-icons/aegis-icons/blob/master/icons/2_Variations/ClearScore%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
