### ISSUE TITLE
Icon request: phpMyAdmin

### ISSUE THREAD

**Issue by ernolf** [krisu5/aegis-icons#811]
### URL for the brand / site / app

https://www.phpmyadmin.net/

### Logo resources for the icon

https://github.com/phpmyadmin/data/tree/master/pma_logo_legacy/logo

### Proof of the Aegis-compatible 2FA

Described in [Documentation](https://docs.phpmyadmin.net/en/latest/two_factor.html#authentication-application-2fa)

Screenshot from my Installation
![image](https://user-images.githubusercontent.com/39901936/213597486-78933587-ae8e-428e-8fb6-9791cf60bda0.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/phpMyAdmin.svg


:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
