### ISSUE TITLE
Icon request: Masterworks

### ISSUE THREAD

**Issue by simonhollingshead** [krisu5/aegis-icons#813]
### URL for the brand / site / app

https://www.masterworks.com

### Logo resources for the icon

https://www.masterworks.com/about/press

### Proof of the Aegis-compatible 2FA

Amazingly there's no documentation saying this can be done, and the setup page has two placeholder strings where the 2FA app names are supposed to be, but it works - you go to SMS 2FA and then at the bottom click "want to use an authenticator app instead?"

![2fa_masterworks](https://user-images.githubusercontent.com/3343403/213883973-9efc3c16-a72c-4778-84f6-b7d88ffc62ec.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Masterworks.svg
https://github.com/aegis-icons/aegis-icons/blob/master/icons/2_Variations/Masterworks%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
