### ISSUE TITLE
Icon request: Second Life

### ISSUE THREAD

**Issue by simonhollingshead** [krisu5/aegis-icons#815]
### URL for the brand / site / app

https://secondlife.com/

### Logo resources for the icon

https://assets-global.website-files.com/60a83025d932b623a6a61ff8/62d1b099e69c5c3ac00656ba_SL-Logo-Horizontal-white.svg (It's the icon in the top corner of their webpage)

### Proof of the Aegis-compatible 2FA

https://community.secondlife.com/knowledgebase/english/password-and-account-information-r2/#Section__5_1_1

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Second%20Life.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
