### ISSUE TITLE
Icon request: AOL

### ISSUE THREAD

**Issue by simonhollingshead** [krisu5/aegis-icons#816]
### URL for the brand / site / app

https://aol.com

### Logo resources for the icon

https://s.yimg.com/cv/apiv2/default/20190830/aol-logo.svg (icon in top corner of website)

### Proof of the Aegis-compatible 2FA

https://help.aol.com/articles/2-step-verification-stronger-than-your-password-alone

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/AOL.svg
https://github.com/aegis-icons/aegis-icons/blob/master/icons/2_Variations/AOL%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
