### ISSUE TITLE
Update icon: Gmail

### ISSUE THREAD

**Issue by Sami32** [krisu5/aegis-icons#817]
### URL for the brand / site / app

https://gmail.com

### Reason for update

New logo

### Logo resources for the icon

https://upload.wikimedia.org/wikipedia/commons/7/7e/Gmail_icon_%282020%29.svg

### Anything else?

Official Google logos:
https://about.google/brand-resource-center/logos-list/

Because it seem that only the generic email icon is provided by default in Aegis.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Similar issue: #645.

Gmail is sub-brand of Google and Gmail uses Google accounts.

Use **Google** icon.

P.S. This shouldn't be "update" issue, it's "new icon" issue.

**Comment by Sami32** [comment]
Ok but i will still use the Gmail logo though ;)

P.S. I wasn't aware of the default "email" icon not being considered as an icon. Thanks.
