### ISSUE TITLE
Icon request: mail.com

### ISSUE THREAD

**Issue by 3xploiton3** [krisu5/aegis-icons#818]
### URL for the brand / site / app

https://www.mail.com/

### Logo resources for the icon

*Removed by maintainer (raster image, ICO)*

### Proof of the Aegis-compatible 2FA

https://support.mail.com/security/2fa/about-twofactor.html

### Anything else?

https://play-lh.googleusercontent.com/0iZnDRkCMzcK6ZxLbg83jSlR_GZHLCPc32sfNt01lfMRUqnOyKW9qKE_-64YnSpq3A

email.com
or
mail.com

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/mail.com.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
