### ISSUE TITLE
Icon request: Bitbuy

### ISSUE THREAD

**Issue by RobK88** [krisu5/aegis-icons#820]
### URL for the brand / site / app

https://www.bitbuy.ca

### Logo resources for the icon

https://bitbuy.ca/media

### Proof of the Aegis-compatible 2FA

See
How do I enable Google Authenticator or Authy? 

https://support.bitbuy.ca/hc/en-us/articles/360059151172-How-do-I-enable-Google-Authenticator-or-Authy-

### Anything else?

I have successfully added the Bitbuy 2FA token to Aegis.  I just need the icon!

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Bitbuy.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*

**Comment by RobK88** [comment]
Many many thanks for the icon for Bitbuy!

Rob
________________________________
