### ISSUE TITLE
Icon Request: Birdie

### ISSUE THREAD

**Issue by jensz12** [krisu5/aegis-icons#821]
### URL for the brand / site / app

https://www.birdie.so/

### Logo resources for the icon

https://uploads-ssl.webflow.com/63568f58066d30e2a58c8025/63723e5b389c7a9ea8a36dcd_Logotype-White.svg

### Proof of the Aegis-compatible 2FA

[Screenshot_20230127-000319](https://user-images.githubusercontent.com/1682377/214970244-04445853-4c6b-4baa-b02f-e8043d90cdd8.png)
 

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Birdie.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
