### ISSUE TITLE
Icon request: Pushover

### ISSUE THREAD

**Issue by okunze** [krisu5/aegis-icons#822]
### URL for the brand / site / app

https://pushover.net/

### Logo resources for the icon

https://www.svgrepo.com/svg/331554/pushover

### Proof of the Aegis-compatible 2FA

A FAQ about 2FA can be found here:
https://support.pushover.net/i49-how-can-i-enable-two-factor-authentication-2fa-on-my-account

### Anything else?

Pushover Logos and Usage can be found here (currently no SVG):
https://support.pushover.net/i63-pushover-logos-and-usage

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Already exists. The logo resource you linked is icon originally taken from aegis-icons. Please use search on our [website](https://aegis-icons.github.io/) before submitting any issues.
