### ISSUE TITLE
Icon request: LOBSTR

### ISSUE THREAD

**Issue by manquetin** [krisu5/aegis-icons#823]
### URL for the brand / site / app

https://lobstr.co/

### Proof of the Aegis-compatible 2FA

https://lobstr.freshdesk.com/support/solutions/articles/151000001324-secure-your-account-with-two-factor-authentication-2fa-setup-instructions-

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/LOBSTR.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
