### ISSUE TITLE
Icon request: Coinhako

### ISSUE THREAD

**Issue by Lonestarkiller6** [krisu5/aegis-icons#825]
### URL for the brand / site / app

https://www.coinhako.com/

### Logo resources for the icon

https://github.com/2fasvg/2fasvg.github.io/raw/master/assets/img/logo/coinhako.com/coinhako.com.svg

### Proof of the Aegis-compatible 2FA

https://help.coinhako.com/portal/en/kb/articles/setting-up-2fa-on-coinhako

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Coinhako.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
