### ISSUE TITLE
Icon request: SeatGeek

### ISSUE THREAD

**Issue by lordoftheoats** [krisu5/aegis-icons#826]
### URL for the brand / site / app

https://seatgeek.com/

### Logo resources for the icon

https://seatgeek.com/press

### Proof of the Aegis-compatible 2FA

[2FA Support Document from SeatGeek](https://support.seatgeek.com/hc/en-us/articles/360007288013-What-is-two-factor-authentication-)

### Anything else?

Frequently alternate between both a positive version of the logo and a reversed version on black, as seen in the linked brand guide. Thank you!

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/SeatGeek.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*

**Comment by lordoftheoats** [comment]
Thank you!
