### ISSUE TITLE
Icon request: Gusto

### ISSUE THREAD

**Issue by jvanderen1** [krisu5/aegis-icons#827]
### URL for the brand / site / app

https://gusto.com/

### Logo resources for the icon

https://www.dropbox.com/s/7su8t41u8q0sfo1/20190726_Gusto%20Logos.zip?dl=0 (from: https://gusto.com/partner-resources/branding-style-guide)

### Proof of the Aegis-compatible 2FA

2FA Documentation: https://support.gusto.com/article/106622317100000/Set-up-and-manage-2-step-verification

### Anything else?

Gusto provides additional information about branding here: https://gusto.com/wp-content/uploads/2019/08/Gusto-brand-guidelines.pdf

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Gusto.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*

**Comment by jvanderen1** [comment]
Thanks!
