### ISSUE TITLE
Icon request: AList

### ISSUE THREAD

**Issue by lituo666** [krisu5/aegis-icons#828]
### URL for the brand / site / app

https://alist.nn.ci

### Logo resources for the icon

https://github.com/alist-org/logo

### Proof of the Aegis-compatible 2FA

https://alist.nn.ci/guide/advanced/2fa.html

### Anything else?

A file list program that supports multiple storage, powered by Gin and Solidjs.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/AList.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
