### ISSUE TITLE
Icon request: Mos.ru

### ISSUE THREAD

**Issue by imelwebs** [krisu5/aegis-icons#831]
### URL for the brand / site / app

https://www.mos.ru/en/ (_sometimes_ accessible only through a Russian internet connection or VPN)

### Logo resources for the icon

[Mos.ru logo SVG](https://user-images.githubusercontent.com/3540275/218320393-51d68fc0-d2ce-4794-b955-244a403a27c2.svg) *(uploaded by maintainer for archival reasons)*

### Proof of the Aegis-compatible 2FA

https://github.com/2factorauth/twofactorauth/issues/6158
![One-Time-Password](https://user-images.githubusercontent.com/125190088/218308733-98da5b99-2581-4ffd-8a9a-1d3267472fff.png)

### Anything else?

The mos.ru website is the official website of the city of Moscow, Russia. It provides information and services to residents and visitors of the city, including news and events, city maps, public services and utilities, cultural and leisure activities, and much more. The website serves as a comprehensive resource for anyone interested in the city, including tourists, business travelers, and those who live in or are moving to Moscow. 

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Mos.ru.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
