### ISSUE TITLE
Icon request: RU-CENTER

### ISSUE THREAD

**Issue by imelwebs** [krisu5/aegis-icons#832]
### URL for the brand / site / app

https://www.nic.ru/en/

### Logo resources for the icon

https://www.nic.ru/help/logotip-ru-center_6095.html

### Proof of the Aegis-compatible 2FA

https://www.nic.ru/help/two-factor-authentication-1529/

### Anything else?

RU-CENTER is the second largest domain registrar in Russia, known for its high-quality customer support and comprehensive range of services. It offers domain registration, website hosting and development, and 24/7 technical support. One of its key features is the availability of mobile two-factor authentication, making it the largest domain registrar in Russia with this functionality.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/RU-CENTER.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
