### ISSUE TITLE
Icon request: Incogniton

### ISSUE THREAD

**Issue by imelwebs** [krisu5/aegis-icons#833]
### URL for the brand / site / app

https://incogniton.com/

### Logo resources for the icon

https://incogniton.com/wp-content/uploads/2021/08/headerOnlyIncognitonBlack.svg

### Proof of the Aegis-compatible 2FA

https://incogniton.com/knowledge%20center/guide-how-to-set-2fa-in-incogniton/

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Incogniton.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
