### ISSUE TITLE
Icon request: IServ

### ISSUE THREAD

**Issue by imelwebs** [krisu5/aegis-icons#834]
### URL for the brand / site / app

https://iserv.de/

### Logo resources for the icon

https://upload.wikimedia.org/wikipedia/commons/7/74/IServ_Logo_2022.svg

### Proof of the Aegis-compatible 2FA

https://doku.iserv.de/web/profile/#:~:text=Zur%20Aktivierung%20der%20Zwei%2DFaktor,aufgefordert%2C%20den%20zweiten%20Faktor%20einzugeben.

### Anything else?

iServ is a Debian-based, paid school server that enables the building of a school network including a web portal. Its development focus is on ease of use and administration. With various modules, users can complete tasks and participate in video conferences. It provides a secure, reliable, and simple platform for schools' educational activities.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/IServ.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
