### ISSUE TITLE
Icon request: TryHackMe

### ISSUE THREAD

**Issue by imelwebs** [krisu5/aegis-icons#835]
### URL for the brand / site / app

https://tryhackme.com/

### Logo resources for the icon

https://assets.tryhackme.com/img/logo/tryhackme_logo_full.svg
https://assets.tryhackme.com/img/THMlogo.png *(color)*

### Proof of the Aegis-compatible 2FA

https://github.com/2factorauth/twofactorauth/pull/7237
<img width="1392" alt="Screenshot 2023-02-12 at 18 58 35" src="https://user-images.githubusercontent.com/125190088/218328477-d138db48-b21e-48f2-8d09-adec9115618f.png">

### Anything else?

TryHackMe is a platform for learning and practicing ethical hacking and cyber security skills. It provides online virtual labs and challenges for users to develop and improve their hacking skills in a safe and controlled environment. Users can also interact and collaborate with other members of the community to enhance their learning experience.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/TryHackMe.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
