### ISSUE TITLE
Icon request: VDSina

### ISSUE THREAD

**Issue by imelwebs** [krisu5/aegis-icons#836]
### URL for the brand / site / app

https://vdsina.ru/

### Logo resources for the icon

https://vdsina.ru/img/v201805/content-images/white-logo-19.svg

### Proof of the Aegis-compatible 2FA

https://vdsina.ru/qa/q/kak-vklyuchit-dvukhfaktornuyu-autentifikatsiyu

### Anything else?

VDSina is a Russian hosting service provider offering virtual private servers (VPS) and dedicated servers for rent. They use NVMe disks and KVM virtualization technology, and have a custom virtual server control panel. Customers can pay daily or monthly in Russian rubles, with the option to test the service for a short period of time.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/VDSina.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
