### ISSUE TITLE
Icon request: ANY.RUN

### ISSUE THREAD

**Issue by imelwebs** [krisu5/aegis-icons#837]
### URL for the brand / site / app

https://any.run/

### Logo resources for the icon

https://any.run/media-kit/

### Proof of the Aegis-compatible 2FA

![Screenshot 2023-02-12 at 21 05 01](https://user-images.githubusercontent.com/125190088/218334500-c7a6bc1c-19cf-4d6c-87ab-4a46457afa37.png)

### Anything else?

Any.run is a cloud-based cybersecurity platform that provides a virtual environment for analyzing and inspecting malicious software in real-time. It allows security researchers and analysts to safely execute and study malware behavior, providing valuable insights into how cyberattacks are carried out and how they can be prevented.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/ANY.RUN.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
