### ISSUE TITLE
Icon request: Patronite

### ISSUE THREAD

**Issue by flav0ring** [krisu5/aegis-icons#838]
### URL for the brand / site / app

https://patronite.pl/

### Logo resources for the icon

https://patronite.pl/logotypes

### Proof of the Aegis-compatible 2FA

https://patronite.pl/app/faq/articles/43000599307
Google Translate:
https://patronite.pl/moj_profil/2fa/zmiana
![xgh](https://user-images.githubusercontent.com/125269947/218472214-39ae8089-1b14-4c84-a81c-3a04c0908b96.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Patronite.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
