### ISSUE TITLE
Icon request: Wykop.pl

### ISSUE THREAD

**Issue by flav0ring** [krisu5/aegis-icons#839]
### URL for the brand / site / app

https://wykop.pl

### Logo resources for the icon

https://wykop.pl/kontakt (at bottom, search for "logo" worded link)

### Proof of the Aegis-compatible 2FA

https://github.com/2factorauth/twofactorauth/pull/3058

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Wykop.pl.svg


:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
