### ISSUE TITLE
Icon request: 1login od WP

### ISSUE THREAD

**Issue by flav0ring** [krisu5/aegis-icons#840]
### URL for the brand / site / app

https://1login.wp.pl/informacje

### Logo resources for the icon

https://svgur.com/s/qFE

### Proof of the Aegis-compatible 2FA

https://pomoc.o2.pl/1login/jak-wlaczyc-i-wylaczyc-logowanie-dwustopniowe
https://pomoc.wp.pl/1login/jak-wlaczyc-i-wylaczyc-logowanie-dwustopniowe
Google Translate:
![Zrzut ekranu z 2023-02-13 15-04-20](https://user-images.githubusercontent.com/125269947/218479309-044c6c48-907a-4ae6-9dd7-3607859aca25.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/1login%20od%20WP.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
