### ISSUE TITLE
Icon request: Wise

### ISSUE THREAD

**Issue by Lonestarkiller6** [krisu5/aegis-icons#841]
### URL for the brand / site / app

https://wise.com

### Logo resources for the icon

https://newsroom.wise.com/en-UKI/media_kits/

### Proof of the Aegis-compatible 2FA

![2023-02-13 22_20_09-Wise_ Online Money Transfers _ International Banking Features](https://user-images.githubusercontent.com/76207732/218483506-30202b7b-1582-4044-b1c6-51786b508d9a.png)

### Anything else?

Was formerly known as TransferWise.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Wise.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*

**Comment by krisu5** [comment]
Wise got rebrand recently, so icon was replaced:

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Wise.svg
https://github.com/aegis-icons/aegis-icons/blob/master/icons/2_Variations/Wise%20fg.var.svg
