### ISSUE TITLE
Icon request: Indeed

### ISSUE THREAD

**Issue by alastortenebris** [krisu5/aegis-icons#847]
### URL for the brand / site / app

https://www.indeed.com/

### Logo resources for the icon

https://indeed.design/resources

### Proof of the Aegis-compatible 2FA

![image](https://user-images.githubusercontent.com/100882069/219909957-c3e853e7-9139-4a73-ac11-bb789ee93611.png)

> **Maintainer note:** Only accounts with "employer" status can enable 2FA.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Indeed.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
