### ISSUE TITLE
Icon submission: LimeSurvey

### ISSUE THREAD

**Issue by C0NZZ** [krisu5/aegis-icons#848]
### URL of the site or app

https://www.limesurvey.org/

### Proof of the Aegis-compatible 2FA

[https://manual.limesurvey.org/TwoFactorAdminLogin](https://manual.limesurvey.org/TwoFactorAdminLogin)

### Logo / icon info

[https://www.limesurvey.org/images/2022/logo_limesurvey.svg](https://www.limesurvey.org/images/2022/logo_limesurvey.svg)
Manually saved the SVG file used on the homepage ([https://www.limesurvey.org/](https://www.limesurvey.org/))

### Background color info

Background color is from the logo (`#14ae5c`).

### Upload icon(s)

[LimeSurvey.zip](https://github.com/aegis-icons/aegis-icons/files/10781750/LimeSurvey.zip)

### Confirmation

- [X] I have **read and carefully followed** [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) during the creation of the icon.

**Comment by krisu5** [comment]
Added with edits.
