### ISSUE TITLE
Icon submission: Rocket.Chat

### ISSUE THREAD

**Issue by C0NZZ** [krisu5/aegis-icons#849]
### URL of the site or app

https://www.rocket.chat/

### Proof of the Aegis-compatible 2FA

[https://docs.rocket.chat/use-rocket.chat/user-guides/security-bundle/two-factor-authentication-user-guide](https://docs.rocket.chat/use-rocket.chat/user-guides/security-bundle/two-factor-authentication-user-guide)

### Logo / icon info

[https://global-uploads.webflow.com/611a19b9853b7414a0f6b3f6/611bbb87319adfd903b90f24_logoRC.svg](https://global-uploads.webflow.com/611a19b9853b7414a0f6b3f6/611bbb87319adfd903b90f24_logoRC.svg)
Manually saved the SVG file used on the homepage ([https://www.rocket.chat/](https://www.rocket.chat/)).

### Background color info

Background color is from the logo (`#f5455c`).

### Upload icon(s)

[Rocket.Chat.zip](https://github.com/aegis-icons/aegis-icons/files/10807495/Rocket.Chat.zip)

### Anything else?

Logo was already submitted in #509 but wasn't following the guidelines.

### Confirmation

- [X] I have **read and carefully followed** [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) during the creation of the icon.

**Comment by krisu5** [comment]
Added to the repo.
