### ISSUE TITLE
Icon request: System76

### ISSUE THREAD

**Issue by pseudacris** [krisu5/aegis-icons#850]
### URL for the brand / site / app

https://system76.com/

### Logo resources for the icon

https://github.com/system76/brand

### Proof of the Aegis-compatible 2FA

https://github.com/2factorauth/twofactorauth/issues/6940

[Screenshot_20230223-043200](https://user-images.githubusercontent.com/86464203/220906620-a730c119-d7ce-49fc-9776-ae39882b1585.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/System76.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
