### ISSUE TITLE
Icon submission: Apache Guacamole

### ISSUE THREAD

**Issue by gnulab-id** [krisu5/aegis-icons#851]
### URL of the site or app

https://guacamole.apache.org/

### Proof of the Aegis-compatible 2FA

[Guacamole TOPT](https://guacamole.apache.org/doc/gug/totp-auth.html)

### Logo / icon info

[Guacamole Icon](https://guacamole.apache.org/images/guacamole-logo-64.png)

### Background color info

![2023-02-28_161108](https://user-images.githubusercontent.com/52167826/221806332-00f82990-15f1-4ba7-8378-2242a49752b9.png)

### Upload icon(s)

[Guacamelo.zip](https://github.com/aegis-icons/aegis-icons/files/10848346/Guacamelo.zip)

### Confirmation

- [X] I have **read and carefully followed** [CONTRIBUTING document](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) during the creation of the icon.

**Comment by krisu5** [comment]
> Logo / icon info
> [Guacamole Icon](https://guacamole.apache.org/images/guacamole-logo-64.png)

Doesn't match what I seen on the submitted icon, more likely source is the header's logo: https://guacamole.apache.org/images/guac-logo.png. You also didn't state what tool you used for image tracing _(as stated in the issue form)_ or did you do it manually by hand.

> Background color info
> [2023-02-28_161108](https://user-images.githubusercontent.com/52167826/221806332-00f82990-15f1-4ba7-8378-2242a49752b9.png)

Doesn't answer anything where **exactly** background color is taken and further note, any of the colors in the screenshot don't actually match with icon's background color. I guess it's from the [colored icon](https://guacamole.apache.org/images/guacamole-logo-64.png)?

---

I cannot accept the icon, until these questions are answered properly. Otherwise, I reject this in 30 days.

> _Minor notes:_ issue title was missing and icon is incorrectly named.

**Comment by ghost** [comment]
Just passing by, the up-to-date Guacamole logo is [here](https://github.com/apache/guacamole-client/blob/master/guacamole/src/main/frontend/src/images/guac-tricolor.svg) (colored svg), this is the exact resource file used on the system's login page (this is a self-hosted app). The official website uses a monochrome version that's already been linked above.
![guacamole-login](https://user-images.githubusercontent.com/44501389/222124042-e523f049-b845-44f5-9236-7e380b537438.png)


The system UI itself (aside from this logo - and even that's only present on the login page) has almost no colors, it's very spartan and pretty much all grayscale (see [docs](https://guacamole.apache.org/doc/gug/using-guacamole.html)). There's only a handful of light green (`#ccddaa`) and some dark red (dangerous actions) hover highlights. I don't think either this light green or the dark shades on the website are meant as "official" colors preferable to the colored logo itself.

![guacamole-ui](https://user-images.githubusercontent.com/44501389/222127309-f60fe25d-63ea-4e84-9939-3bd827859f33.png)

**Comment by krisu5** [comment]
Thanks for info, I hope OP will confirm it.

> The system UI itself (aside from this logo - and even that's only present on the login page) has almost no colors, it's very spartan and pretty much all grayscale ...

Color should be taken from logo if possible (that colored SVG is acceptable), so this is not an issue.

**Comment by gnulab-id** [comment]
Thanks @dsvk for clarifying.

The reason why I did not submit the colored SVG was because that logo appears only on the login page of self hosted app. 

On the main website, the closest to an icon is the white color besides the word Apache Guacamole.

As for tools used, I have no idea actually. I instructed my in house graphic designer to create the icon that is fits the requirement.

So, yes, the colored SVG is correct. 

What do I do now? Resubmit with the colored SVG?

**Comment by krisu5** [comment]
> The reason why I did not submit the colored SVG was because that logo appears only on the login page of self hosted app.

I don't think [CONTRIBUTING](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) has anything that prohibits using that has logo base? As long as it's current official logo, it's fine.

> Resubmit with the colored SVG?

Use [that logo vector](https://github.com/apache/guacamole-client/blob/master/guacamole/src/main/frontend/src/images/guac-tricolor.svg) excluding the black circle as logo base and make it white just like it's currently, use colored logo's green color as background color for icon template.

**Don't submit anything "just as is" from the web.**

[CONTRIBUTING](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md) has you covered with instructions.

**Comment by krisu5** [comment]
Closed as stale.
