### ISSUE TITLE
Icon request: Cults

### ISSUE THREAD

**Issue by HEPOSHEIKKI** [krisu5/aegis-icons#852]
### URL for the brand / site / app

https://cults3d.com/en

### Logo resources for the icon

https://cults3d.com/en/press

### Proof of the Aegis-compatible 2FA

https://cults3d.com/en/questions#2fa

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Cults.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
