### ISSUE TITLE
Icon request: Bitrefill

### ISSUE THREAD

**Issue by CodeShakingSheep** [krisu5/aegis-icons#853]
### URL for the brand / site / app

https://www.bitrefill.com/

### Proof of the Aegis-compatible 2FA

https://bitrefill.zendesk.com/hc/en-us/articles/4755755118610-How-do-I-reset-or-remove-my-two-factor-authentication-2FA-

### Anything else?

There is an inlined logo SVG on the official website.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Bitrefill.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
