### ISSUE TITLE
Icon request: GBAtemp (forum)

### ISSUE THREAD

**Issue by HEPOSHEIKKI** [krisu5/aegis-icons#854]
### URL for the brand / site / app

https://gbatemp.net/

### Logo resources for the icon

https://gbatemp.net/styles/ts32/tempy.svg

### Proof of the Aegis-compatible 2FA

![gbatemp-2fa](https://user-images.githubusercontent.com/51783206/222729956-431b30ee-9e66-4d30-a1dd-e8769ca946f7.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

> **Maintainer note:** _has over 250 000 forum users, passes [icon acceptability criteria](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#case-by-case-basis)_

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/GBAtemp.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
