### ISSUE TITLE
Icon request: Marketplace.tf

### ISSUE THREAD

**Issue by HEPOSHEIKKI** [krisu5/aegis-icons#855]
### URL for the brand / site / app

https://marketplace.tf/

### Logo resources for the icon

https://marketplace.tf/safari-pinned-tab.svg

> **Maintainer note:** *badly image traced from raster, needs manual fixing. Don't use it as it is.*

https://blapature.org/wp-content/uploads/2022/07/MarketplaceTF-Branding-Blue.svg

> **Maintainer note:** _Check if this is close to [official logo](https://marketplace.tf/images/TitleV1.png)_

### Proof of the Aegis-compatible 2FA

https://marketplace.tf/blog/posts/MJYOVW

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Marketplace.tf.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
