### ISSUE TITLE
Icon request: Zone

### ISSUE THREAD

**Issue by HEPOSHEIKKI** [krisu5/aegis-icons#857]
### URL for the brand / site / app

https://www.zone.ee/en/

### Logo resources for the icon

https://www.zone.ee/et/meediale-ja-partnerile/

### Proof of the Aegis-compatible 2FA

https://help.zone.eu/en/kb/secure-authentication/#h2-idtotp-2fa-two-factor-authenticationtotp-2fa-8211-two-factor-authenticationh2

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
**Use proper capitalization and spelling for issue titles**, I didn't say this on the last issues since you were new, but it clearly says on the issue form:

> Please use proper capitalization / spelling for the name (check the capitalization / spelling from browser tab title or body text of their website, **not from the logo!**).

**Comment by HEPOSHEIKKI** [comment]
> **Use proper capitalization and spelling for issue titles**, I didn't say this on the last issues since you were new, but it clearly says on the issue form:
> 
> > Please use proper capitalization / spelling for the name (check the capitalization / spelling from browser tab title or body text of their website, **not from the logo!**).

My bad, I was on my phone which autocapitalized the text ✌️

**Comment by krisu5** [comment]
Filled by #870

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Zone.svg

:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
