### ISSUE TITLE
Icon request: Cuttly

### ISSUE THREAD

**Issue by HEPOSHEIKKI** [krisu5/aegis-icons#858]
### URL for the brand / site / app

https://cutt.ly

### Logo resources for the icon

https://cutt.ly/img/c_logo.svg

### Proof of the Aegis-compatible 2FA

https://cutt.ly/resources/support/get-started/how-to-login-with-cuttly

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Filled by #871

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Cuttly.svg

:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
