### ISSUE TITLE
Icon request: Goregrish (forum)

### ISSUE THREAD

**Issue by HEPOSHEIKKI** [krisu5/aegis-icons#859]
### URL for the brand / site / app

*Removed by maintainer (highly immoral)*

### Proof of the Aegis-compatible 2FA

*Removed by maintainer (highly immoral)*

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
[We only make icons for really popular forums](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#case-by-case-basis) (at least over 250,000 total members and high posting activity). For forums under the requirements, forum software related icons are the prefer solution.

This forum only has 344,003 members.

Use ** XenForo** icon (the forum software) or generic **Chat** icon instead.

**Comment by krisu5** [comment]
I consider this in "icon acceptability criteria" as [not approved](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#not-approved).

> Apps / sites focusing on **highly** immoral and illegal activity / material.

Gore is subject that's highly immoral and possibly illegal one.
