### ISSUE TITLE
Icon request: Hostingpalvelu

### ISSUE THREAD

**Issue by HEPOSHEIKKI** [krisu5/aegis-icons#860]
### URL for the brand / site / app

https://www.hostingpalvelu.fi/en

### Proof of the Aegis-compatible 2FA

https://www.hostingpalvelu.fi/ohjeet/webhotelli-ohjeet/hallintapaneeli/kaksivaiheisen-tunnistautumisen-kayttoonotto/

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Hostingpalvelu.svg
https://github.com/aegis-icons/aegis-icons/blob/master/icons/2_Variations/Hostingpalvelu%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
