### ISSUE TITLE
Icon request: SpeedyPage

### ISSUE THREAD

**Issue by 3xploiton3** [krisu5/aegis-icons#861]
### URL for the brand / site / app

https://speedypage.com

### Proof of the Aegis-compatible 2FA

![image](https://user-images.githubusercontent.com/19517680/223287935-b8ebbfac-44a2-46ef-bd32-c4cded158d7f.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Please use proper issue title as instructed on the issue form.

Also the problem with screenshot is that it doesn't answer if it actually has Aegis compatible 2FA, please show the setup page with **censored** QR code or part where it says "Google Authenticator" / "Authy" / "(T)OTP".

**Comment by 3xploiton3** [comment]
*Removed by maintainer for security reasons (Aegis screenshot of TOTP display code)*

**Comment by krisu5** [comment]
Not what I meant at all (I meant in the website, not on the Aegis app), but okay fine. I'll go with it **this time**, next time I'm not so generous. Please be mindful about this in the future.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/SpeedyPage.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
