### ISSUE TITLE
Icon request: Ultimaker

### ISSUE THREAD

**Issue by fiorins** [krisu5/aegis-icons#862]
### URL for the brand / site / app

https://ultimaker.com

### Logo resources for the icon

*Removed by maintainer (Google image search link)*

### Proof of the Aegis-compatible 2FA

https://support.makerbot.com/s/article/1667411531300

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Ultimaker.svg
https://github.com/aegis-icons/aegis-icons/blob/master/icons/2_Variations/Ultimaker%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
