### ISSUE TITLE
Icon request: DNS.services

### ISSUE THREAD

**Issue by Willow0349** [krisu5/aegis-icons#865]
### URL for the brand / site / app

https://dns.services/

### Proof of the Aegis-compatible 2FA

https://dns.services/news/view/12/2-faktor-godkendelse/

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/DNS.services.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
