### ISSUE TITLE
Icon request: Fandom

### ISSUE THREAD

**Issue by Lumaeris** [krisu5/aegis-icons#872]
### URL for the brand / site / app

https://www.fandom.com

### Logo resources for the icon

https://fandomdesignsystem.com/?path=/story/assets-brand--brand

### Proof of the Aegis-compatible 2FA

https://community.fandom.com/wiki/User_blog:DToast/Arrived:_Two-Factor_Authentication_for_Fandom_Accounts

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Filled by #874

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Fandom.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
