### ISSUE TITLE
Icon request: Borlabs

### ISSUE THREAD

**Issue by CodeShakingSheep** [krisu5/aegis-icons#876]
### URL for the brand / site / app

https://borlabs.io/

### Proof of the Aegis-compatible 2FA

https://borlabs.io/borlabs-service-our-new-account-area/ 

### Anything else?

Unfortunately, I didn't find logo resources for the icon.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
> ### Proof of the Aegis-compatible 2FA
> 
> https://borlabs.io/borlabs-service-our-new-account-area/

Proof is not good enough, as stated on the issue form:

> Note – Documentation link or screenshot should clearly mention that 2FA is "TOTP" / "OTP" or any TOTP 2FA app (eg. Google Authenticator, Microsoft Authenticator etc.) or show section of the 2FA setup page with (censored) TOTP 2FA QR code image. Otherwise we cannot be sure if 2FA actually is compatible for Aegis.

[The page](https://borlabs.io/borlabs-service-our-new-account-area/) only says "You can also activate the two-factor authentication we recommend." and no screenshots of the 2FA process.

Please provide screenshot of the 2FA area that resolves this issue.

**Comment by CodeShakingSheep** [comment]
Ok, here is a screenshot of the 2FA area. Unfortunately, it is in German but I highlighted the relevant parts. Please let me know if this is sufficient. Thanks.

![image](https://user-images.githubusercontent.com/19874562/229116340-12ccd58a-a55e-45e1-9afa-f5ecc4208a2c.png)

**Comment by krisu5** [comment]
Yes, this is acceptable. Thank you.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Borlabs.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
