### ISSUE TITLE
Icon request: Derpibooru

### ISSUE THREAD

**Issue by ItzF1ker1** [krisu5/aegis-icons#877]
### URL for the brand / site / app

https://www.derpibooru.org/

### Logo resources for the icon

https://www.derpibooru.org/favicon-1d9b18a7f91980befac934757ed800f5.svg

### Proof of the Aegis-compatible 2FA

![F1K_Tuesday_28_March_14_2023_PM-02-57-55-685-1679990275_1903x371_Two_Factor_Authentication_-_Derpibo](https://user-images.githubusercontent.com/70688563/228168766-504629a9-3f8b-40bb-be74-68a8043a8f98.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
> ### Proof of the Aegis-compatible 2FA
> ![F1K_Tuesday_28_March_14_2023_PM-02-57-55-685-1679990275_1903x371_Two_Factor_Authentication_-_Derpibo](https://user-images.githubusercontent.com/70688563/228168766-504629a9-3f8b-40bb-be74-68a8043a8f98.png)

Proof is not good enough, as stated on the issue form:

> Note – Documentation link or screenshot should clearly mention that 2FA is "TOTP" / "OTP" or any TOTP 2FA app (eg. Google Authenticator, Microsoft Authenticator etc.) or show section of the 2FA setup page with (censored) TOTP 2FA QR code image. Otherwise we cannot be sure if 2FA actually is compatible for Aegis.

Please provide screenshot or documentation link that resolves this issue.

**Comment by ItzF1ker1** [comment]
oh i see, i couldn't find the documentation so ill provide the censored qr code and secret key
![image](https://user-images.githubusercontent.com/70688563/228251511-8975a5ff-eb7e-495b-80db-acbf01bca6f8.png)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Derpibooru.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
