### ISSUE TITLE
Icon request: Battlestate Games (Escape from Tarkov)

### ISSUE THREAD

**Issue by llricci** [krisu5/aegis-icons#878]
### URL for the brand / site / app

https://www.escapefromtarkov.com/?lang=en

### Proof of the Aegis-compatible 2FA

https://forum.escapefromtarkov.com/topic/75988-accounts-security/

### Anything else?

With all this things happening in Ukraine, I understand if you do not want to add a icon for a Russia gamedev. Just tell me if so

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by llricci** [comment]
![Further 2FA proof](https://user-images.githubusercontent.com/62891523/228229466-5540e69f-54bd-4de4-980e-128fc8b8a10a.png)

**Comment by krisu5** [comment]
We're okay with Russian-based services, as long as they follow [icon acceptability criteria](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#icon-acceptability-criteria). If suggested service is clear propaganda machine, then we would decline it.

But please don't change the issue title formatting.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Battlestate%20Games.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
