### ISSUE TITLE
Icon request: Epik

### ISSUE THREAD

**Issue by ghost** [krisu5/aegis-icons#880]
### URL for the brand / site / app

https://www.epik.com/

### Logo resources for the icon

https://id.epik.com/auth/resources/4wrd3/welcome/epik/img/logopack/epik-red2.svg

### Proof of the Aegis-compatible 2FA

https://support.epik.com/hc/en-us/articles/10721574479771-How-to-add-2-factor-authentication-in-Epik-com

### Anything else?

Link to another svg file: https://www.epik.com/themes/epik/assets/img/svg/logo.svg

### Confirmation

- [x] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Rejected because of "[icon acceptability criteria](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#icon-acceptability-criteria)":

> - Platforms having massive hate speech group following and poor moderation (a.k.a. "Alt-tech").
>   - *Examples (not limited to):* [most of the platforms listed here](https://en.wikipedia.org/wiki/Alt-tech#Platforms).

Duplicate of #234.
