### ISSUE TITLE
Icon request: BingX

### ISSUE THREAD

**Issue by Armin-GS** [krisu5/aegis-icons#881]
### URL for the brand / site / app

https://bingx.pro/en-us/

### Proof of the Aegis-compatible 2FA

https://support.bingx.com/hc/en-001/articles/360045555233-Instructions-for-Google-Authentication

### Anything else?

I have successfully manually added an account using TOTP/SHA1/30 sec/6 digits default settings.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/BingX.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
