### ISSUE TITLE
Icon request: Jottacloud

### ISSUE THREAD

**Issue by BingoKingo** [krisu5/aegis-icons#882]
### URL for the brand / site / app

https://www.jottacloud.com/en/

### Proof of the Aegis-compatible 2FA

https://docs.jottacloud.com/en/articles/1292931

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Jottacloud.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
