### ISSUE TITLE
Icon request: Nifty Gateway

### ISSUE THREAD

**Issue by BingoKingo** [krisu5/aegis-icons#884]
### URL for the brand / site / app

https://www.niftygateway.com/

### Proof of the Aegis-compatible 2FA

https://help.niftygateway.com/hc/en-us/articles/360061942154-Setting-up-Two-Factor-Authentication-on-Nifty-Gateway

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Nifty%20Gateway.svg
https://github.com/aegis-icons/aegis-icons/blob/master/icons/2_Variations/Nifty%20Gateway%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
