### ISSUE TITLE
Icon request: Qiita

### ISSUE THREAD

**Issue by BingoKingo** [krisu5/aegis-icons#885]
### URL for the brand / site / app

https://qiita.com/

### Logo resources for the icon

https://help.qiita.com/ja/articles/others-brand-guideline

### Proof of the Aegis-compatible 2FA

https://qiita.com/settings/two_factor_authentication/configure
https://qiita.com/login/otp
and

![IMG_1574](https://user-images.githubusercontent.com/24961267/229087858-02145764-b850-464a-8591-63e8436a5862.jpeg)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Qiita.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
