### ISSUE TITLE
Icon request: redirect.pizza

### ISSUE THREAD

**Issue by BingoKingo** [krisu5/aegis-icons#886]
### URL for the brand / site / app

https://redirect.pizza/

### Proof of the Aegis-compatible 2FA

https://redirect.pizza/profile
shows
[IMG_1578](https://user-images.githubusercontent.com/24961267/229091713-323e1c39-72fa-4bf0-8d91-d2ac9b142b73.jpeg)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/redirect.pizza.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
