### ISSUE TITLE
Icon request: Leantime

### ISSUE THREAD

**Issue by CodeShakingSheep** [krisu5/aegis-icons#887]
### URL for the brand / site / app

https://leantime.io/

### Logo resources for the icon

https://seeklogo.com/vector-logo/470336/leantime

### Proof of the Aegis-compatible 2FA

Unfortunately, the 2FA is not well documented. It is just mentionned briefly in the system requirements under the optional PHP modules. So, I attached screenshots right away. Please let me know if these are sufficient. Otherwise, I need to remove 2FA and re-enable it to make a screenshot of the QR code process.

https://docs.leantime.io/#/installation/system-requirements?id=system-requirements

[image](https://user-images.githubusercontent.com/19874562/229272510-2c925f21-5773-414d-8dd8-c92fbc0a7350.png)

[image](https://user-images.githubusercontent.com/19874562/229272660-cccca474-0b83-4d88-addb-0ca5f3c8e40e.png)

### Anything else?

Unfortunately, I didn't find official logo resources, only the SVG on SeekLogo. Nevertheless, that might be a starting point.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
> Otherwise, I need to remove 2FA and re-enable it to make a screenshot of the QR code process.

Unfortunately that is needed, if nothing else is available. These screenshots aren't good enough. If mentioned things from the note aren't there, it isn't acceptable. But this is good as proof: https://github.com/Leantime/leantime/issues/1432

**Comment by CodeShakingSheep** [comment]
> > Otherwise, I need to remove 2FA and re-enable it to make a screenshot of the QR code process.
> 
> Unfortunately that is needed, if nothing else is available. These screenshots aren't good enough. If mentioned things from the note aren't there, it isn't acceptable. But this is good as proof: [Leantime/leantime#1432](https://github.com/Leantime/leantime/issues/1432)

Amazing, that the link is sufficient. However, I'll keep it in mind for the future should I come across another not well-documented 2FA app for aegis. Thank you.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Leantime.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
