### ISSUE TITLE
Icon request: Pronouns.page

### ISSUE THREAD

**Issue by ghost** [krisu5/aegis-icons#888]
### URL for the brand / site / app

https://en.pronouns.page/

### Logo resources for the icon

https://gitlab.com/PronounsPage/PronounsPage/-/tree/main/static/logo

### Proof of the Aegis-compatible 2FA

[Screenshot_20230404_195130_com brave browser_1](https://user-images.githubusercontent.com/129856154/229784313-5b627546-7237-429c-a66d-01dd5e3a0b2c.jpg)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Closed because author deleted the GitHub account before request is completed (we cannot be sure if it still means that requester still wants the icon or not because of it).
