### ISSUE TITLE
Icon request: British Computer Society (BCS)

### ISSUE THREAD

**Issue by simonhollingshead** [krisu5/aegis-icons#892]
### URL for the brand / site / app

https://www.bcs.org

### Logo resources for the icon

https://sts.bcs.org/bcs-logo.svg

### Proof of the Aegis-compatible 2FA

https://imgur.com/a/GLV0syF

All the help documentation appears to be after login.  As such, here's a screenshot.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/British%20Computer%20Society.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
