### ISSUE TITLE
Icon request: Lark

### ISSUE THREAD

**Issue by AkarinLiu** [krisu5/aegis-icons#894]
### URL for the brand / site / app

https://www.larksuite.com

### Logo resources for the icon

*Removed by maintainer (raster favicon aka ICO file)*

### Proof of the Aegis-compatible 2FA

https://www.larksuite.com/hc/en-US/articles/360048488173

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Lark.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
