### ISSUE TITLE
Icon request: Logitech

### ISSUE THREAD

**Issue by McRoyce** [krisu5/aegis-icons#895]
### URL for the brand / site / app

https://www.logitech.com/

### Proof of the Aegis-compatible 2FA

https://github.com/2factorauth/twofactorauth/pull/7083

![image](https://user-images.githubusercontent.com/94728369/231372264-5ca28e2c-eaee-4deb-96b9-bc88677a20c2.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Logitech.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
