### ISSUE TITLE
Icon request: Raindrop.io

### ISSUE THREAD

**Issue by drinkcoffee247** [krisu5/aegis-icons#896]
### URL for the brand / site / app

https://raindrop.io

### Proof of the Aegis-compatible 2FA

https://blog.raindrop.io/two-factor-authentication-2fa-1a320fa2eed7

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Raindrop.io.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
