### ISSUE TITLE
Icon request: True Wealth

### ISSUE THREAD

**Issue by salim-b** [krisu5/aegis-icons#897]
### URL for the brand / site / app

https://www.truewealth.ch/

### Logo resources for the icon

https://www.truewealth.ch/en/press

### Proof of the Aegis-compatible 2FA

https://www.truewealth.ch/en/faq/security/which-app-should-i-use-for-totp-two-factor-authentication

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/True%20Wealth.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
