### ISSUE TITLE
Icon request: Grav

### ISSUE THREAD

**Issue by nichu42** [krisu5/aegis-icons#898]
### URL for the brand / site / app

https://getgrav.org

### Logo resources for the icon

https://getgrav.org/media

### Proof of the Aegis-compatible 2FA

https://learn.getgrav.org/17/admin-panel/security/2fa

### Anything else?

2FA is not for the getgrav.org web-site itself, but for any web-site that has been created using this CMS

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Grav.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
