### ISSUE TITLE
Update icon: Eneba

### ISSUE THREAD

**Issue by juanico10** [krisu5/aegis-icons#900]
### URL for the brand / site / app

https://www.eneba.com/

### Reason for update

Updated brand color

### Logo resources for the icon

https://cdn.eneba.com/branding/v2/logoFull.svg

### Anything else?

We would like the Eneba logo with the blue background.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Not valid reason, branding hasn't changed. Also see: https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#can-you-make-variation-for-x-icon
