### ISSUE TITLE
Icon request: Akamai Connected Cloud (f.k.a. Linode)

### ISSUE THREAD

**Issue by davidlemlerm** [krisu5/aegis-icons#901]
### URL for the brand / site / app

https://www.linode.com/

### Logo resources for the icon

https://www.akamai.com/newsroom/media-resources

### Proof of the Aegis-compatible 2FA

Documentation page: [Guides - Manage Two-Factor Authentication (2FA) on a User Account](https://www.linode.com/docs/products/platform/accounts/guides/2fa/)

The page recommends several authenticators including Authy, Duo Mobile, Google Authenticator, and Microsoft Authenticator, and describes how Linode uses a "time-sensitive OTP token" (AKA TOTP token) for 2 factor authentication.

Also see [directory entry on 2FA Directory](https://github.com/2factorauth/twofactorauth/blob/3675567d060a30c3986060fbe5c70b2210799a93/entries/l/linode.com.json#L6).

### Anything else?

Adding Linode's icon was initially discussed in #124 and done in 248a111e2655a9e9a54ef3cb2706abe30afff7c2, but the icon was removed in 6170a86473494686cae4c6a1a4961e38f1d94a1e due to Akamai not having TOTP 2 factor authentication, and Akamai having bought Linode.  I am not aware if Akamai has TOTP 2 factor authentication or not, but I have a Linode account and do know that Linode *does* support TOTP 2 factor authentication.  Currently, Akamai and Linode use 2 separate login systems.  It does appear that Linode is now using Akamai's icons for their branding, hence why I have included the Akamai press kit in the logo resource section.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Renamed as "Akamai Connected Cloud" because of info on Wikipedia: https://en.wikipedia.org/wiki/Linode#History

Linode as brand will be discontinued completely in some day, but I also add Linode icon back as "outdated" when this request is completed.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Akamai%20Connected%20Cloud.svg

(and Linode is now available on the outdated section of the 2023-04-23 pack)



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
