### ISSUE TITLE
Icon request: HashiCorp

### ISSUE THREAD

**Issue by davidlemlerm** [krisu5/aegis-icons#902]
### URL for the brand / site / app

https://www.hashicorp.com/

### Logo resources for the icon

https://www.hashicorp.com/brand

### Proof of the Aegis-compatible 2FA

Documentation page: [Introduction to Multi-Factor Authentication](https://developer.hashicorp.com/hcp/docs/hcp/security/mfa)

The page states:

> HCP offers one method of MFA called one-time password (OTP).

And includes an example of setting up 2 factor authentication with a scannable QR code.

Also see [entry on 2FA Directory](https://github.com/2factorauth/twofactorauth/blob/92144a7bb69f78afe0d4a18c3bb94123888df946/entries/c/cloud.hashicorp.com.json#L8).

### Anything else?

The "Brand Kit" item from the press kit page is a ZIP file.  For a square logo, the file `Brand Kit/Logos/Corporate/Logos/Logomark/RGB/SVG/HashiCorp_Logomark_Black_RGB.svg` in the ZIP file would probably be most ideal.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/HashiCorp.svg
https://github.com/aegis-icons/aegis-icons/blob/master/icons/2_Variations/HashiCorp%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
