### ISSUE TITLE
Icon request: GOV.BR

### ISSUE THREAD

**Issue by rafaelazvdo** [krisu5/aegis-icons#903]
### URL for the brand / site / app

https://www.gov.br/

### Logo resources for the icon

https://pt.m.wikipedia.org/wiki/Ficheiro:Gov.br_logo.svg

### Proof of the Aegis-compatible 2FA

![Captura de Tela (3)](https://user-images.githubusercontent.com/122113441/233817398-7b8ce1f1-030e-492d-9cce-a32dd787ab7b.png)
![Captura de Tela (4)](https://user-images.githubusercontent.com/122113441/233817401-730cc8b9-1285-4cbb-b2bc-15e0f88a9cd7.png)
![Captura de Tela (5)](https://user-images.githubusercontent.com/122113441/233817404-587b0a16-dbdd-47e2-98f3-43968da51b12.png)

### Anything else?

When looking for how to activate 2FA on the access.gov.br website, we only found instructions on how to do this through the use of an application found in the Play Store, Gov.br, but when activating 2FA, within the account settings there is the option to additionally activate "Offline 2-Step Verification" by scanning a QR code via the OTP app.

In the third screenshot of the test, I put the translation of the text of the page from Portuguese to English.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/GOV.BR.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
