### ISSUE TITLE
Icon request: Fakturoid

### ISSUE THREAD

**Issue by janvanicek** [krisu5/aegis-icons#905]
### URL for the brand / site / app

https://www.fakturoid.cz

### Logo resources for the icon

https://www.fakturoid.cz/logo

### Proof of the Aegis-compatible 2FA

https://www.fakturoid.cz/podpora/nastaveni/dvoufazove-overeni

### Anything else?

How to use logo: https://www.fakturoid.cz/logo

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Fakturoid.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
