### ISSUE TITLE
Icon request: vorsorgestiftung vsao

### ISSUE THREAD

**Issue by salim-b** [krisu5/aegis-icons#906]
### URL for the brand / site / app

https://www.vorsorgestiftung-vsao.ch/

### Logo resources for the icon

https://www.vorsorgestiftung-vsao.ch/img/logo-vorsorgestiftung-vsao.svg

### Proof of the Aegis-compatible 2FA

Screenshot of 2FA settings page (German):

[Screenshot 2023-04-25 at 12-07-57 Einstellungen - vorsorgestiftung vsao](https://user-images.githubusercontent.com/20040931/234245856-cf02c8be-0104-4468-ab8e-dbcf12b6491b.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/vorsorgestiftung%20vsao.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
