### ISSUE TITLE
Icon request: SAPO

### ISSUE THREAD

**Issue by poingg** [krisu5/aegis-icons#907]
### URL for the brand / site / app

https://www.sapo.pt

### Logo resources for the icon

https://sobre.sapo.pt/marca

### Proof of the Aegis-compatible 2FA

![Screenshot 2023-04-25 at 11 40 02](https://user-images.githubusercontent.com/194691/234253017-af38ece2-88e5-4e22-84f2-e69925319c3c.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/SAPO.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
