### ISSUE TITLE
Icon request: Well.ca

### ISSUE THREAD

**Issue by lordoftheoats** [krisu5/aegis-icons#908]
### URL for the brand / site / app

https://well.ca/

### Logo resources for the icon

https://d2i6p126yvrgeu.cloudfront.net/templates/york/images/logo-mobile-black.svg

### Proof of the Aegis-compatible 2FA

From the sign up dialogue:
<img width="443" alt="Screenshot 2023-04-26 at 1 43 14 AM" src="https://user-images.githubusercontent.com/8661442/234480480-78278176-3ac5-455a-acb0-a5e00eb0f42e.png">

### Anything else?

The linked SVG is the full logo, but the symbol alone may be preferable for use as an icon (see:favicon). Thank you!

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Well.ca.svg


:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
