### ISSUE TITLE
Icon request: Notion

### ISSUE THREAD

**Issue by LupSpie** [krisu5/aegis-icons#909]
### URL for the brand / site / app

https://notion.so

### Logo resources for the icon

https://www.notion.so/205535b1d9c4440497a3d7a2ac096286

### Proof of the Aegis-compatible 2FA

Announcement post: https://twitter.com/NotionHQ/status/1650880108696326146
Documentation page: https://www.notion.so/help/two-step-verification

### Anything else?

Love this project :heart:

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Notion.svg
https://github.com/aegis-icons/aegis-icons/blob/master/icons/2_Variations/Notion%20bg.var.svg

> Love this project ❤️

Thanks :)



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
