### ISSUE TITLE
Icon request: Braze

### ISSUE THREAD

**Issue by ixti** [krisu5/aegis-icons#910]
### URL for the brand / site / app

https://www.braze.com/

### Logo resources for the icon

https://en.wikipedia.org/wiki/File:Braze_Logo.svg

### Proof of the Aegis-compatible 2FA

[image](https://user-images.githubusercontent.com/94782/235044634-b62e4b9c-e5d5-4a68-b8d0-6bb29baf565a.png)

[image](https://user-images.githubusercontent.com/94782/235045052-2e914c18-c6a9-4981-8507-606f41abeac2.png)

[image](https://user-images.githubusercontent.com/94782/235044505-4c3859ea-78c6-4706-8711-ffa25f790249.png)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Braze.svg
https://github.com/aegis-icons/aegis-icons/blob/master/icons/2_Variations/Braze%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*

**Comment by ixti** [comment]
Thank you!
