### ISSUE TITLE
Icon request: ente

### ISSUE THREAD

**Issue by m0yP** [krisu5/aegis-icons#912]
### URL for the brand / site / app

https://ente.io

### Proof of the Aegis-compatible 2FA

https://ente.io/features

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Proof is not good enough, as stated on the issue form:

> Documentation link or screenshot should clearly mention that 2FA is (T)OTP / HOTP or any mobile 2FA app (eg. Google Authenticator, Microsoft Authenticator, LastPass Authenticator etc.) or show section of the 2FA setup page with *(censored)* OTP 2FA QR code image. **Otherwise we cannot be sure if 2FA actually is compatible for Aegis.**

Please provide screenshot or documentation link that resolves this issue. Otherwise, this issue will be closed in 30 days.

**Comment by m0yP** [comment]
Sure, here they go.

![IMG_20230501_071009_964](https://user-images.githubusercontent.com/22119314/235455920-4d6a337c-7690-4ba0-878e-c223d8fade0c.jpg)
![IMG_20230501_071004_786](https://user-images.githubusercontent.com/22119314/235455924-595ec6d3-f1bb-47bd-9906-d9a33f699d18.jpg)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/ente.svg
https://github.com/aegis-icons/aegis-icons/blob/master/icons/2_Variations/ente%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
