### ISSUE TITLE
Icon request: TikTok

### ISSUE THREAD

**Issue by imelwebs** [krisu5/aegis-icons#914]
### URL for the brand / site / app

https://www.tiktok.com

### Logo resources for the icon

https://developers.tiktok.com/doc/getting-started-design-guidelines

### Proof of the Aegis-compatible 2FA

https://support.tiktok.com/en/safety-hc/account-and-user-safety/account-safety

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/TikTok.svg
https://github.com/aegis-icons/aegis-icons/blob/master/icons/2_Variations/TikTok%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
