### ISSUE TITLE
Update icon: Brevo (f.k.a. Sendinblue)

### ISSUE THREAD

**Issue by Vucko130** [krisu5/aegis-icons#915]
### URL for the brand / site / app

https://www.brevo.com/

### Reason for update

Other (write more info to "Anything else?" section)

### Logo resources for the icon

https://www.brevo.com/press-room/

### Anything else?

Sendinblue changed their brand name to Brevo. So, Sendinblue is now Brevo, which means that Sendinblue's old icon is no longer relevant.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Brevo.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
