### ISSUE TITLE
Icon request: OpenAI (ChatGPT)

### ISSUE THREAD

**Issue by imelwebs** [krisu5/aegis-icons#917]
### URL for the brand / site / app

https://openai.com/

### Logo resources for the icon

https://openai.com/brand

### Proof of the Aegis-compatible 2FA

https://youtu.be/pv_55-mEiLE

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
There was no such settings in my OpenAI account, that video showed.

And [based of this thread](https://community.openai.com/t/2fa-for-openai-account/18498/9), it's not currently available.

**Comment by imelwebs** [comment]
This feature might only be for ChatGPT Plus users. If you have issues, try clearing your cache. To set up two-factor authentication, click the three-dot menu, go to settings, then data control. Keep in mind that it might not be available everywhere, as it's rolled out differently in various countries. In my case, my Austrian account already has this feature:
https://www.testingcatalog.com/icymi-chatgpt-updates-settings-ui-and-teases-2fa-support/ <https://www.testingcatalog.com/icymi-chatgpt-updates-settings-ui-and-teases-2fa-support/>

**Comment by krisu5** [comment]
2FA Directory [accepted](https://github.com/2factorauth/twofactorauth/pull/7569) OpenAI with TOTP feature, so I accept it as well.

**Comment by rafaelazvdo** [comment]
I'm from Brazil and 2FA TOTP in Open AI ChatGPT is available to enable in my account with free plan.
![Captura de Tela (7)](https://user-images.githubusercontent.com/122113441/236646287-fea48e9b-c54c-40c9-ad69-cc2cde3b41aa.png)
![Captura de Tela (8)](https://user-images.githubusercontent.com/122113441/236646293-0776b096-1aec-45e8-b16f-1d01fc654b57.png)

**Comment by imelwebs** [comment]
Good to know. Thanks for your work  💪

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/OpenAI.svg
https://github.com/aegis-icons/aegis-icons/blob/master/icons/2_Variations/OpenAI%20bg.var.svg


:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
