### ISSUE TITLE
Icon request: WhiteBIT

### ISSUE THREAD

**Issue by ThunderF0x** [krisu5/aegis-icons#919]
### URL for the brand / site / app

https://whitebit.com/

### Logo resources for the icon

https://whitebit.com/brand-guideline

### Proof of the Aegis-compatible 2FA

https://blog.whitebit.com/en/what-is-two-factor-authentication/

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/WhiteBIT.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
