### ISSUE TITLE
Icon request: Codeanywhere

### ISSUE THREAD

**Issue by Awzri** [krisu5/aegis-icons#921]
### URL for the brand / site / app

https://codeanywhere.com

### Logo resources for the icon

https://codeanywhere.com/media

### Proof of the Aegis-compatible 2FA

https://docs.codeanywhere.com/general/getting-started/faq#how-to-enable-two-factor-authentication

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Codeanywhere.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
