### ISSUE TITLE
Icon request: deSEC

### ISSUE THREAD

**Issue by burnoutprojects** [krisu5/aegis-icons#922]
### URL for the brand / site / app

https://desec.io

### Logo resources for the icon

https://desec.io/img/logo.d22c6d53.svg

### Proof of the Aegis-compatible 2FA

https://desec.readthedocs.io/en/latest/auth/account.html#factor-authentication

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Proof is not good enough, as stated on the issue form:

> Documentation link or screenshot should clearly mention that 2FA is (T)OTP / HOTP or any mobile 2FA app (eg. Google Authenticator, Microsoft Authenticator, LastPass Authenticator etc.) or show section of the 2FA setup page with *(censored)* OTP 2FA QR code image. **Otherwise we cannot be sure if 2FA actually is compatible for Aegis.**

Please provide screenshot or documentation link that resolves this issue. Otherwise, this issue will be closed in 30 days.

**Comment by burnoutprojects** [comment]
Hello @krisu5, here is a screenshot from the 2fa settings inside the site.

![desec io_totp](https://github.com/aegis-icons/aegis-icons/assets/16170502/1f752751-07bd-4ec6-af54-ad378a82fc5d)

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/deSEC.svg
https://github.com/aegis-icons/aegis-icons/blob/master/icons/2_Variations/deSEC%20bg.var.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
