### ISSUE TITLE
Icon request: Vivaldi

### ISSUE THREAD

**Issue by ztNFny** [krisu5/aegis-icons#923]
### URL for the brand / site / app

https://vivaldi.com

### Logo resources for the icon

https://vivaldi.com/press/

### Proof of the Aegis-compatible 2FA

https://help.vivaldi.com/services/account/two-factor-authentication/

### Anything else?

~~Press kit contains red logo but community - for which the 2FA is - uses #3f78eb as color~~

> **Maintainer note:** _Icon should be made based of Vivaldi **browser**'s branding (red)._

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Vivaldi.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*

**Comment by ztNFny** [comment]
Thabks for the quick work.

> Maintainer note: Icon should be made based of Vivaldi browser's branding (red).

Why? The 2FA is for the community which uses blue?

**Comment by krisu5** [comment]
> > Maintainer note: Icon should be made based of Vivaldi browser's branding (red).
> 
> Why? The 2FA is for the community which uses blue?

Because account also works on the browser, they have only one account system for both community and browser sync. 2FA support for browser sync is TBA, but I rather design it based of original branding now.
