### ISSUE TITLE
Icon request: Spaceship

### ISSUE THREAD

**Issue by Trip7274** [krisu5/aegis-icons#924]
### URL for the brand / site / app

https://www.spaceship.com/

### Logo resources for the icon

https://drive.google.com/file/d/1ZXiRpw4ZjSIuX7i_pLSCBmbgrvDQ5jhP/view

### Proof of the Aegis-compatible 2FA

![Screenshot 2023-05-16 at 00-18-36 Launch into the future - Spaceship](https://github.com/aegis-icons/aegis-icons/assets/42869384/92b56dc7-4479-4b00-bc46-06d8f7bac9b0)
![Screenshot 2023-05-16 at 00-21-29 Two Factor Authentication - Security Center - Spaceship](https://github.com/aegis-icons/aegis-icons/assets/42869384/291fb2e2-5628-4460-9916-eec671fe0124)

### Anything else?

I had to link the icon resources on my Google Drive since it was an inline HTML and I wasn't sure how to link it, but it was from their main page, i just saved it as a .svg by copying the code onto a text file and renaming it's extension as an .svg
Much thanks for your time and I hope I provided accurate and helpful info!

### Confirmation

- [x] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Spaceship.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
