### ISSUE TITLE
Icon request: Bitwage

### ISSUE THREAD

**Issue by eloyesp** [krisu5/aegis-icons#925]
### URL for the brand / site / app

https://www.bitwage.com/

### Proof of the Aegis-compatible 2FA

It is the second option here: https://support.bitwage.com/two-factor-authentication

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Rejected because of "[icon acceptability criteria](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#icon-acceptability-criteria)":

> - **Unregulated** (crypto) currency trading / investing platforms.
>   - Checked with [WikiBit](https://www.wikibit.com), [WikiFX](https://www.wikifx.com/en/) and/or Google.
>   - If no regulation information is found, request / submission is also rejected.
>   - Why this restriction?
>     1. So many of these platforms are scams or operate company illegally in other ways.
>     2. Too many requests for these platforms and high maintenance for it.
>     3. Checking regulation is the only way to somewhat certainly say of the legality of the company.

No regulation information found.

**Comment by eloyesp** [comment]
This is a crypto company, but there is no trading or investing involved, it is a payroll service, so they don't have user's crypto. They are not regulated as a trading company just because they are not, just searched on wikibit and wikifx and they do not show there (because it is not an exchange).

**Comment by krisu5** [comment]
I let this back because of misunderstanding.

**Comment by krisu5** [comment]
Here you go!

https://github.com/aegis-icons/aegis-icons/blob/master/icons/1_Primary/Bitwage.svg



:question: *[How to add icon(s) to Aegis?](https://github.com/aegis-icons/aegis-icons/blob/master/FAQ.md#manually)*

:star: *Support this project by giving a star! Just adding like to this comment is also appreciated.*
