### ISSUE TITLE
Icon request: ARGENBTC

### ISSUE THREAD

**Issue by eloyesp** [krisu5/aegis-icons#926]
### URL for the brand / site / app

https://argenbtc.com/

### Logo resources for the icon

https://argenbtc.com/img/logos/iso_ftr.svg

### Proof of the Aegis-compatible 2FA

In the instructions here: https://argenbtc.com/vender-bitcoins-en-pesos (in spanish) the second step is enabling 2FA and Google Authenticator is mentioned.

### Anything else?

The site is in Spanish only.

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
Rejected because of "[icon acceptability criteria](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#icon-acceptability-criteria)":

> - **Unregulated** (crypto) currency trading / investing platforms.
>   - Checked with [WikiBit](https://www.wikibit.com), [WikiFX](https://www.wikifx.com/en/) and/or Google.
>   - If no regulation information is found, request / submission is also rejected.
>   - Why this restriction?
>     1. So many of these platforms are scams or operate company illegally in other ways.
>     2. Too many requests for these platforms and high maintenance for it.
>     3. Checking regulation is the only way to somewhat certainly say of the legality of the company.

See https://www.wikibit.com/en/dr/1402948431220.html

**Comment by eloyesp** [comment]
Hi, I cannot understand this, there is no regulatory for this kind of company on Argentina but AFIP, and they are registered there. There is a link on the bottom-right of the page with the regulation link: http://qr.afip.gob.ar/?qr=PzVFOFe5pJKWhThDohIsXg,, (gob is for government on spanish). There are no other license available on Argentina and they only support Argentina...

That said, it is mostly sure that the company is not entirely legal, but they seems to be as legal as the rest of the companies on the world (I'm mostly sure that google, meta and microsoft are doing ilegal stuff (and lot of that).

**Comment by krisu5** [comment]
Sorry, but it stays closed. That link isn't for regulation info, it's complaint form.

We are more strict to these kinds of services as mentioned in the issue guidelines and we stick to them.

You can always use generic icons or add picture from internet as icon. We are not only source.

> I'm mostly sure that google, meta and microsoft are doing ilegal stuff 

Possibly, but these are not count as full on scams like FTX, Celsius and others are now. Biggest reason why I did the change, you cannot even trust big guys in that business. And personally TBH: I'm sick of making icons for crypto businesses. If that's a problem, then I'm sorry.

This is final.
