### ISSUE TITLE
Icon request: Pi-hole Userspace (forum)

### ISSUE THREAD

**Issue by erfirya** [krisu5/aegis-icons#929]
### URL for the brand / site / app

https://discourse.pi-hole.net/

### Proof of the Aegis-compatible 2FA

![Screenshot_20230520-233422_Mull](https://github.com/aegis-icons/aegis-icons/assets/71990871/798ecf94-f8ed-446e-b5be-d5fd2d888832)

### Confirmation

- [X] I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.

**Comment by krisu5** [comment]
[We only make icons for really popular forums](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#case-by-case-basis) (at least over 250,000 total members and high posting activity). For forums under the requirements, forum software related icons are the prefer solution.

This forum only has [21830](https://discourse.pi-hole.net/u?order=likes_received) members.

Use one of the **Discourse** icons (the forum software) or generic **Chat** icon instead.
