### ISSUE TITLE
🏝 Taking a break

### ISSUE THREAD

**Issue by krisu5** [krisu5/aegis-icons#931]
Taking a break once again, issue section closed from creating new issues. I'm focusing on [the other tasks of the project](https://github.com/aegis-icons/aegis-icons/issues/863) and IRL stuff.

**Reason for break:** I'm only maintainer on this project and to avoid burnout, I don't want huge amount of stuff to moderate during this time.

_Few things during the break:_
- **Do not create issues!**
  - Bypassing the notice when clicking "new issue" and making issue anyway **will give you a ban and instant delete for the issue!**
- **No icon requests / non-PR submissions via comment either to any of issues, PRs or anywhere else!**
  - Warning for the first offense, second time equals ban.
  - Comments that aren't related to those are fine (comment them here on this issue).
- ~~PRs are allowed.~~ See bottom comment.

**Comment by krisu5** [comment]
### Important update!

PRs are temporarily **NOT ALLOWED** until I have revisioned CONTRIBUTING guidelines about icon grid and other stuff.

:warning: **New PRs during this state will be closed without further notice.**

*Subscribe to #938 to know when PRs are allowed again.*

**Comment by Hypfer** [comment]
Just FYI if you didn't know:

You can use GitHub interaction limits to achieve this. 
By setting those to collaborators only, you can still work in the repo but anyone wanting to open an issue, comment or do anything that would require energy from you only sees a message box that that isn't possible at the current time.

![image](https://github.com/aegis-icons/aegis-icons/assets/974410/f6834e4e-c52f-444a-8dc2-b587e43bdb3b)

**Comment by Densh0** [comment]
Just wanted to thank you for this project!

**Comment by salicius** [comment]
Would you be willing to pass the project on to others?

**Comment by krisu5** [comment]
> Would you be willing to pass the project on to others?

Okay, I guess it's time to break the silence from me: I'm not sure and even if I decide this, I can't say when.

Few months after break started, I got too busy with stuff on school / personal life and finally burned out on this project, so it's uncertain if I continue on it. It had over 4 year run, which is pretty long for most FOSS projects.

There are other parts outside of GitHub that also possibly need migration (eg. Notion databases) **and** I would also need volunteers that understand how to make icons with all the standards in mind.

But for now this project is on indefinite hiatus.

**Comment by SynapseScribe** [comment]
On https://aegis-icons.github.io/ it is still specified that the icon pack is updated monthly. Would be good to remove that so that people don't spend time updating the icon pack over and over again with the same version.

**Comment by krisu5** [comment]
I will remove it someday but there's also release date under it, so it's not that big of the issue

**Comment by krisu5** [comment]
> On https://aegis-icons.github.io/ it is still specified that the icon pack is updated monthly. Would be good to remove that so that people don't spend time updating the icon pack over and over again with the same version.

Done.

**Comment by thisisgregm** [comment]
Would you be interested to bring it back to life if there will be more contributors / maintainers? I'm happy to help.

**Comment by krisu5** [comment]
I decided to archive this project.

I don't have time or mental energy for finding new maintainers and there's now too many things broken or even removed (e.g. GitHub deleted old projects boards).
